src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <label>Date Of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Update Required</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>On List</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Black__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Black</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible Citizen</fullName>
                </value>
                <value>
                    <fullName>Eligible Non - Citizen</fullName>
                </value>
                <value>
                    <fullName>Ineligible Non-Citizen</fullName>
                </value>
                <value>
                    <fullName>Pending Verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Not Hispanic or Latino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Annual_Income__c</fullName>
        <label>Family Annual Income</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>Spouse First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Spouse Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PBVS_Project_Based_Single__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PBS-Project Based Single</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PBV_Project_Based__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PBV-Project Based</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Public_Housing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Public Housing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section_8__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section 8</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>White__c</fullName>
        <defaultValue>false</defaultValue>
        <label>White</label>
        <type>Checkbox</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checkbox_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Community Global User</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Housing Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Inspector</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>On-Site Manager</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Property Manager</fullName>
                </value>
                <value>
                    <fullName>Rehab HC Specialist</fullName>
                </value>
                <value>
                    <fullName>Resident Manager</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First - Housing Our Heroes</fullName>
                </value>
                <value>
                    <fullName>Landlord/Owner</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Community Member</fullName>
                </value>
                <value>
                    <fullName>Housing Specialist</fullName>
                </value>
                <value>
                    <fullName>Section 3 Resident</fullName>
                </value>
                <value>
                    <fullName>Primary Business Contact</fullName>
                </value>
                <value>
                    <fullName>Business Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Business Admin Contact</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Payroll Contact</fullName>
                </value>
                <value>
                    <fullName>Co-Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First Client_FY18</fullName>
                </value>
                <value>
                    <fullName>Housing First Client - FY17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Do_not_Have__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do not Have</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Residential_City__c</fullName>
        <label>Residential City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_State__c</fullName>
        <label>Residential State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_Street__c</fullName>
        <label>Residential Street</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_Zipcode__c</fullName>
        <label>Residential Zipcode</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>Rental Assistance Wait List Portal Record Type</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RAD_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Portal_Contact_Address__c</fullName>
        <label>Portal Contact Address</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Portal_Forgot_Password_Note__c</fullName>
        <label>Portal Forgot Password Note</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Portal_Forgot_UserName_Note__c</fullName>
        <label>Portal Forgot UserName Note</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Purge_Extension_Months__c</fullName>
        <description>Purge Extension in months</description>
        <label>Purge Extension(Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update_Duration_Months__c</fullName>
        <label>Update Duration (Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RAD Configuration</label>
    <nameField>
        <label>RAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Selection_Records__c.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Selection Record</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selection Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/classes/Rad_PublishingPrintLabl_Test.cls
@isTest
public class Rad_PublishingPrintLabl_Test {
public static testMethod void RefLetterpdf()
{
list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
sw_list.add(sw);
SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
sw_list.add(swWL);
insert sw_list;
RAD_Configuration__c  confg = new RAD_Configuration__c(Name = 'Main Configurations', Update_Duration_Months__c = 6, RAD_Purge_Extension_Months__c =1,
                RAD_Portal_Forgot_Password_Note__c ='This is Forgotten Password Note', RAD_Portal_Forgot_UserName_Note__c ='This is Forgotten Username Note',
                RAD_Portal_Contact_Address__c = 'This is Portal Contact Address', Announcement__c = 'This is Announcement');

            insert confg;
 
   User thisUser = [select Id from User where Id = :UserInfo.getUserId()];
    //Id RecTypeaccount=Schema.SObjectType.account.getRecordTypeInfosByName().get('RAD Community Account').getRecordTypeId();
     Id idd = Schema.SObjectType.Account.getRecordTypeInfosByName().get('RAD Community Account').getRecordTypeId();
        
       Account A1 = new Account(Name = 'Test Account', OwnerId=thisUser.Id,First_Name__c='test',Last_Name__c='test',RecordTypeId=idd
 );
      
        insert A1;
          Id idd1 = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        
           Contact  ct = new Contact();
            ct.FirstName = 'firstname';
            ct.LastName = 'lName';
            ct.email = 'test@cgi.com';
            ct.accountId = A1.id;
            ct.Contact_Type__c  = 'Community Global User';
            ct.Do_not_Have__c  = true;
            ct.Date_of_Birth__c  = Date.Today().addMonths(-400);
            ct.Gender__c = 'Female';
            
            ct.Residential_Street__c=  'Residency Street'; 
            ct.Residential_City__c = 'San Diego';
            ct.Residential_State__c = 'CA';
            ct.Residential_Zipcode__c ='71117';
            
            ct.MailingStreet = 'EastMail Street'; 
            ct.MailingCity = 'San Diego';
            ct.MailingState = 'CA';
            ct.MailingPostalCode ='71119';
            ct.RecordTypeId = idd1;
            ct.Active__c='Yes';

        
            insert ct;
            
            Applications__c app = new Applications__c(); 
            app.Applicant__c = ct.id;
            app.Ethnicity__c = 'Hispanic or Latino';
            app.Section_8__c =true;
            app.PBVS_Project_Based_Single__c = true;
            app.PBV_Project_Based__c =true;
            app.Public_Housing__c = true;
            app.Application_Status__c = 'Update Required';
            app.Family_Annual_Income__c = Decimal.valueOf('1000');
            app.White__c =  true;
            app.Black__c = true;
            app.Citizenship__c = 'Eligible Citizen';
            app.of_people_in_the_H_H_Adults__c = 1;
            //app.Dependents_Children_under_age_of_18__c = '1';
            app.Family__c = true; 
            app.RAD_Next_Purge_Request_Date__c=Date.Today().addMonths(-400);
            insert app;
            
 
 
     Wait_List_Type__c  wlt=new  Wait_List_Type__c();
     wlt.Name='Public Housing';
     wlt.YARDI_HMY__c=Decimal.valueof('12345');
     wlt.RADFamily__c=1;
     insert wlt;
     
     Enrolled_Wait_List__c ew=new Enrolled_Wait_List__c();
     ew.Current_Status__c='Onlist'; 
     ew.Wait_List_Type__c=wlt.id;
     ew.Prefernce_Point__c=Decimal.valueof('3'); 
     ew.Applications__c=app.id;   
     ew.Lottery__c=56712;
     insert ew;   
        
        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        wls.Wait_List_Type__c = wlt.id;
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c = 3;
        wls.Bedroom_Size__c=3;     
        insert wls;
      List<Selection_Records__c> listsel=new    List<Selection_Records__c>(); 
        
Test.startTest();
 ApexPages.StandardController sc = new ApexPages.StandardController(wls);
RAD_PubHsgPrintLbl rf = new RAD_PubHsgPrintLbl(sc);
Test.StopTest();
System.assertEquals(wls.Bedroom_Size__c,3);
listsel=rf.getSelList(); 



}
}