src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <label>Date Of Birth</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Update Required</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>On List</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Black__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Black</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible Citizen</fullName>
                </value>
                <value>
                    <fullName>Eligible Non - Citizen</fullName>
                </value>
                <value>
                    <fullName>Ineligible Non-Citizen</fullName>
                </value>
                <value>
                    <fullName>Pending Verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dependents_Children_under_age_of_18__c</fullName>
        <label>Dependents/Children under age of 18</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Not Hispanic or Latino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Annual_Income__c</fullName>
        <label>Family Annual Income</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Family</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Homeless_with_disability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Homeless with disability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Live_Work_in_City_of_San_Diego__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Applicant lives or works within the City of San Diego</description>
        <label>Live/Work in City of San Diego</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_Elderly_Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Elderly Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PBVS_Project_Based_Single__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PBS-Project Based Single</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PBV_Project_Based__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PBV-Project Based</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Public_Housing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Public Housing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RAD_Next_Purge_Date__c</fullName>
        <description>This is informational field, which will store the end date of Grace Period.</description>
        <label>Grace Period End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RAD_Next_Purge_Request_Date__c</fullName>
        <label>Next Update Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Section_8__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section 8</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Veteran_Family_of__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Applicant is from a veteran / active military or family of veterans</description>
        <label>Veteran / Active Military</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>White__c</fullName>
        <defaultValue>false</defaultValue>
        <label>White</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_people_in_the_H_H_Adults__c</fullName>
        <label># of people in the H/H - Adults</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checkbox_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Community Global User</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Housing Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Inspector</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>On-Site Manager</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Property Manager</fullName>
                </value>
                <value>
                    <fullName>Rehab HC Specialist</fullName>
                </value>
                <value>
                    <fullName>Resident Manager</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First - Housing Our Heroes</fullName>
                </value>
                <value>
                    <fullName>Landlord/Owner</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Community Member</fullName>
                </value>
                <value>
                    <fullName>Housing Specialist</fullName>
                </value>
                <value>
                    <fullName>Section 3 Resident</fullName>
                </value>
                <value>
                    <fullName>Primary Business Contact</fullName>
                </value>
                <value>
                    <fullName>Business Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Business Admin Contact</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Payroll Contact</fullName>
                </value>
                <value>
                    <fullName>Co-Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First Client_FY18</fullName>
                </value>
                <value>
                    <fullName>Housing First Client - FY17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Do_not_Have__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do not Have</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Residential_City__c</fullName>
        <label>Residential City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_State__c</fullName>
        <label>Residential State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_Street__c</fullName>
        <label>Residential Street</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_Zipcode__c</fullName>
        <label>Residential Zipcode</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>Rental Assistance Wait List Portal Record Type</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Memo__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Memos</relationshipLabel>
        <relationshipName>Memos_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Memos</label>
    <nameField>
        <label>Memo Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/classes/RAD_testMemoTriggerHandler.cls
@isTest
public class RAD_testMemoTriggerHandler {

    
    public static testmethod void testCreateMemo1(){
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;

        TestSuiteHelper.setupCustomSettings();  
        Account A1 = TestSuiteHelper.setupTestAccount();
        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();

        List<Contact> ctLst = new List<Contact>();
           Contact  ct = new Contact();
            ct.FirstName = 'firstname';
            ct.LastName = 'lName';
            ct.email = 'test@cgi.com';
            ct.accountId = A1.id;
            ct.Contact_Type__c  = 'Community Global User';
            ct.Do_not_Have__c  = true;
            ct.Date_of_Birth__c  = Date.Today().addMonths(-400);
            ct.Gender__c = 'Female';
            
            ct.Residential_Street__c=  'Residency Street'; 
            ct.Residential_City__c = 'San Diego';
            ct.Residential_State__c = 'CA';
            ct.Residential_Zipcode__c ='71117';
            
            ct.MailingStreet = 'EastMail Street'; 
            ct.MailingCity = 'San Diego';
            ct.MailingState = 'CA';
            ct.MailingPostalCode ='71119';
        ct.RecordTypeId = idd;
    ct.Active__c='Yes';
    ctLst.add(ct);
    
    Contact ct1 = new Contact();
            ct1.FirstName = 'firstname';
            ct1.LastName = 'lName';
            //ct1.email = 'test@cgi.com';
            ct1.accountId = A1.id;
            ct1.Contact_Type__c  = 'Community Global User';
            ct1.Do_not_Have__c  = true;
            ct1.Date_of_Birth__c  = Date.Today().addMonths(-400);
            ct1.Gender__c = 'Female';
            
            ct1.Residential_Street__c=  'Residency Street'; 
            ct1.Residential_City__c = 'San Diego';
            ct1.Residential_State__c = 'CA';
            ct1.Residential_Zipcode__c ='71117';
            
            ct1.MailingStreet = 'EastMail Street'; 
            ct1.MailingCity = 'San Diego';
            ct1.MailingState = 'CA';
            ct1.MailingPostalCode ='71119';
        ct1.RecordTypeId = idd;
    ct1.Active__c='Yes';
    ctLst.add(ct1);
            insert ctLst;

           
            




List<Applications__c> applist=new List<Applications__c>();
 Applications__c app1 = new Applications__c(); 
            app1.Applicant__c = ct.id;
            app1.Ethnicity__c = 'Hispanic or Latino';
            //app1.Section_8__c =true;
            //app1.PBVS_Project_Based_Single__c = true;
            //app1.PBV_Project_Based__c =true;
            app1.Public_Housing__c = true;
            app1.Application_Status__c = 'Update Required';
            app1.of_people_in_the_H_H_Adults__c = 1;
            app1.Dependents_Children_under_age_of_18__c = 1;
            app1.Family_Annual_Income__c = Decimal.valueOf('1000');
            app1.White__c =  true;
            app1.Black__c = true;
            app1.Citizenship__c = 'Eligible Citizen';
            app1.RAD_Next_Purge_Request_Date__c=Date.today();
            app1.Family__c=true;
            app1.Homeless_with_disability__c=true;
            app1.Live_Work_in_City_of_San_Diego__c=true;
            app1.Non_Elderly_Disabled__c=true;
            app1.Veteran_Family_of__c=true;
             
            app1.RAD_Next_Purge_Request_Date__c=Datetime.Now().addMonths(-1);
            
            appList.add(app1);
           
           
           app1 = new Applications__c(); 
            app1.Applicant__c = ct1.id;
            app1.Ethnicity__c = 'Hispanic or Latino';
            //app1.Section_8__c =true;
            //app1.PBVS_Project_Based_Single__c = true;
            //app1.PBV_Project_Based__c =true;
            app1.Public_Housing__c = true;
            app1.Application_Status__c = 'Update Required';
            app1.of_people_in_the_H_H_Adults__c = 1;
            app1.Dependents_Children_under_age_of_18__c = 1;
            app1.Family_Annual_Income__c = Decimal.valueOf('1000');
            app1.White__c =  true;
            app1.Black__c = true;
            app1.Citizenship__c = 'Eligible Citizen';
            app1.RAD_Next_Purge_Request_Date__c=Date.today();
            app1.Family__c=true;
            app1.Homeless_with_disability__c=true;
            app1.Live_Work_in_City_of_San_Diego__c=true;
            app1.Non_Elderly_Disabled__c=true;
            app1.Veteran_Family_of__c=true;
             
           
            applist.add(app1);
           
           
            insert  appList;
                        
            
            for(Applications__c app: appList){            
                app.RAD_Next_Purge_Request_Date__c=Datetime.Now().addDays(-3);
                app.RAD_Next_Purge_Date__c = Datetime.now().addDays(10);

            }
            update appList;

		Test.startTest();
        
        RAD_DailyBatchToPurge.createMemo(appList[0], 'BounceUpdate');
        appList = [select id, (SELECT id, Name FROM Memos_Records__r) FROM Applications__c WHERE id = :appList[0].id];
        for(Memo__c a:appList[0].Memos_Records__r){
        	System.assertEquals(a.Name, 'Email bounce from Purge Update');
            }
        Test.stopTest();
    }
    public static testmethod void testCreateMemo2(){
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;

        TestSuiteHelper.setupCustomSettings();  
        Account A1 = TestSuiteHelper.setupTestAccount();
        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();

        List<Contact> ctLst = new List<Contact>();
           Contact  ct = new Contact();
            ct.FirstName = 'firstname';
            ct.LastName = 'lName';
            ct.email = 'test@cgi.com';
            ct.accountId = A1.id;
            ct.Contact_Type__c  = 'Community Global User';
            ct.Do_not_Have__c  = true;
            ct.Date_of_Birth__c  = Date.Today().addMonths(-400);
            ct.Gender__c = 'Female';
            
            ct.Residential_Street__c=  'Residency Street'; 
            ct.Residential_City__c = 'San Diego';
            ct.Residential_State__c = 'CA';
            ct.Residential_Zipcode__c ='71117';
            
            ct.MailingStreet = 'EastMail Street'; 
            ct.MailingCity = 'San Diego';
            ct.MailingState = 'CA';
            ct.MailingPostalCode ='71119';
        ct.RecordTypeId = idd;
    ct.Active__c='Yes';
    ctLst.add(ct);
    
    Contact ct1 = new Contact();
            ct1.FirstName = 'firstname';
            ct1.LastName = 'lName';
            //ct1.email = 'test@cgi.com';
            ct1.accountId = A1.id;
            ct1.Contact_Type__c  = 'Community Global User';
            ct1.Do_not_Have__c  = true;
            ct1.Date_of_Birth__c  = Date.Today().addMonths(-400);
            ct1.Gender__c = 'Female';
            
            ct1.Residential_Street__c=  'Residency Street'; 
            ct1.Residential_City__c = 'San Diego';
            ct1.Residential_State__c = 'CA';
            ct1.Residential_Zipcode__c ='71117';
            
            ct1.MailingStreet = 'EastMail Street'; 
            ct1.MailingCity = 'San Diego';
            ct1.MailingState = 'CA';
            ct1.MailingPostalCode ='71119';
        ct1.RecordTypeId = idd;
    ct1.Active__c='Yes';
    ctLst.add(ct1);
            insert ctLst;

           
            




List<Applications__c> applist=new List<Applications__c>();
 Applications__c app1 = new Applications__c(); 
            app1.Applicant__c = ct.id;
            app1.Ethnicity__c = 'Hispanic or Latino';
            //app1.Section_8__c =true;
            //app1.PBVS_Project_Based_Single__c = true;
            //app1.PBV_Project_Based__c =true;
            app1.Public_Housing__c = true;
            app1.Application_Status__c = 'Update Required';
            app1.of_people_in_the_H_H_Adults__c = 1;
            app1.Dependents_Children_under_age_of_18__c = 1;
            app1.Family_Annual_Income__c = Decimal.valueOf('1000');
            app1.White__c =  true;
            app1.Black__c = true;
            app1.Citizenship__c = 'Eligible Citizen';
            app1.RAD_Next_Purge_Request_Date__c=Date.today();
            app1.Family__c=true;
            app1.Homeless_with_disability__c=true;
            app1.Live_Work_in_City_of_San_Diego__c=true;
            app1.Non_Elderly_Disabled__c=true;
            app1.Veteran_Family_of__c=true;
             
            app1.RAD_Next_Purge_Request_Date__c=Datetime.Now().addMonths(-1);
            
            appList.add(app1);
           
           
           app1 = new Applications__c(); 
            app1.Applicant__c = ct1.id;
            app1.Ethnicity__c = 'Hispanic or Latino';
            //app1.Section_8__c =true;
            //app1.PBVS_Project_Based_Single__c = true;
            //app1.PBV_Project_Based__c =true;
            app1.Public_Housing__c = true;
            app1.Application_Status__c = 'Update Required';
            app1.of_people_in_the_H_H_Adults__c = 1;
            app1.Dependents_Children_under_age_of_18__c = 1;
            app1.Family_Annual_Income__c = Decimal.valueOf('1000');
            app1.White__c =  true;
            app1.Black__c = true;
            app1.Citizenship__c = 'Eligible Citizen';
            app1.RAD_Next_Purge_Request_Date__c=Date.today();
            app1.Family__c=true;
            app1.Homeless_with_disability__c=true;
            app1.Live_Work_in_City_of_San_Diego__c=true;
            app1.Non_Elderly_Disabled__c=true;
            app1.Veteran_Family_of__c=true;
             
           
            applist.add(app1);
           
           
            insert  appList;
                        
            
            for(Applications__c app: appList){            
                app.RAD_Next_Purge_Request_Date__c=Datetime.Now().addDays(-3);
                app.RAD_Next_Purge_Date__c = Datetime.now().addDays(10);

            }
            update appList;


		Test.startTest();
        RAD_DailyBatchToPurge.createMemo(appList[0], 'PurgeUpdateEmail');
        appList = [select id, (SELECT id, Name FROM Memos_Records__r) FROM Applications__c WHERE id = :appList[0].id];
        for(Memo__c a:appList[0].Memos_Records__r){
        	System.assertEquals(a.Name, 'Email failure from Purge Update');
            }
        Test.stopTest();
    }
    public static testmethod void testCreateMemo3(){
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;

        TestSuiteHelper.setupCustomSettings();  
        Account A1 = TestSuiteHelper.setupTestAccount();
        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();

        List<Contact> ctLst = new List<Contact>();
           Contact  ct = new Contact();
            ct.FirstName = 'firstname';
            ct.LastName = 'lName';
            ct.email = 'test@cgi.com';
            ct.accountId = A1.id;
            ct.Contact_Type__c  = 'Community Global User';
            ct.Do_not_Have__c  = true;
            ct.Date_of_Birth__c  = Date.Today().addMonths(-400);
            ct.Gender__c = 'Female';
            
            ct.Residential_Street__c=  'Residency Street'; 
            ct.Residential_City__c = 'San Diego';
            ct.Residential_State__c = 'CA';
            ct.Residential_Zipcode__c ='71117';
            
            ct.MailingStreet = 'EastMail Street'; 
            ct.MailingCity = 'San Diego';
            ct.MailingState = 'CA';
            ct.MailingPostalCode ='71119';
        ct.RecordTypeId = idd;
    ct.Active__c='Yes';
    ctLst.add(ct);
    
    Contact ct1 = new Contact();
            ct1.FirstName = 'firstname';
            ct1.LastName = 'lName';
            //ct1.email = 'test@cgi.com';
            ct1.accountId = A1.id;
            ct1.Contact_Type__c  = 'Community Global User';
            ct1.Do_not_Have__c  = true;
            ct1.Date_of_Birth__c  = Date.Today().addMonths(-400);
            ct1.Gender__c = 'Female';
            
            ct1.Residential_Street__c=  'Residency Street'; 
            ct1.Residential_City__c = 'San Diego';
            ct1.Residential_State__c = 'CA';
            ct1.Residential_Zipcode__c ='71117';
            
            ct1.MailingStreet = 'EastMail Street'; 
            ct1.MailingCity = 'San Diego';
            ct1.MailingState = 'CA';
            ct1.MailingPostalCode ='71119';
        ct1.RecordTypeId = idd;
    ct1.Active__c='Yes';
    ctLst.add(ct1);
            insert ctLst;

           
            




List<Applications__c> applist=new List<Applications__c>();
 Applications__c app1 = new Applications__c(); 
            app1.Applicant__c = ct.id;
            app1.Ethnicity__c = 'Hispanic or Latino';
            //app1.Section_8__c =true;
            //app1.PBVS_Project_Based_Single__c = true;
            //app1.PBV_Project_Based__c =true;
            app1.Public_Housing__c = true;
            app1.Application_Status__c = 'Update Required';
            app1.of_people_in_the_H_H_Adults__c = 1;
            app1.Dependents_Children_under_age_of_18__c = 1;
            app1.Family_Annual_Income__c = Decimal.valueOf('1000');
            app1.White__c =  true;
            app1.Black__c = true;
            app1.Citizenship__c = 'Eligible Citizen';
            app1.RAD_Next_Purge_Request_Date__c=Date.today();
            app1.Family__c=true;
            app1.Homeless_with_disability__c=true;
            app1.Live_Work_in_City_of_San_Diego__c=true;
            app1.Non_Elderly_Disabled__c=true;
            app1.Veteran_Family_of__c=true;
             
            app1.RAD_Next_Purge_Request_Date__c=Datetime.Now().addMonths(-1);
            
            appList.add(app1);
           
           
           app1 = new Applications__c(); 
            app1.Applicant__c = ct1.id;
            app1.Ethnicity__c = 'Hispanic or Latino';
            //app1.Section_8__c =true;
            //app1.PBVS_Project_Based_Single__c = true;
            //app1.PBV_Project_Based__c =true;
            app1.Public_Housing__c = true;
            app1.Application_Status__c = 'Update Required';
            app1.of_people_in_the_H_H_Adults__c = 1;
            app1.Dependents_Children_under_age_of_18__c = 1;
            app1.Family_Annual_Income__c = Decimal.valueOf('1000');
            app1.White__c =  true;
            app1.Black__c = true;
            app1.Citizenship__c = 'Eligible Citizen';
            app1.RAD_Next_Purge_Request_Date__c=Date.today();
            app1.Family__c=true;
            app1.Homeless_with_disability__c=true;
            app1.Live_Work_in_City_of_San_Diego__c=true;
            app1.Non_Elderly_Disabled__c=true;
            app1.Veteran_Family_of__c=true;
             
           
            applist.add(app1);
           
           
            insert  appList;
                        
            
            for(Applications__c app: appList){            
                app.RAD_Next_Purge_Request_Date__c=Datetime.Now().addDays(-3);
                app.RAD_Next_Purge_Date__c = Datetime.now().addDays(10);

            }
            update appList;


		Test.startTest();
        RAD_DailyBatchToPurge.createMemo(appList[0], 'PurgeReminderEmail');
        appList = [select id, (SELECT id, Name FROM Memos_Records__r) FROM Applications__c WHERE id = :appList[0].id];
        for(Memo__c a:appList[0].Memos_Records__r){
        	System.assertEquals(a.Name, 'Email failure from Purge Reminder');
            }
        Test.stopTest();
    } 
    public static testmethod void testCreateMemo4(){
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;

        TestSuiteHelper.setupCustomSettings();  
        Account A1 = TestSuiteHelper.setupTestAccount();
        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();

        List<Contact> ctLst = new List<Contact>();
           Contact  ct = new Contact();
            ct.FirstName = 'firstname';
            ct.LastName = 'lName';
            ct.email = 'test@cgi.com';
            ct.accountId = A1.id;
            ct.Contact_Type__c  = 'Community Global User';
            ct.Do_not_Have__c  = true;
            ct.Date_of_Birth__c  = Date.Today().addMonths(-400);
            ct.Gender__c = 'Female';
            
            ct.Residential_Street__c=  'Residency Street'; 
            ct.Residential_City__c = 'San Diego';
            ct.Residential_State__c = 'CA';
            ct.Residential_Zipcode__c ='71117';
            
            ct.MailingStreet = 'EastMail Street'; 
            ct.MailingCity = 'San Diego';
            ct.MailingState = 'CA';
            ct.MailingPostalCode ='71119';
        ct.RecordTypeId = idd;
    ct.Active__c='Yes';
    ctLst.add(ct);
    
    Contact ct1 = new Contact();
            ct1.FirstName = 'firstname';
            ct1.LastName = 'lName';
            //ct1.email = 'test@cgi.com';
            ct1.accountId = A1.id;
            ct1.Contact_Type__c  = 'Community Global User';
            ct1.Do_not_Have__c  = true;
            ct1.Date_of_Birth__c  = Date.Today().addMonths(-400);
            ct1.Gender__c = 'Female';
            
            ct1.Residential_Street__c=  'Residency Street'; 
            ct1.Residential_City__c = 'San Diego';
            ct1.Residential_State__c = 'CA';
            ct1.Residential_Zipcode__c ='71117';
            
            ct1.MailingStreet = 'EastMail Street'; 
            ct1.MailingCity = 'San Diego';
            ct1.MailingState = 'CA';
            ct1.MailingPostalCode ='71119';
        ct1.RecordTypeId = idd;
    ct1.Active__c='Yes';
    ctLst.add(ct1);
            insert ctLst;

           
            




List<Applications__c> applist=new List<Applications__c>();
 Applications__c app1 = new Applications__c(); 
            app1.Applicant__c = ct.id;
            app1.Ethnicity__c = 'Hispanic or Latino';
            //app1.Section_8__c =true;
            //app1.PBVS_Project_Based_Single__c = true;
            //app1.PBV_Project_Based__c =true;
            app1.Public_Housing__c = true;
            app1.Application_Status__c = 'Update Required';
            app1.of_people_in_the_H_H_Adults__c = 1;
            app1.Dependents_Children_under_age_of_18__c = 1;
            app1.Family_Annual_Income__c = Decimal.valueOf('1000');
            app1.White__c =  true;
            app1.Black__c = true;
            app1.Citizenship__c = 'Eligible Citizen';
            app1.RAD_Next_Purge_Request_Date__c=Date.today();
            app1.Family__c=true;
            app1.Homeless_with_disability__c=true;
            app1.Live_Work_in_City_of_San_Diego__c=true;
            app1.Non_Elderly_Disabled__c=true;
            app1.Veteran_Family_of__c=true;
             
            app1.RAD_Next_Purge_Request_Date__c=Datetime.Now().addMonths(-1);
            
            appList.add(app1);
           
           
           app1 = new Applications__c(); 
            app1.Applicant__c = ct1.id;
            app1.Ethnicity__c = 'Hispanic or Latino';
            //app1.Section_8__c =true;
            //app1.PBVS_Project_Based_Single__c = true;
            //app1.PBV_Project_Based__c =true;
            app1.Public_Housing__c = true;
            app1.Application_Status__c = 'Update Required';
            app1.of_people_in_the_H_H_Adults__c = 1;
            app1.Dependents_Children_under_age_of_18__c = 1;
            app1.Family_Annual_Income__c = Decimal.valueOf('1000');
            app1.White__c =  true;
            app1.Black__c = true;
            app1.Citizenship__c = 'Eligible Citizen';
            app1.RAD_Next_Purge_Request_Date__c=Date.today();
            app1.Family__c=true;
            app1.Homeless_with_disability__c=true;
            app1.Live_Work_in_City_of_San_Diego__c=true;
            app1.Non_Elderly_Disabled__c=true;
            app1.Veteran_Family_of__c=true;
             
           
            applist.add(app1);
           
           
            insert  appList;
                        
            
            for(Applications__c app: appList){            
                app.RAD_Next_Purge_Request_Date__c=Datetime.Now().addDays(-3);
                app.RAD_Next_Purge_Date__c = Datetime.now().addDays(10);

            }
            update appList;

		Test.startTest();
        RAD_DailyBatchToPurge.createMemo(appList[0], 'BounceReminder');
        appList = [select id, (SELECT id, Name FROM Memos_Records__r) FROM Applications__c WHERE id = :appList[0].id];
        for(Memo__c a:appList[0].Memos_Records__r){
        	System.assertEquals(a.Name, 'Email bounce from Purge Reminder');
            }
        Test.stopTest();
    }    
}