src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <label>Date Of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Not Hispanic or Latino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Family</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>Spouse First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Spouse Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PBVS_Project_Based_Single__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PBS-Project Based Single</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section_8__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section 8</label>
        <type>Checkbox</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checkbox_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Community Global User</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Housing Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Inspector</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>On-Site Manager</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Property Manager</fullName>
                </value>
                <value>
                    <fullName>Rehab HC Specialist</fullName>
                </value>
                <value>
                    <fullName>Resident Manager</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First - Housing Our Heroes</fullName>
                </value>
                <value>
                    <fullName>Landlord/Owner</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Community Member</fullName>
                </value>
                <value>
                    <fullName>Housing Specialist</fullName>
                </value>
                <value>
                    <fullName>Section 3 Resident</fullName>
                </value>
                <value>
                    <fullName>Primary Business Contact</fullName>
                </value>
                <value>
                    <fullName>Business Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Business Admin Contact</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Payroll Contact</fullName>
                </value>
                <value>
                    <fullName>Co-Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First Client_FY18</fullName>
                </value>
                <value>
                    <fullName>Housing First Client - FY17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Do_not_Have__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do not Have</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Residential_City__c</fullName>
        <label>Residential City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_State__c</fullName>
        <label>Residential State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_Street__c</fullName>
        <label>Residential Street</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_Zipcode__c</fullName>
        <label>Residential Zipcode</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>Rental Assistance Wait List Portal Record Type</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RAD_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Portal_Contact_Address__c</fullName>
        <label>Portal Contact Address</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Portal_Forgot_Password_Note__c</fullName>
        <label>Portal Forgot Password Note</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Portal_Forgot_UserName_Note__c</fullName>
        <label>Portal Forgot UserName Note</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Purge_Extension_Months__c</fullName>
        <description>Purge Extension in months</description>
        <label>Purge Extension(Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update_Duration_Months__c</fullName>
        <label>Update Duration (Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RAD Configuration</label>
    <nameField>
        <label>RAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Wait_List_Income_Limit__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percent_Income_Limit__c</fullName>
        <label>Percent Income Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Wait List Income Limit</label>
    <nameField>
        <label>HMY</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Income Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Wait_List_Income_Limit_Details__c.object
<CustomObject>
    <fields>
        <fullName>Income_Limit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Income Limit</label>
        <referenceTo>Wait_List_Income_Limit__c</referenceTo>
        <relationshipLabel>Wait List Income Limit Details</relationshipLabel>
        <relationshipName>Wait_List_Income_Limit_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Limit_1__c</fullName>
        <label>Limit 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_2__c</fullName>
        <label>Limit 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_3__c</fullName>
        <label>Limit 3</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_4__c</fullName>
        <label>Limit 4</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_Effective_Date__c</fullName>
        <label>Limit Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Limit_Expiration_Date__c</fullName>
        <label>Limit Expiration Date</label>
        <type>Date</type>
    </fields>
    <label>Wait List Income Limit Details</label>
    <nameField>
        <label>HMY</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Income Limit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Up__c</fullName>
        <defaultValue>&apos;50&apos;</defaultValue>
        <label>% Lease Up</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RADDisabled_Family__c</fullName>
        <label>Disabled</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADFamily__c</fullName>
        <label>Family</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADHomeless_with_disability__c</fullName>
        <label>Homeless with disability</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADLive_Work_in_City_of_San_Diego__c</fullName>
        <label>Live/Work in City of San Diego</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADNon_Elderly_Disabled__c</fullName>
        <label>Elderly</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADVeteran_Active_Military__c</fullName>
        <label>Veteran / Active Military</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YARDI_HMY__c</fullName>
        <externalId>true</externalId>
        <label>YARDI ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZipLocation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ZipRanges__c</fullName>
        <label>ZipRanges</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ZipLocation</label>
</CustomObject>

src/classes/TestSuiteHelper.cls
public class TestSuiteHelper {
    public static RAD_Configuration__c confg;
    public static Contact[] testContacts;
    public static Account[] testAccounts;
    public static Account testAccount;
    public static Applications__c[] testApplns;
//    public static customsetting cSetting;
    public static Wait_List_Type__c[] wlts;
    public static Wait_List_Income_Limit__c[]  wlIncLmts;
    public static Wait_List_Income_Limit_Details__c[] wlIncLmtDtl ;


    public static Account setupTestAccount(){
        testAccounts = [Select id, name From Account  Where name = 'RAD Community Account' ];
        if( testAccounts.isEmpty() ){
            Id idd = Schema.SObjectType.Account.getRecordTypeInfosByName().get('RAD Community Account').getRecordTypeId();
            testAccount = new Account(Name = 'RAD Community Account', First_Name__c = 'TestName',Last_Name__c ='LastName', RecordTypeId = idd );
            insert testAccount;
        }else{
            testAccount =testAccounts[0];
        }
        
        return testAccount;
    }
    
    public static void setupCustomSettings(){
        
        
        try{
            confg = [Select Update_Duration_Months__c, RAD_Purge_Extension_Months__c, RAD_Portal_Forgot_Password_Note__c, 
                RAD_Portal_Forgot_UserName_Note__c, RAD_Portal_Contact_Address__c, Announcement__c
                from RAD_Configuration__c where name = 'Main Configurations'];
        }catch(Exception e){
            confg = new RAD_Configuration__c(Name = 'Main Configurations', Update_Duration_Months__c = 6, RAD_Purge_Extension_Months__c =1,
                RAD_Portal_Forgot_Password_Note__c ='This is Forgotten Password Note', RAD_Portal_Forgot_UserName_Note__c ='This is Forgotten Username Note',
                RAD_Portal_Contact_Address__c = 'This is Portal Contact Address', Announcement__c = 'This is Announcement');

            insert confg; 
        }
        
        ZipLocation__c zLocSetting = null;
        if(ZipLocation__c.getInstance('San Diego')==null)
        {
          zLocSetting = new ZipLocation__c(Name='San Diego',ZipRanges__c='92101,92102,92103,92104');
          insert zLocSetting ;
        }
            
        wlts =  new Wait_List_Type__c[]{
        new Wait_List_Type__c( Name = 'Section 8', Lease_Up__c = '50', RADDisabled_Family__c = 1, RADFamily__c = 2, RADHomeless_with_disability__c = 3,
        RADNon_Elderly_Disabled__c = 4, RADLive_Work_in_City_of_San_Diego__c = 5, RADVeteran_Active_Military__c = 6, YARDI_HMY__c = 5),
        new Wait_List_Type__c( Name = 'Project Based', Lease_Up__c = '50', RADDisabled_Family__c = 10, RADFamily__c = 11, RADHomeless_with_disability__c = 13,
        RADNon_Elderly_Disabled__c = 14, RADLive_Work_in_City_of_San_Diego__c = 15, RADVeteran_Active_Military__c = 16, YARDI_HMY__c = 3),
        new Wait_List_Type__c( Name = 'Project Based Single', Lease_Up__c = '50', RADDisabled_Family__c = 20, RADFamily__c = 21, RADHomeless_with_disability__c = 23,
        RADNon_Elderly_Disabled__c = 24, RADLive_Work_in_City_of_San_Diego__c = 25, RADVeteran_Active_Military__c = 26, YARDI_HMY__c = 4),
        new Wait_List_Type__c( Name = 'Mod Rehab', Lease_Up__c = '50', RADDisabled_Family__c = 30, RADFamily__c = 31, RADHomeless_with_disability__c = 33,
        RADNon_Elderly_Disabled__c = 34, RADLive_Work_in_City_of_San_Diego__c = 35, RADVeteran_Active_Military__c = 36, YARDI_HMY__c = 1),
        new Wait_List_Type__c( Name = 'Public Housing', Lease_Up__c = '50', RADDisabled_Family__c = 30, RADFamily__c = 31, RADHomeless_with_disability__c = 33,
        RADNon_Elderly_Disabled__c = 34, RADLive_Work_in_City_of_San_Diego__c = 35, RADVeteran_Active_Military__c = 36, YARDI_HMY__c = 2),
        new Wait_List_Type__c( Name = 'NED', Lease_Up__c = '50', RADDisabled_Family__c = 30, RADFamily__c = 31, RADHomeless_with_disability__c = 33,
        RADNon_Elderly_Disabled__c = 34, RADLive_Work_in_City_of_San_Diego__c = 35, RADVeteran_Active_Military__c = 36, YARDI_HMY__c = 13456)
        };
        insert wlts;
        
        wlIncLmts = new Wait_List_Income_Limit__c[]{
            new Wait_List_Income_Limit__c(Name = '1',Code__c = 'eli-30', Percent_Income_Limit__c = 30),
            new Wait_List_Income_Limit__c(Name = '2',Code__c = 'vli-50', Percent_Income_Limit__c = 50),
            new Wait_List_Income_Limit__c(Name = '3',Code__c = 'li-80', Percent_Income_Limit__c = 80)
        };               
        insert wlIncLmts; 
        
        wlIncLmtDtl = new Wait_List_Income_Limit_Details__c[]{
            new Wait_List_Income_Limit_Details__c(Name = '1', Limit_Effective_Date__c = Date.Today()-5, Limit_Expiration_Date__c = Date.Today()+5,
                         Income_Limit__c = wlIncLmts[0].id, Limit_1__c = '10000', Limit_2__c = '20000', Limit_3__c = '23000',Limit_4__c = '25000' ),
            new Wait_List_Income_Limit_Details__c(Name = '2', Limit_Effective_Date__c = Date.Today()-5, Limit_Expiration_Date__c = Date.Today()+5,
                         Income_Limit__c = wlIncLmts[1].id, Limit_1__c = '31850', Limit_2__c = '36400', Limit_3__c = '40950',Limit_4__c = '45450' ),
            new Wait_List_Income_Limit_Details__c(Name = '3', Limit_Effective_Date__c = Date.Today()-5, Limit_Expiration_Date__c = Date.Today()+5,
                         Income_Limit__c = wlIncLmts[2].id, Limit_1__c = '50950', Limit_2__c = '58200', Limit_3__c = '65500',Limit_4__c = '72750' )                                                
        };
        
        insert wlIncLmtDtl ;
        
        //add inc limit
    
    }
    

    public static List<Contact> setupPortalRequiredData() {  
       // TestSuiteHelper.setupCustomSettings();
        TestSuiteHelper.setupTestAccount();
        testApplns = new List<Applications__c>();
        testContacts = new List<Contact>();
        
        
        
        testContacts.addAll(createPortalSDContacts(4, 'SDeli0ne', 'T1', true));
        testApplns.addAll(createAppln(4,'SDeli0ne' ,10000, 1 ) );
        
        testContacts.addAll(createPortalSDContacts(1, 'SDelithree', 'T2', true));
        testApplns.addAll(createAppln(1,'SDelithree' ,10000, 3 ) );
        
        testContacts.addAll(createPortalSDContacts(3, 'SDVlione', 'T3', true));
        testApplns.addAll(createAppln(3,'SDVlione' ,30000, 1 ) );

        testContacts.addAll(createPortalSDContacts(2, 'SDLione', 'T4', true));
        testApplns.addAll(createAppln(2,'SDLione' ,40000, 1 ) );
        
        
        
  /*
        testContacts.addAll(createNonSDContacts(10, 'NSDWithEmail', 'T2', true));
        testApplns.addAll(createAppln(4,'NSDWithEmail' ,10000, 1 ) );
        testApplns.addAll(createAppln(1,'NSDWithEmail' ,10000, 3 ) );        
        testApplns.addAll(createAppln(3,'NSDWithEmail' ,30000, 1 ) );
        testApplns.addAll(createAppln(2,'NSDWithEmail' ,40000, 1 ) );
        
        */
        //Database.insert(testContacts, false);
        //Database.insert(testApplns, false);//only insert applns
        
        //insert testContacts;
        try{
            insert testApplns;
            }catch(Exception ee){
                System.debug('founnd exception '+ee.getMessage());
            }
        
        
        return testContacts;
        
    }
    
    public static List<Contact> createSDContacts(Integer cnt, String lName, String uniqIdx, Boolean withEmail) {  
        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        List<Contact> ctLst = new List<Contact>();
        Contact ct = new Contact();
        for(Integer i=1;i<=cnt;i++){
            ct = new Contact();
            ct.FirstName = 'SD'+i;
            ct.LastName = lName;
            if(withEmail ==  true){
                ct.email = lName + uniqIdx + i+'@testpqr.com';
            }
            ct.accountId = testAccount.id;
            ct.Contact_Type__c  = 'Community Global User';
            ct.Do_not_Have__c  = true;
            ct.Date_of_Birth__c  = Date.Today().addMonths(-400);
            ct.Gender__c = 'Female';
            
            ct.Residential_Street__c= i + 'Residency Street'; 
            ct.Residential_City__c = 'San Diego';
            ct.Residential_State__c = 'CA';
            ct.Residential_Zipcode__c ='92101';
            
            ct.MailingStreet = i + 'EastMail Street'; 
            ct.MailingCity = 'San Diego';
            ct.MailingState = 'CA';
            ct.MailingPostalCode ='92101';
            
            ct.Active__c = 'Yes';
            ct.RecordTypeId = idd;
                        
            ctLst.add(ct);
        }
        return ctLst;        
    }
    
  
    public static List<Contact> createPortalSDContacts(Integer cnt, String lName, String uniqIdx, Boolean withEmail) {  
        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        List<Contact> ctLst = new List<Contact>();
        Contact ct = new Contact();
        for(Integer i=1;i<=cnt;i++){
            ct = new Contact();
            ct.FirstName = 'SD'+i;
            ct.LastName = lName;
            ct.email = lName + uniqIdx + i+'@testpqr.com';
            ct.accountId = testAccount.id;
            ct.Contact_Type__c  = 'Community Global User';
            ct.Do_not_Have__c  = true;
            ct.Date_of_Birth__c  = Date.Today().addMonths(-400);
            ct.Gender__c = 'Female';
            
            ct.Residential_Street__c= i + 'Residency Street'; 
            ct.Residential_City__c = 'San Diego';
            ct.Residential_State__c = 'CA';
            ct.Residential_Zipcode__c ='92101';
            
            ct.MailingStreet = i + 'EastMail Street'; 
            ct.MailingCity = 'San Diego';
            ct.MailingState = 'CA';
            ct.MailingPostalCode ='92101';
            
            ct.Active__c = 'Yes';
            ct.RecordTypeId = idd;
            
            ctLst.add(ct);
        }
        
        Database.insert(ctLst, false);
        
        if(withEmail ==  false ){
            for(Contact ctt : ctLst){
                ctt.Email = '';
            }
            
            Database.update(ctLst, false);//chkk
        
        }
        
        Profile p = [select id from profile where name='RAD_Community_Profile']; 
        List<User> lstUser = new List<User>();
        User u = new User();

      
        Integer i =1;
        for(Contact ctt : ctLst){
            u = new User();
            u.FirstName = 'SD'+i;
            u.LastName = lName;
            u.username = ctt.Email;
            u.ProfileId  = p.id;
            u.CommunityNickname = 'tcwo' + String.ValueOf(cnt);
            U.alias = 'r'+String.ValueOf(cnt);
            u.Email = ctt.Email;
            u.TIMEZONESIDKEY = 'America/Los_Angeles';
            u.contactId = ctt.id;
            u.emailencodingkey='UTF-8';
            u.languagelocalekey='en_US';
            
            u.localesidkey='en_US';
            
            i++;
            lstUser.add(u);
        }
        
        
        
        Database.insert(lstUser, false);
        
        return ctLst;
        
    }
    
    
    public static List<Contact> createNonSDContacts(Integer cnt, String lName, String uniqIdx, Boolean withEmail) {  

        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        List<Contact> ctLst = new List<Contact>();
        Contact ct = new Contact();
        for(Integer i=1;i<=cnt;i++){
            ct = new Contact();
            ct.FirstName = 'NSD'+i;
            ct.LastName = lName;
            ct.email = lName + uniqIdx + i+'@testpqr.com';
            ct.accountId = testAccount.id;
            ct.Contact_Type__c  = 'Community Global User';
            ct.Do_not_Have__c  = true;
            ct.Date_of_Birth__c  = Date.Today().addMonths(-400);
            ct.Gender__c = 'Female';
            
            ct.Residential_Street__c= i + 'Residency Street'; 
            ct.Residential_City__c = 'San Diego';
            ct.Residential_State__c = 'CA';
            ct.Residential_Zipcode__c ='71117';
            
            ct.MailingStreet = i + 'EastMail Street'; 
            ct.MailingCity = 'San Diego';
            ct.MailingState = 'CA';
            ct.MailingPostalCode ='71119';
            
            ct.Active__c = 'Yes';
            ct.RecordTypeId = idd;
            
            ctLst.add(ct);
        }
        
        Database.insert(ctLst, false);
        
        
        if(withEmail ==  false ){
            for(Contact ctt : ctLst){
                ctt.Email = '';
            }
            
            Database.update(ctLst, false);//chkk
        
        }
        
        Profile p = [select id from profile where name='RAD_Community_Profile']; 
        List<User> lstUser = new List<User>();
        User u = new User();


        Integer i =1;
        for(Contact ctt : ctLst){
            u = new User();
            u.FirstName = 'NonSandiego'+i;
            u.LastName = lName;
            u.username = ctt.Email;
            u.ProfileId  = p.id;
            u.CommunityNickname = 'tcwo' + String.ValueOf(cnt);
            U.alias = 'r'+String.ValueOf(cnt);
            u.Email = ctt.Email;
            u.TIMEZONESIDKEY = 'America/Los_Angeles';
            u.contactId = ctt.id;
            u.emailencodingkey='UTF-8';
            u.languagelocalekey='en_US';
            
            u.localesidkey='en_US';

            i++;
            lstUser.add(u);
        }
        
        
        
        Database.insert(lstUser, false);
        
        return ctLst;
        
    }
    
    public static List<Applications__c> createAppln(Integer cnt, String lname,Decimal annInc, Integer chldcnt ){
        List<Applications__c> appLst = new List<Applications__c>();
        Applications__c app = new Applications__c();
        
        List<Contact>ctLst = [Select  Id from Contact where lastname =: lname order by name asc ]; 
        for(Contact ct : ctLst){
            app = new Applications__c();
            app.Applicant__c = ct.id;
            app.Ethnicity__c = 'Hispanic or Latino';
            app.Section_8__c =true;
            app.PBVS_Project_Based_Single__c = true;
            app.PBV_Project_Based__c =true;
            app.Public_Housing__c = true;
            app.Application_Status__c = 'Submitted';
            app.Family_Annual_Income__c = annInc;
            app.White__c =  true;
            app.Black__c = true;
            app.Citizenship__c = 'Eligible Citizen';
            app.of_people_in_the_H_H_Adults__c = 1;
            app.Dependents_Children_under_age_of_18__c = chldcnt;
            app.Family__c = true;
            appLst.add(app);
        
        }

        return appLst;
    }
    


}