src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>American_Indian__c</fullName>
        <defaultValue>false</defaultValue>
        <label>American Indian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Update Required</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>On List</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Asian__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Black__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Black</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dependents_Children_under_age_of_18__c</fullName>
        <label>Dependents/Children under age of 18</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Not Hispanic or Latino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Annual_Income__c</fullName>
        <label>Family Annual Income</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pacific_Islander__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pacific Islander</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>White__c</fullName>
        <defaultValue>false</defaultValue>
        <label>White</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_people_in_the_H_H_Adults__c</fullName>
        <label># of people in the H/H - Adults</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checkbox_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Community Global User</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Housing Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Inspector</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>On-Site Manager</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Property Manager</fullName>
                </value>
                <value>
                    <fullName>Rehab HC Specialist</fullName>
                </value>
                <value>
                    <fullName>Resident Manager</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First - Housing Our Heroes</fullName>
                </value>
                <value>
                    <fullName>Landlord/Owner</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Community Member</fullName>
                </value>
                <value>
                    <fullName>Housing Specialist</fullName>
                </value>
                <value>
                    <fullName>Section 3 Resident</fullName>
                </value>
                <value>
                    <fullName>Primary Business Contact</fullName>
                </value>
                <value>
                    <fullName>Business Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Business Admin Contact</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Payroll Contact</fullName>
                </value>
                <value>
                    <fullName>Co-Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First Client_FY18</fullName>
                </value>
                <value>
                    <fullName>Housing First Client - FY17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_not_Have__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do not Have</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>Rental Assistance Wait List Portal Record Type</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bed_size__c</fullName>
        <label>Bed size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onlist</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issue/Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lottery__c</fullName>
        <label>Lottery</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prefernce_Point__c</fullName>
        <label>Preference Point</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On List</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issued/Offer</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Refused</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/objects/Wait_List_Selection__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait List Selections</relationshipLabel>
        <relationshipName>Wait_List_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Wait List Selection</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait List Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_PubHsgScheduler_Test.cls
@isTest
public class RAD_PubHsgScheduler_Test
{
    public static testMethod void PB_Scheduletest()
    {
    
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
            
        TestSuiteHelper.setupCustomSettings();  
        //TestSuiteHelper.setupPortalRequiredData();
        Account A1 = TestSuiteHelper.setupTestAccount();
        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        
        Contact con=new  Contact();
        //con.Name='test@cgi.com';
        con.FirstName='test';
        con.LastName='testLast';
        con.accountId = A1.id;
        con.Contact_Type__c  = 'Community Global User';
        con.Do_not_Have__c  = true;
        con.RecordTypeId = idd;
        con.Active__c='Yes';
        insert con;
        
        
        Applications__c app=new Applications__c();
        app.Applicant__c=con.id;
        app.Ethnicity__c = 'Hispanic or Latino';
        app.Family_Annual_Income__c=Decimal.valueof('1000');
        app.White__c=true;
        app.Asian__c=  true;
        app.Black__c = true;
        app.American_Indian__c=true;
        app.Pacific_Islander__c=true;
        
        app.of_people_in_the_H_H_Adults__c = 1;
        app.Dependents_Children_under_age_of_18__c = 0;
        app.Application_Status__c = 'Submitted';
        
        insert app;
        //clearing WL to work for mig and normal mode        
        List<Enrolled_Wait_List__c> wlst = [Select id from Enrolled_Wait_List__c where Applications__c =: app.id ];
        Database.delete(wlst, false);
        
        Wait_List_Type__c wltype =[Select id from Wait_List_Type__c where name ='Public Housing' limit 1];
        
        Enrolled_Wait_List__c en=new Enrolled_Wait_List__c();
        en.Applications__c=app.id;
        en.Current_Status__c='Onlist';
        en.Wait_List_Type__c=wltype.id;
        en.Bed_size__c=1;
        en.Prefernce_Point__c=3;
        en.Lottery__c=45673;
        en.Limit__c='eli-30';
        en.Reason__c ='Active';  
        
        insert en;
        
        
        
        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        wls.Wait_List_Type__c = wltype.id;
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=5;
        wls.Bedroom_Size__c=1;
        wls.Pull_Rank__c=45673;
        wls.RAD_Current_Scheduler_Count__c = 1;
        
        
        insert wls;
        
        wls.Applicant_at_eli_30_75__c = 2;
        wls.Applicant_at_vli_50_25__c = 1;
        wls.Applicant_at_LI_80__c     = 1;
        update wls;
        Test.startTest(); 
        
        wls.Status__c = 'Scheduled';
        update wls;
        
        Datetime dt = Datetime.now();
        Integer tempMin = dt.minute() + 1 ;  //dont use current min, 
        if(tempMin >= 59){
            tempMin = 0;
        }
        System.assertEquals(en.Current_Status__c, 'Onlist');
        String cronExpr = '0 ' + tempMin + ' * * * ? *';
        RAD_PubHsgScheduler rabpbs=new RAD_PubHsgScheduler(wls.id);
        system.schedule('Test Password Reminder', cronExpr, rabpbs);
        Test.stopTest();
        
        
        
    }
    public static testMethod void PB_Scheduletest2vli()
    {
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
               
        TestSuiteHelper.setupCustomSettings();  
        Account A1 = TestSuiteHelper.setupTestAccount();
        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        
        
        Contact con1=new  Contact();
        //con.Name='test@cgi.com';
        con1.FirstName='testtest';
        con1.LastName='testLa';
        con1.accountId = A1.id;
        con1.Contact_Type__c  = 'Community Global User';
        con1.Do_not_Have__c  = true;
        con1.Date_of_Birth__c  = Date.Today().addMonths(-400);
        con1.Gender__c = 'Female';
        
        con1.Residential_Street__c=  'Residency Street'; 
        con1.Residential_City__c = 'San Diego';
        con1.Residential_State__c = 'CA';
        con1.Residential_Zipcode__c ='71117';
        
        con1.MailingStreet = 'EastMail Street'; 
        con1.MailingCity = 'San Diego';
        con1.MailingState = 'CA';
        con1.MailingPostalCode ='71119';
        
        con1.RecordTypeId = idd;
        con1.Active__c='Yes';
        insert con1;
        
        
        Applications__c app1=new Applications__c();
        app1.Applicant__c=con1.id;
        
        app1.Ethnicity__c = 'Hispanic or Latino';
        //app1.Public_Housing__c = true;
        app1.Application_Status__c = 'Submitted';
        app1.of_people_in_the_H_H_Adults__c = 1;
        app1.Dependents_Children_under_age_of_18__c = 1;
        app1.Family_Annual_Income__c = 10000;
        app1.White__c =  true;
        app1.Black__c = true;
        app1.Citizenship__c = 'Eligible Citizen';
        app1.RAD_Next_Purge_Request_Date__c=Date.today();
        app1.Family__c=true;
        app1.Homeless_with_disability__c=true;
        app1.Live_Work_in_City_of_San_Diego__c=true;
        app1.Non_Elderly_Disabled__c=true;
        app1.Veteran_Family_of__c=true;
        
        insert app1;
        //clearing WL to work for mig and normal mode        
        List<Enrolled_Wait_List__c> wlst = [Select id from Enrolled_Wait_List__c where Applications__c =: app1.id ];
        Database.delete(wlst, false);
        
        Wait_List_Type__c wltype1 =[Select id from Wait_List_Type__c where name ='Public Housing' limit 1];
        
        Enrolled_Wait_List__c en1=new Enrolled_Wait_List__c();
        en1.Applications__c=app1.id;
        en1.Current_Status__c='Onlist';
        en1.Wait_List_Type__c=wltype1.id;
        en1.Bed_size__c=1;
        en1.Prefernce_Point__c=12;
        en1.Lottery__c=67856;
        en1.Limit__c='vli-50';
        en1.Reason__c ='Active';  
        insert en1;
        
        
        Test.startTest();
        Wait_List_Selection__c wls1 = new Wait_List_Selection__c();
        wls1.Wait_List_Type__c = wltype1.id;
        wls1.Scheduled_Date__c = Date.Today()+1;
        wls1.Schedule_Time__c = '4:00 PM';
        wls1.Number_of_vacancies_to_fill__c=5;
        wls1.Bedroom_Size__c=1;
        wls1.Pull_Rank__c=67856;
        wls1.RAD_Current_Scheduler_Count__c = 1;
        
        
        insert wls1;
        
        wls1.Applicant_at_eli_30_75__c = 1;
        wls1.Applicant_at_vli_50_25__c = 2;
        wls1.Applicant_at_LI_80__c     = 1;
        update wls1;
        
        
        wls1.Status__c = 'Scheduled';
        update wls1;
        
        Datetime dt = Datetime.now();
        Integer tempMin = dt.minute() + 1 ;  //dont use current min, 
        if(tempMin >= 59){
            tempMin = 0;
        }
        System.assertEquals(en1.Current_Status__c, 'Onlist');
        String cronExpr = '0 ' + tempMin + ' * * * ? *';
        RAD_PubHsgScheduler rabpbs=new RAD_PubHsgScheduler(wls1.id);
        system.schedule('Test Password Reminder', cronExpr, rabpbs);
        Test.stopTest();
        
        
        
    }
    public static testMethod void PB_Scheduletest3li()
    {

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
        
        TestSuiteHelper.setupCustomSettings();
        Account A1 = TestSuiteHelper.setupTestAccount();
        
        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId(); 
        Contact con1=new  Contact();
        con1.FirstName='testtest';
        con1.LastName='testLa';
        con1.accountId = A1.id;
        con1.Contact_Type__c  = 'Community Global User';
        
        con1.RecordTypeId = idd;
        con1.Active__c='Yes';
        insert con1;
        
        
        Applications__c app1=new Applications__c();
        
        app1.Applicant__c=con1.id;
        app1.Ethnicity__c = 'Hispanic or Latino';
        app1.Family_Annual_Income__c=40000;
        app1.White__c=true;
        app1.Asian__c=  true;
        app1.Black__c = true;
        app1.American_Indian__c=true;
        app1.Pacific_Islander__c=true;
        
        app1.of_people_in_the_H_H_Adults__c = 1;
        app1.Dependents_Children_under_age_of_18__c = 0;
        app1.Application_Status__c = 'Submitted';
        
        insert app1;
        
        //clearing WL to work for mig and normal mode        
        List<Enrolled_Wait_List__c> wlst = [Select id from Enrolled_Wait_List__c where Applications__c =: app1.id ];
        Database.delete(wlst, false);
        
        Wait_List_Type__c wltype1 =[Select id from Wait_List_Type__c where name ='Public Housing' limit 1];
        
        
        Enrolled_Wait_List__c en1=new Enrolled_Wait_List__c();
        //en.Name='test';
        en1.Applications__c=app1.id;
        en1.Current_Status__c='Onlist';
        en1.Wait_List_Type__c=wltype1.id;
        en1.Bed_size__c=4;
        en1.Prefernce_Point__c=3;
        en1.Lottery__c=67856;
        en1.Limit__c='li-80';
        en1.Reason__c ='Active';
        
        insert en1;
        
        
        
        Wait_List_Selection__c wls1 = new Wait_List_Selection__c();
        wls1.Wait_List_Type__c = wltype1.id;
        wls1.Scheduled_Date__c = Date.Today()+1;
        wls1.Schedule_Time__c = '4:00 PM';
        wls1.Number_of_vacancies_to_fill__c=5;
        wls1.Bedroom_Size__c=4;
        wls1.Pull_Rank__c=67856;
        wls1.RAD_Current_Scheduler_Count__c = 1;
        
        
        
        insert wls1;
        
        wls1.Applicant_at_eli_30_75__c = 1;
        wls1.Applicant_at_vli_50_25__c = 0;
        wls1.Applicant_at_LI_80__c     = 2;
        update wls1;
        
        Test.startTest();
        wls1.Status__c = 'Scheduled';
        update wls1;
        
        Datetime dt = Datetime.now();
        Integer tempMin = dt.minute() + 1 ;  //dont use current min, 
        if(tempMin >= 59){
            tempMin = 0;
        }
        System.assertEquals(en1.Current_Status__c, 'Onlist');
        String cronExpr = '0 ' + tempMin + ' * * * ? *';
        RAD_PubHsgScheduler rabpbs=new RAD_PubHsgScheduler(wls1.id);
        system.schedule('Test Password Reminder', cronExpr, rabpbs);
        Test.stopTest();
        
        
        
    }
    public static testMethod void PB_Scheduletestallzeros()
    {

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
        
        TestSuiteHelper.setupCustomSettings();
        Account A1 = TestSuiteHelper.setupTestAccount();
        
        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId(); 
        Contact con1=new  Contact();
        con1.FirstName='testtest';
        con1.LastName='testLa';
        con1.accountId = A1.id;
        con1.Contact_Type__c  = 'Community Global User';
        
        con1.RecordTypeId = idd;
        con1.Active__c='Yes';
        insert con1;
        
        
        Applications__c app1=new Applications__c();
        
        app1.Applicant__c=con1.id;
        app1.Ethnicity__c = 'Hispanic or Latino';
        app1.Family_Annual_Income__c=40000;
        app1.White__c=true;
        app1.Asian__c=  true;
        app1.Black__c = true;
        app1.American_Indian__c=true;
        app1.Pacific_Islander__c=true;
        
        app1.of_people_in_the_H_H_Adults__c = 1;
        app1.Dependents_Children_under_age_of_18__c = 0;
        app1.Application_Status__c = 'Submitted';
        
        insert app1;
        
        //clearing WL to work for mig and normal mode        
        List<Enrolled_Wait_List__c> wlst = [Select id from Enrolled_Wait_List__c where Applications__c =: app1.id ];
        Database.delete(wlst, false);
        
        Wait_List_Type__c wltype1 =[Select id from Wait_List_Type__c where name ='Public Housing' limit 1];
        
        
        Enrolled_Wait_List__c en1=new Enrolled_Wait_List__c();
        //en.Name='test';
        en1.Applications__c=app1.id;
        en1.Current_Status__c='Onlist';
        en1.Wait_List_Type__c=wltype1.id;
        en1.Bed_size__c=4;
        en1.Prefernce_Point__c=3;
        en1.Lottery__c=67856;
        en1.Limit__c='li-80';
        en1.Reason__c ='Active';
        
        insert en1;
        
        
        
        Wait_List_Selection__c wls1 = new Wait_List_Selection__c();
        wls1.Wait_List_Type__c = wltype1.id;
        wls1.Scheduled_Date__c = Date.Today()+1;
        wls1.Schedule_Time__c = '4:00 PM';
        wls1.Number_of_vacancies_to_fill__c=3;
        wls1.Bedroom_Size__c=4;
        wls1.Pull_Rank__c=67856;
        wls1.RAD_Current_Scheduler_Count__c = 1;
        
        
        
        insert wls1;
        
        wls1.Applicant_at_eli_30_75__c = 0;
        wls1.Applicant_at_vli_50_25__c = 0;
        wls1.Applicant_at_LI_80__c     = 0;
        update wls1;
        
        Test.startTest();
        wls1.Status__c = 'Scheduled';
        update wls1;
        
        Datetime dt = Datetime.now();
        Integer tempMin = dt.minute() + 1 ;  //dont use current min, 
        if(tempMin >= 59){
            tempMin = 0;
        }
        System.assertEquals(en1.Current_Status__c, 'Onlist');
        String cronExpr = '0 ' + tempMin + ' * * * ? *';
        RAD_PubHsgScheduler rabpbs=new RAD_PubHsgScheduler(wls1.id);
        system.schedule('Test Password Reminder', cronExpr, rabpbs);
        Test.stopTest();
        
        
        
    }
    
    
}