src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Update Required</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>On List</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Not Hispanic or Latino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Family</label>
        <type>Checkbox</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checkbox_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Community Global User</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Housing Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Inspector</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>On-Site Manager</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Property Manager</fullName>
                </value>
                <value>
                    <fullName>Rehab HC Specialist</fullName>
                </value>
                <value>
                    <fullName>Resident Manager</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First - Housing Our Heroes</fullName>
                </value>
                <value>
                    <fullName>Landlord/Owner</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Community Member</fullName>
                </value>
                <value>
                    <fullName>Housing Specialist</fullName>
                </value>
                <value>
                    <fullName>Section 3 Resident</fullName>
                </value>
                <value>
                    <fullName>Primary Business Contact</fullName>
                </value>
                <value>
                    <fullName>Business Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Business Admin Contact</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Payroll Contact</fullName>
                </value>
                <value>
                    <fullName>Co-Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First Client_FY18</fullName>
                </value>
                <value>
                    <fullName>Housing First Client - FY17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>Rental Assistance Wait List Portal Record Type</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onlist</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issue/Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prefernce_Point__c</fullName>
        <label>Preference Point</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Current_Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Over Income</fullName>
                </value>
                <value>
                    <fullName>Criminal</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Refused Offer</fullName>
                </value>
                <value>
                    <fullName>Income Targeting</fullName>
                </value>
                <value>
                    <fullName>System Selection</fullName>
                </value>
                <value>
                    <fullName>NED</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Briefing</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Dropped</fullName>
                </value>
                <value>
                    <fullName>Dropped/No Update 2011</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>Lease Up</fullName>
                </value>
                <value>
                    <fullName>No Show/Response</fullName>
                </value>
                <value>
                    <fullName>Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Offer Rejected</fullName>
                </value>
                <value>
                    <fullName>Voucher Cancelled</fullName>
                </value>
                <value>
                    <fullName>Voucher Expired</fullName>
                </value>
                <value>
                    <fullName>Voucher Issued</fullName>
                </value>
                <value>
                    <fullName>Yearly Updated</fullName>
                </value>
                <value>
                    <fullName>Special Admission</fullName>
                </value>
                <value>
                    <fullName>See Memo</fullName>
                </value>
                <value>
                    <fullName>Accessibility Needs</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Deconcentrate Poverty</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>No, Response</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Request</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted Selection</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Vou Expired</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On List</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issued/Offer</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Refused</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <fields>
        <fullName>RADFamily__c</fullName>
        <label>Family</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADLive_Work_in_City_of_San_Diego__c</fullName>
        <label>Live/Work in City of San Diego</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADNon_Elderly_Disabled__c</fullName>
        <label>Elderly</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADVeteran_Active_Military__c</fullName>
        <label>Veteran / Active Military</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_LandingCtrlrTest.cls
@isTest
public class RAD_LandingCtrlrTest
{    
    static testMethod void RADLandingCtrlrMethod() 
    {         
        TestSuiteHelper.setupCustomSettings();
        PageReference pageRef = Page.RADNewLand;
        Test.setCurrentPage(pageRef);
        
        Test.StartTest();
        RAD_LandPageCtrlr controller = new RAD_LandPageCtrlr();
        controller.init();
        
        
        Test.StopTest();    
        
    }
    
    static testMethod void testLandingCntrlr() 
    {         
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;    
        
        TestSuiteHelper.setupCustomSettings();
        List<Contact> cts =TestSuiteHelper.setupPortalRequiredData();  
        Contact ct = cts[0];
        Applications__c app = [Select id, Application_Status__c from Applications__c limit 1]; // where Applicant__c =:ct.id 
        
        String jsonApp = json.serialize(app);
        String jsonCt = json.serialize(ct);
        Wait_List_Type__c wlt = [Select name, RADFamily__c, RADLive_Work_in_City_of_San_Diego__c, 
                                 RADNon_Elderly_Disabled__c, RADVeteran_Active_Military__c from Wait_List_Type__c where name ='Public Housing' limit 1];
        Test.StartTest();
        RAD_LandPageCtrlr.getZipCodeLocation('11', '92101');
        RAD_LandPageCtrlr.getZipCodeLocation('123','123');
        //RAD_LandPageCtrlr.saveSubmit(jsonApp, jsonCt, 'save');
        //RAD_LandPageCtrlr.saveSubmit(jsonApp, jsonCt, 'submit');
        RAD_LandPageCtrlr.getApplication(app.id);
        RAD_LandPageCtrlr.confirmPurgeExtnInterest(app.id);
        RAD_LandPageCtrlr.confirmPurgeExtnInterest('noid');
        RAD_LandPageCtrlr.reapplyWL('noid');
        List<Enrolled_Wait_List__c> wls = [Select id from Enrolled_Wait_List__c  where Applications__c =:app.id limit 1] ;
        Enrolled_Wait_List__c ew = new Enrolled_Wait_List__c();
        if(wls.isEmpty()){
            ew = new Enrolled_Wait_List__c();
            ew.Wait_List_Type__c=wlt.id;
            ew.Prefernce_Point__c=Decimal.valueof('3'); 
            ew.Applications__c=app.id;   
            ew.Current_Status__c='Onlist'; 
            ew.Status__c = 'On List';
            ew.Reason__c ='Active';
            
            //Database.insert( ew, false);      
        }else{
            ew = wls[0];
        }
        RAD_LandPageCtrlr.reapplyWL(ew.id);
        
        RAD_LandPageCtrlr r = new RAD_LandPageCtrlr();
            r.getContactandApplication();
        
        Test.StopTest();    
        
    }
    
    static testmethod void testUser(){
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;    
        
        Test.startTest();
       TestSuiteHelper.setupCustomSettings();
        Contact con=new  Contact();
        Account acc = TestSuiteHelper.setupTestAccount();
        Id idd1 = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        con.AccountId = acc.id;
        con.FirstName='testuser';
        con.LastName='testLast';
        con.Contact_Type__c='Community Global User';
        con.Email='test@cgi.com';
        con.RecordTypeId = idd1;
        con.Active__c = 'Yes';
        insert con;
         Applications__c app = new Applications__c();
            app.Applicant__c = con.id;
            app.Ethnicity__c = 'Hispanic or Latino';
            app.Public_Housing__c = true;
            app.Application_Status__c = 'Submitted';
            app.Family_Annual_Income__c = 10000;
            app.White__c =  true;
            app.Black__c = true;
            app.Citizenship__c = 'Eligible Citizen';
            app.of_people_in_the_H_H_Adults__c = 1;
            app.Dependents_Children_under_age_of_18__c = 1;
            app.Family__c = true;
          insert app;
           Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='Public Housing' limit 1];
           List<Enrolled_Wait_List__c> wlst = [Select id from Enrolled_Wait_List__c where Applications__c =: app.id ];
            Database.delete(wlst, false);
          Enrolled_Wait_List__c ew = new Enrolled_Wait_List__c();
             ew.Current_Status__c= 'Removed';
             ew.Wait_List_Type__c=wlt.id;
             ew.Prefernce_Point__c=Decimal.valueof('3'); 
             ew.Applications__c=app.id;
             ew.Reason__c ='Active';   

             Database.insert( ew, false);
        
        Profile p = [select id from profile where name='RAD_Community_Profile']; 
        User u = new User();
            u.FirstName = 'testuser';
            u.LastName = 'testLast';
            u.username = con.Email;
            u.ProfileId  = p.id;
            u.CommunityNickname = 'tcwoq';
            U.alias = 'rusrr';
            u.Email = con.Email;
            u.TIMEZONESIDKEY = 'America/Los_Angeles';
            u.contactId = con.id;
            u.emailencodingkey='UTF-8';
            u.languagelocalekey='en_US';
            
            u.localesidkey='en_US';
            insert u;
        System.runAs(u){
            RAD_LandPageCtrlr.profile_In_Appl();  
            RAD_LandPageCtrlr r = new RAD_LandPageCtrlr();
            r.getContactandApplication();
            
        }
        Test.stopTest();
        
        
    }
    
    static testMethod void testnewApp() {
    
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
    
        TestSuiteHelper.setupCustomSettings();
        List<Contact> cts =TestSuiteHelper.setupPortalRequiredData();  
        Contact ct = cts[0];
        Applications__c app = [Select id, Application_Status__c from Applications__c limit 1]; // where Applicant__c =:ct.id 
        
        Wait_List_Type__c wlt = [Select name, RADFamily__c, RADLive_Work_in_City_of_San_Diego__c, 
                                 RADNon_Elderly_Disabled__c, RADVeteran_Active_Military__c from Wait_List_Type__c where name ='Public Housing' limit 1];
        Test.StartTest();
       
        app.Applicant__c = null;
        Database.update(app, false);
        
        String jsonApp = json.serialize(app);
        
        
        RAD_LandPageCtrlr.saveSubmit(jsonApp, null, 'submit');
        
        
        
    }
    static testMethod void testClosedApp() {

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;    
        TestSuiteHelper.setupCustomSettings();
        List<Contact> cts =TestSuiteHelper.setupPortalRequiredData();  
        Contact ct = cts[0];
        Applications__c app = [Select id, Application_Status__c from Applications__c  limit 1]; //where Applicant__c =:ct.id
        
        app.Application_Status__c ='Closed';
        Database.update(app, false);
        
        String jsonApp = json.serialize(app);
        String jsonCt = json.serialize(ct);
        Wait_List_Type__c wlt = [Select name, RADFamily__c, RADLive_Work_in_City_of_San_Diego__c, 
                                 RADNon_Elderly_Disabled__c, RADVeteran_Active_Military__c from Wait_List_Type__c where name ='Public Housing' limit 1];
        Test.StartTest();
        
        //RAD_LandPageCtrlr.saveSubmit(jsonApp, jsonCt, 'submit');
        
        
    }
    
}