src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checkbox_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paperless_Email_only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paperless/Email only:</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Person_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On List</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issued/Offer</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Refused</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Selection_Records__c.object
<CustomObject>
    <fields>
        <fullName>RAD_Wait_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List</label>
        <referenceTo>Enrolled_Wait_List__c</referenceTo>
        <relationshipLabel>Selection Records</relationshipLabel>
        <relationshipName>Selection_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selection_ID__c</fullName>
        <label>Wait List Selection</label>
        <referenceTo>Wait_List_Selection__c</referenceTo>
        <relationshipLabel>Selection Records</relationshipLabel>
        <relationshipName>Selection_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Selection Record</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selection Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/objects/Wait_List_Selection__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait List Selections</relationshipLabel>
        <relationshipName>Wait_List_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Wait List Selection</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait List Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_projectbased_Notify_Batch.cls
global class RAD_projectbased_Notify_Batch implements Database.batchable<sObject>,Database.Stateful{
    global String selRunId;
    global String query;
    global string letter;
    global string addrs;
    global string ownersph;
    global string bedsize;
    global Date cmdates;
    global String owneraddr;
    global String newdate;
    global Date respdate;
    global string newresdate;
    global string casewoker;
    global string todaydate;
    global list<Selection_Records__c> finalSelIds;
    global string ownerPhoneNo;
    
    
    
    global RAD_projectbased_Notify_Batch( String s, string le,string addr, string owner,string bedroom,Date cmdate,string owneradd,Date resdate,string casework,string todaydat,list<Selection_Records__c> finalSelIds,string ownerPhone)
    {      
        
        selRunId=s;
        letter=le;
        addrs=addr;
        ownersph=owner;
        bedsize=bedroom;
        cmdates=cmdate;
        this.finalSelIds = finalSelIds;
        ownerPhoneNo = ownerPhone;
        
        
        if(cmdates!=Null)
        {
            newdate=cmdates.format();
        }
        owneraddr=owneradd;  
        respdate=resdate;
        if(newresdate!=null)
        {
            newresdate=resdate.format();
        }
        casewoker=casework;
        todaydate=todaydat;
        
        system.debug('strQuery------->'+ s);
        system.debug('selected letter is------->'+ letter);                
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        
        query= 'select Name,Status__c,Selection_ID__c,Selection_ID__r.Name,RAD_Wait_List__c,RAD_Wait_List__r.Wait_List_Type__c,RAD_Wait_List__r.Wait_List_Type__r.Name, RAD_Wait_List__r.Name,RAD_Wait_List__r.Applications__c,RAD_Wait_List__r.Applications__r.Name,RAD_Wait_List__r.Applications__r.Applicant__c,RAD_Wait_List__r.Applications__r.Applicant__r.Name,RAD_Wait_List__r.Applications__r.Applicant__r.Email,RAD_Wait_List__r.Applications__r.Applicant__r.Person_Email__c ,RAD_Wait_List__r.Applications__r.Applicant__r.Paperless_Email_only__c from Selection_Records__c where id=:finalSelIds and Status__c=\'Selected\' ';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Selection_Records__c > scope)
        
    {
        PageReference pdf = null;
        
        Id folderReApplyId = [select id from folder where name ='Notice of Opportunity - MR'].Id; 
        Id folderProjectbasedId = [select id from folder where name ='Notice of Opportunity - PBV'].Id; 
        Id folderPbsId = [select id from folder where name ='Notice of Opportunity - PBS'].Id;
        Id folderMRRefId = [select id from folder where name ='Notice of Owner Referral - MR'].Id;
        Id folderPBRefId = [select id from folder where name ='Notice of Owner Referral - PBV'].Id;
        Id folderPBSRefId = [select id from folder where name ='Notice of Owner Referral - PBS'].Id;
        
        
        List<Document> docList = new List<Document>();
        Document doc = new Document();
        Blob b = null;
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
        List<Messaging.SingleEmailMessage> emailLst = new List<Messaging.SingleEmailMessage>();
        
        
        for(Selection_Records__c sr:scope )    
        {
            
            
            list<Selection_Records__c> cust=new List<Selection_Records__c>();
            
            
            
            
            if( sr.RAD_Wait_List__r.Wait_List_Type__r.Name =='Mod Rehab' && (letter=='NOletter'|| letter=='NORLetter'))
            {
                
                pdf = new PageReference('/apex/RAD_Mod_Rehab_Notice_opp_Letter?&urlparm='+ownersph + '&unitaddres=' + addrs + '&bsize=' + bedsize+ '&cmdat=' + newdate+'&owneraddress='+owneraddr+ '&caseworkert='+casewoker+ '&ownPhNo='+ownerPhoneNo);     
               
                system.debug('$$$$ url ownersph value ' +ownersph );
                system.debug('$$$$ url unitaddres value ' +addrs );
                system.debug('$$$$ url bsize value ' +bedsize );
                system.debug('$$$$ url cmdat value ' +newdate);
                system.debug('$$$$ url owneraddress value ' +owneraddr);
                system.debug('$$$$ url caseworkert value ' +casewoker);
                system.debug('$$$$ url caseowner phonenumber value ' +ownerPhoneNo);
                
                
                pdf.setRedirect(true);
                pdf.getParameters().put('id', sr.id);
                if(!Test.isRunningTest()){ 
                    b = pdf.getContent(); 
                }
                doc = new Document();         
                
                doc.name=sr.RAD_Wait_List__r.Applications__r.Name+'_'+sr.Name+'_ '+ todaydate+'.pdf'; 
                doc.body = b;
                doc.FolderId =folderReApplyId;
                docList.add(doc);
            } 
            
            
            else if( sr.RAD_Wait_List__r.Wait_List_Type__r.Name =='project Based' && (letter=='NOletter'|| letter=='NORLetter')) {
                
                
                
                
                pdf = new PageReference('/apex/RAD_Projectbased_Noti_Opp_Letter?&urlparm='+ownersph + '&unitaddres=' + addrs + '&bsize=' + bedsize+ '&cmdat=' + newdate+'&owneraddress='+owneraddr+ '&caseworkert='+casewoker+ '&ownPhNo ='+ownerPhoneNo);               
                
                pdf.setRedirect(true);
                pdf.getParameters().put('id', sr.id);
                if(!Test.isRunningTest()){ 
                    b = pdf.getContent(); 
                }
                doc = new Document();         
                
                doc.name=sr.RAD_Wait_List__r.Applications__r.Name+'_'+sr.Name+'_ '+ todaydate+'.pdf'; 
                doc.body = b;
                doc.FolderId =folderProjectbasedId;
                docList.add(doc); 
            } 
            
            else if( sr.RAD_Wait_List__r.Wait_List_Type__r.Name =='Project Based Single' && (letter=='NOletter'|| letter=='NORLetter'))  {
                
                
                
                pdf = new PageReference('/apex/RAD_PBS_Notice_Letter?&urlparm='+ownersph + '&unitaddres=' + addrs + '&bsize=' + bedsize+ '&cmdat=' + newdate+'&owneraddress='+owneraddr+ '&caseworkert='+casewoker+ '&ownPhNo ='+ownerPhoneNo);               
                
                pdf.setRedirect(true);
                pdf.getParameters().put('id', sr.id);
                if(!Test.isRunningTest()){ 
                    b = pdf.getContent();
                }
                doc = new Document();         
                
                doc.name=sr.RAD_Wait_List__r.Applications__r.Name+'_'+sr.Name+'_ '+ todaydate+'.pdf'; 
                doc.body = b;
                doc.FolderId =folderPbsId ;
                docList.add(doc); 
            } 
            
            
            
        }  
        List<Database.SaveResult> docResultList   =  Database.insert(docList, false);
        Messaging.SendEmailResult [] results = Messaging.sendEmail(emailLst, false);
        
    }
    global void finish(Database.BatchableContext BC)
    {
        
     /*   // Set Application Trigger on during run.
        SwitchTrigger__c AppTrigger = SwitchTrigger__c.getInstance('Applications__c');
        if(AppTrigger != Null) {
            AppTrigger.Active__c = false;
            update AppTrigger;
        }    */    
        
        AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed,
                          TotalJobItems, CreatedBy.Email
                          from AsyncApexJob where Id =
                          :BC.getJobId()];
        // Send an email to the Apex job's submitter notifying of job completion.  
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[]{a.CreatedBy.Email};
            mail.setToAddresses(toAddresses);
        
        
        mail.setSubject('Project Based Notification Batch Completed.');
        mail.setPlainTextBody(
            'Batch Process has completed.'
            
        );
        
        try {
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        } catch(System.EmailException sme) {
            //DO NOTHING...
        }
    }            
    
}