src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Update Required</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>On List</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dependents_Children_under_age_of_18__c</fullName>
        <label>Dependents/Children under age of 18</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Not Hispanic or Latino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Annual_Income__c</fullName>
        <label>Family Annual Income</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Live_Work_in_City_of_San_Diego__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Applicant lives or works within the City of San Diego</description>
        <label>Live/Work in City of San Diego</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PBV_Project_Based__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PBV-Project Based</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>White__c</fullName>
        <defaultValue>false</defaultValue>
        <label>White</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_people_in_the_H_H_Adults__c</fullName>
        <label># of people in the H/H - Adults</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checkbox_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Community Global User</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Housing Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Inspector</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>On-Site Manager</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Property Manager</fullName>
                </value>
                <value>
                    <fullName>Rehab HC Specialist</fullName>
                </value>
                <value>
                    <fullName>Resident Manager</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First - Housing Our Heroes</fullName>
                </value>
                <value>
                    <fullName>Landlord/Owner</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Community Member</fullName>
                </value>
                <value>
                    <fullName>Housing Specialist</fullName>
                </value>
                <value>
                    <fullName>Section 3 Resident</fullName>
                </value>
                <value>
                    <fullName>Primary Business Contact</fullName>
                </value>
                <value>
                    <fullName>Business Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Business Admin Contact</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Payroll Contact</fullName>
                </value>
                <value>
                    <fullName>Co-Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First Client_FY18</fullName>
                </value>
                <value>
                    <fullName>Housing First Client - FY17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paperless_Email_only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paperless/Email only:</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>Rental Assistance Wait List Portal Record Type</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bed_size__c</fullName>
        <label>Bed size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onlist</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issue/Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lottery__c</fullName>
        <label>Lottery</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prefernce_Point__c</fullName>
        <label>Preference Point</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Applied_Date_and_Time__c</fullName>
        <description>This field is updated when WL is created and reapplied</description>
        <inlineHelpText>This field is updated when WL is created and reapplied</inlineHelpText>
        <label>Applied Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Current_Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Over Income</fullName>
                </value>
                <value>
                    <fullName>Criminal</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Refused Offer</fullName>
                </value>
                <value>
                    <fullName>Income Targeting</fullName>
                </value>
                <value>
                    <fullName>System Selection</fullName>
                </value>
                <value>
                    <fullName>NED</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Briefing</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Dropped</fullName>
                </value>
                <value>
                    <fullName>Dropped/No Update 2011</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>Lease Up</fullName>
                </value>
                <value>
                    <fullName>No Show/Response</fullName>
                </value>
                <value>
                    <fullName>Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Offer Rejected</fullName>
                </value>
                <value>
                    <fullName>Voucher Cancelled</fullName>
                </value>
                <value>
                    <fullName>Voucher Expired</fullName>
                </value>
                <value>
                    <fullName>Voucher Issued</fullName>
                </value>
                <value>
                    <fullName>Yearly Updated</fullName>
                </value>
                <value>
                    <fullName>Special Admission</fullName>
                </value>
                <value>
                    <fullName>See Memo</fullName>
                </value>
                <value>
                    <fullName>Accessibility Needs</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Deconcentrate Poverty</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>No, Response</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Request</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted Selection</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Vou Expired</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_WeeklyModifiedStatusBatch_test.cls
@isTest
public class RAD_WeeklyModifiedStatusBatch_test{
    public static testmethod void wkmodfedstbt()
    {
list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
sw_list.add(sw);
SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
sw_list.add(swWL);
insert sw_list;        
        TestSuiteHelper.setupCustomSettings();
        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        
        
        
        Contact con=new  Contact();
        
        con.FirstName='test';
        con.LastName='testLast';
        con.Contact_Type__c  = 'Community Global User';
        con.RecordTypeId = idd;
        con.Active__c='Yes';
        insert con;
        
        Applications__c app=new Applications__c();
        app.Applicant__c=con.id;
        app.Ethnicity__c = 'Hispanic or Latino';
        app.Family_Annual_Income__c=Decimal.valueof('1000');
        app.White__c=true;
        app.of_people_in_the_H_H_Adults__c = 1;
        app.Dependents_Children_under_age_of_18__c = 0;
        app.Application_Status__c ='Submitted';
        app.PBV_Project_Based__c =true;
        app.Live_Work_in_City_of_San_Diego__c = true;
        
        
        insert app;
        
        
        //clearing WL to work for mig and normal mode        
        List<Enrolled_Wait_List__c> wlst = [Select id from Enrolled_Wait_List__c where Applications__c =: app.id ];
        Database.delete(wlst, false);
        
        Wait_List_Type__c wltype =[Select id from Wait_List_Type__c where name ='Project Based' limit 1];
        
        
        Enrolled_Wait_List__c en=new Enrolled_Wait_List__c();
        en.Applications__c=app.id;
        en.Current_Status__c='Onlist';
        en.Reason__c ='Active';   
        en.Wait_List_Type__c=wltype.id;
        en.Bed_size__c=4;
        en.Prefernce_Point__c=3;
        en.Lottery__c=78901;
        en.Limit__c='eli-30';
        en.RAD_Applied_Date_and_Time__c = datetime.now();
        insert en;
        
        
        
        Test.StartTest();
        RAD_WeeklyModifiedStatusBatch wmsb = new RAD_WeeklyModifiedStatusBatch();
        
        Database.executeBatch(wmsb );
        
        Test.StopTest();   
        //System.AssertEquals(database.countquery('SELECT COUNT()'+' FROM Topic '), 3);
    }
    public static testmethod void wkmodfedstbtEmail()
    {
        
 list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
sw_list.add(sw);
SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
sw_list.add(swWL);
insert sw_list;
       
        TestSuiteHelper.setupCustomSettings();
        
        List<Applications__c>lstAppln = new List<Applications__c>();
        
        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        Contact con=new  Contact();
        
        con.FirstName='test';
        con.LastName='testLast';
        con.Contact_Type__c  = 'Community Global User';
        con.Email='test1abc@cgi.com';
        con.RecordTypeId = idd;
        con.Active__c='Yes';
        insert con;
        Applications__c acc = new Applications__c();
        
        acc.Applicant__c=con.id;
        acc.Ethnicity__c = 'Hispanic or Latino';
        acc.Family_Annual_Income__c=Decimal.valueof('1000');
        acc.White__c=true;
        acc.of_people_in_the_H_H_Adults__c = 1;
        acc.Dependents_Children_under_age_of_18__c = 0;
        acc.Application_Status__c ='Submitted';
        acc.PBV_Project_Based__c =true;
        acc.Live_Work_in_City_of_San_Diego__c = true;
        
        
        lstAppln.add(acc);
        //insert acc;
        Contact con1=new  Contact();
        //con.Name='test@cgi.com';
        con1.FirstName='test';
        con1.LastName='testLast';
        con1.Contact_Type__c  = 'Community Global User';
        con1.Email='testdef@cgi.com';
        con1.Active__c='Yes';
        con1.RecordTypeId = idd;
        insert con1;
        Applications__c acc1 = new Applications__c();
        
        acc1.Applicant__c=con1.id;
        acc1.Ethnicity__c = 'Hispanic or Latino';
        acc1.Family_Annual_Income__c=Decimal.valueof('1000');
        acc1.White__c=true;
        acc1.of_people_in_the_H_H_Adults__c = 1;
        acc1.Dependents_Children_under_age_of_18__c = 0;
        acc1.Application_Status__c ='Submitted';
        acc1.PBV_Project_Based__c =true;
        acc1.Live_Work_in_City_of_San_Diego__c = false;
        
        lstAppln.add(acc1);
        //insert acc1;
        
        Contact con2=new  Contact();
        //con.Name='test@cgi.com';
        con2.FirstName='test';
        con2.LastName='testLast';
        con2.Contact_Type__c  = 'Community Global User';
        con2.Email='';
        con2.RecordTypeId = idd;
        con2.Paperless_Email_only__c =false;
        con2.Active__c='Yes';
        insert con2;
        Applications__c acc2 = new Applications__c();
        
        acc2.Applicant__c=con2.id;
        acc2.Ethnicity__c = 'Hispanic or Latino';
        acc2.Family_Annual_Income__c=Decimal.valueof('1000');
        acc2.White__c=true;
        acc2.of_people_in_the_H_H_Adults__c = 1;
        acc2.Dependents_Children_under_age_of_18__c = 0;
        acc2.Application_Status__c ='Submitted';
        acc2.PBV_Project_Based__c =true;
        acc2.Live_Work_in_City_of_San_Diego__c = false;
        
        lstAppln.add(acc2);
        
        Database.insert(lstAppln, false);
        
        Test.StartTest();
        
        RAD_WeeklyModifiedStatusBatch wmsb = new RAD_WeeklyModifiedStatusBatch();
        
        Database.executeBatch(wmsb );
        
        Test.StopTest();   
        
    }
    
}