src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>Rental Assistance Wait List Portal Record Type</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Memo__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Memos</relationshipLabel>
        <relationshipName>Memos_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>Showing</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>Rejection</fullName>
                </value>
                <value>
                    <fullName>Move in</fullName>
                </value>
                <value>
                    <fullName>Wait List</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>A-App Status(Not Lv/wk SD)</fullName>
                </value>
                <value>
                    <fullName>A1- Out our Jurisdiction</fullName>
                </value>
                <value>
                    <fullName>B-App Status(iv/wk SD)</fullName>
                </value>
                <value>
                    <fullName>C-App Trans Received</fullName>
                </value>
                <value>
                    <fullName>D- App Trans to County</fullName>
                </value>
                <value>
                    <fullName>D1-App National City</fullName>
                </value>
                <value>
                    <fullName>D2- App Oceanside</fullName>
                </value>
                <value>
                    <fullName>D3-App Carlsbad</fullName>
                </value>
                <value>
                    <fullName>D4-App Encinitas</fullName>
                </value>
                <value>
                    <fullName>Ltr1- WL Confirmation</fullName>
                </value>
                <value>
                    <fullName>Ltr4-WL NE State</fullName>
                </value>
                <value>
                    <fullName>LtrIT-WL Ineligible to Trans</fullName>
                </value>
                <value>
                    <fullName>LtrUT-WL Unable to Trans</fullName>
                </value>
                <value>
                    <fullName>Ltr7- WL Claim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Memo</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Memos</label>
    <nameField>
        <label>Memo Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RAD_WeeklyModifiedTransferBatch.cls
//Transfer update email for applicants living /working in City of San Diego

global class RAD_WeeklyModifiedTransferBatch implements Database.batchable<sObject>,Database.Stateful{
    String query;
    global Integer unprocessedCount;
    
    
    global RAD_WeeklyModifiedTransferBatch()
    {
       query = 'select Id, Name, Status__c, Result__c, Applications__r.Applicant__r.Email, Applications__r.Applicant__r.Paperless_Email_only__c  '+
            ' from Memo__c where lastmodifieddate >= LAST_N_DAYS:7  AND Status__c = \'Scheduled\' AND (Result__c = \'D- App Trans to County\' OR Result__c = \'D1-App National City\' OR Result__c = \'D2- App Oceanside\' OR Result__c = \'D3-App Carlsbad\' OR Result__c = \'D4-App Encinitas\') ';

    }
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Memo__c> scope)
    {    
        
        String docCreatedDate = system.now().format('MM/dd/YYYY') ;//Today's date in MM/dd/YYYY
        List<Document> docList = new List<Document>();
        Document doc = new Document();
        Blob b = null;
        //Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
        //List<Messaging.SingleEmailMessage> emailLst = new List<Messaging.SingleEmailMessage>();
        Id folderWeeklyTransferLettersId = [select id from folder where name ='Transfer Letters'].Id;
        
        
       /* EmailTemplate templateId_SD = [Select id from EmailTemplate 
                                       where name ='Status update email for applicants living /working in City of San Diego'];
        //EmailTemplate templateId_NSD = [Select id from EmailTemplate 
                                        where name ='Status update email for applicants not living/working in City of San Diego']; */
        PageReference pdf = null;            
        
        //Narasimha start 18/07/2017
        for(Memo__c m:scope)    
        {
           
                
                if( (m.Applications__r.Applicant__r.email ==''|| m.Applications__r.Applicant__r.Paperless_Email_only__c==False) && (m.Result__c == 'D- App Trans to County'|| m.Result__c == 'D1-App National City'|| m.Result__c == 'D2- App Oceanside'|| m.Result__c == 'D3-App Carlsbad'|| m.Result__c == 'D4-App Encinitass')){  
                    
                    pdf = Page.RAD_TransferLetters; 
                    
                    pdf.setRedirect(true);
                    pdf.getParameters().put('id', m.id);
                    if (!Test.IsRunningTest()) 
                    {
                        b = pdf.getContent(); 
                    }                  
                    doc = new Document();
                    
                    
                    doc.name = m.name+'_'+docCreatedDate+'.pdf';
                    doc.body = b;
                    
                    doc.FolderId =folderWeeklyTransferLettersId;
                    docList.add(doc);               
                    
                    
               }
                
              /*  else if( String.isNotBlank(m.Applications__r.Applicant__r.email) && m.Result__c!=null){
                    email = new Messaging.SingleEmailMessage(); 
                    email.setTemplateID(templateId_SD.Id);
                    
                    email.setTargetObjectId (m.id);//sending to applicant
                    
                  //  emailLst.add(email);
                    
                    
                } */
                //DO NOTHING   
            
         
            
        } 
        
        // send these count to the batch submitter
        
        List<Database.SaveResult> docResultList   =  Database.insert(docList, false);
        
       // Messaging.SendEmailResult [] results = Messaging.sendEmail(emailLst, false);
       
        
    }
    
    
    
    global void finish(Database.BatchableContext BC)
    {
        AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed,
                          TotalJobItems, CreatedBy.Email
                          from AsyncApexJob where Id =
                          :BC.getJobId()];
        // Send an email to the Apex job's submitter notifying of job completion.  
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[]{a.CreatedBy.Email};
            mail.setToAddresses(toAddresses);
        
        
        mail.setSubject('Weekly Update Status ');
        mail.setPlainTextBody(
            'Batch Process has completed.'
            
        );
        
        
        try {
            
            
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        } catch(System.EmailException sme) {
            //DO NOTHING...
        }
    }            
}