src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Not Hispanic or Latino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Annual_Income__c</fullName>
        <label>Family Annual Income</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Next_Purge_Date__c</fullName>
        <description>This is informational field, which will store the end date of Grace Period.</description>
        <label>Grace Period End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RAD_Next_Purge_Request_Date__c</fullName>
        <label>Next Update Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_People__c</fullName>
        <label>Total People</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>White__c</fullName>
        <defaultValue>false</defaultValue>
        <label>White</label>
        <type>Checkbox</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checkbox_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Community Global User</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Housing Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Inspector</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>On-Site Manager</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Property Manager</fullName>
                </value>
                <value>
                    <fullName>Rehab HC Specialist</fullName>
                </value>
                <value>
                    <fullName>Resident Manager</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First - Housing Our Heroes</fullName>
                </value>
                <value>
                    <fullName>Landlord/Owner</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Community Member</fullName>
                </value>
                <value>
                    <fullName>Housing Specialist</fullName>
                </value>
                <value>
                    <fullName>Section 3 Resident</fullName>
                </value>
                <value>
                    <fullName>Primary Business Contact</fullName>
                </value>
                <value>
                    <fullName>Business Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Business Admin Contact</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Payroll Contact</fullName>
                </value>
                <value>
                    <fullName>Co-Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First Client_FY18</fullName>
                </value>
                <value>
                    <fullName>Housing First Client - FY17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>Rental Assistance Wait List Portal Record Type</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bed_size__c</fullName>
        <label>Bed size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onlist</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issue/Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lottery__c</fullName>
        <label>Lottery</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prefernce_Point__c</fullName>
        <label>Preference Point</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On List</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issued/Offer</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Refused</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YARDI_HMY__c</fullName>
        <label>YARDI HMY</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RAD_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Portal_Contact_Address__c</fullName>
        <label>Portal Contact Address</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Portal_Forgot_Password_Note__c</fullName>
        <label>Portal Forgot Password Note</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Portal_Forgot_UserName_Note__c</fullName>
        <label>Portal Forgot UserName Note</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Purge_Extension_Months__c</fullName>
        <description>Purge Extension in months</description>
        <label>Purge Extension(Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update_Duration_Months__c</fullName>
        <label>Update Duration (Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RAD Configuration</label>
    <nameField>
        <label>RAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/objects/Wait_List_Selection__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait List Selections</relationshipLabel>
        <relationshipName>Wait_List_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Wait List Selection</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait List Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <fields>
        <fullName>YARDI_HMY__c</fullName>
        <externalId>true</externalId>
        <label>YARDI ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_PubHsgSelnCnt_BatchTest.cls
@isTest
public class RAD_PubHsgSelnCnt_BatchTest
{
public static testMethod void PubHsgtest(){

list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
sw_list.add(sw);
SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
sw_list.add(swWL);
insert sw_list;
RAD_Configuration__c confg = new RAD_Configuration__c(Name = 'Main Configurations', Update_Duration_Months__c = 6, RAD_Purge_Extension_Months__c =1,
                RAD_Portal_Forgot_Password_Note__c ='This is Forgotten Password Note', RAD_Portal_Forgot_UserName_Note__c ='This is Forgotten Username Note',
                RAD_Portal_Contact_Address__c = 'This is Portal Contact Address', Announcement__c = 'This is Announcement');
                insert confg;
 Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
 Contact con=new  Contact();
    //con.Name='test@cgi.com';
    con.FirstName='test';
    con.LastName='testLast';
    con.Contact_Type__c='Developer';
    con.RecordTypeId = idd;
    con.Active__c='Yes';

    insert con;
    
    
    Applications__c app=new Applications__c();
    
    app.Applicant__c=con.id;
    app.Ethnicity__c='testEthnicity';
    app.Family_Annual_Income__c=Decimal.valueof('1000');
    app.RAD_Next_Purge_Request_Date__c=Datetime.Now().addMonths(2);
    app.RAD_Next_Purge_Date__c=Datetime.Now(); 
    app.White__c=true;
    app.Total_People__c = 1;
    insert app;
   //clearing WL to work for mig and normal mode        
        List<Enrolled_Wait_List__c> wlst = [Select id from Enrolled_Wait_List__c where Applications__c =: app.id ];
        Database.delete(wlst, false);
        
  
   Wait_List_Type__c wltype=new  Wait_List_Type__c();
    wltype.Name='Public Housing';
    wltype.YARDI_HMY__c=1.233;
    insert wltype;
    
    Enrolled_Wait_List__c en=new Enrolled_Wait_List__c();
      //en.Name='test';
      en.Applications__c=app.id;
      en.Current_Status__c='Onlist';
      en.Wait_List_Type__c=wltype.id;
      en.Bed_size__c=4;
      en.Prefernce_Point__c=3;
      en.Lottery__c=45673;
      en.Limit__c='eli-30';
      en.Reason__c ='Active';  
      
      insert en;
    
    
        
        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        wls.Wait_List_Type__c = wltype.id;
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        wls.Bedroom_Size__c=4;
        wls.Pull_Rank__c=45673;
        wls.RAD_Current_Scheduler_Count__c = 1;
        
        insert wls;
        
        wls.Applicant_at_eli_30_75__c = 2;
        wls.Applicant_at_vli_50_25__c = 1;
        wls.Applicant_at_LI_80__c     = 0;
        update wls;
        

        wls.Status__c = 'Scheduled';
        update wls;
        System.assertEquals(en.Current_Status__c,'Onlist');
         Test.startTest();

           RAD_PubHsgSelnCnt_Batch obj = new RAD_PubHsgSelnCnt_Batch(wls.id,wls.Bedroom_Size__c);
          DataBase.executeBatch(obj); 
            
          Test.stopTest();

}
}