src/objects/Applications__c.object
<CustomObject>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RAD_Exception_Log__c.object
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <label>Exception Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/objects/Wait_List_Selection__c.object
<CustomObject>
    <label>Wait List Selection</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait List Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_PubHsgPrintLblBatch.cls
//This class is used for notifying the section 8 applicants via pdf with cover letter or email

global class RAD_PubHsgPrintLblBatch implements Database.batchable<sObject>,Database.Stateful{
    String query;
    String wlsIdd;
      
    public  Static string todayp {get;set;}
    
    global  RAD_PubHsgPrintLblBatch(String wlsId)
    {
        wlsIdd = wlsId;

        query='Select name from Wait_List_Selection__c where id =:wlsIdd';              
              system.debug('RAD_Sec8SelctdNtfyBatch strQuery------->'+query);               
       
    }

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Wait_List_Selection__c> scope)
    {
        List<Document> docList = new List<Document>();
        Document doc = new Document();

        Blob b = null;
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
        List<Messaging.SingleEmailMessage> emailLst = new List<Messaging.SingleEmailMessage>();
        Id PHlabelId = [select id from folder where name ='Public Housing Label'].Id;     
     
     
               
        PageReference pdf = null; 
            
        
        List<RAD_Exception_Log__c> excpLogs = new List<RAD_Exception_Log__c>();
        RAD_Exception_Log__c eLog = new RAD_Exception_Log__c();                               
 
          
           for(Wait_List_Selection__c sr :scope)    
           {
           
            pdf = Page.RAD_Public_Housing_Labels;           
            pdf.setRedirect(true);
            pdf.getParameters().put('id', sr.id);

            if(!Test.isRunningTest()){ 
            b = pdf.getContent();
            }                 
            doc = new Document();
            doc.name=Date.today().format() +'_'+ sr.Name +'.pdf';                 
            doc.body = b;
            doc.FolderId =PHlabelId;
            docList.add(doc);
            List<Database.SaveResult> docResultList   =  Database.insert(docList, false);   
            
                
               
    
    }
    }
    
    global void finish(Database.BatchableContext BC)
    {
        // Set Application Trigger on during run.
        SwitchTrigger__c AppTrigger = SwitchTrigger__c.getInstance('Applications__c');
        if(AppTrigger != Null) {
            AppTrigger.Active__c = true;
            update AppTrigger;
        }
            
        AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            from AsyncApexJob where Id =
            :BC.getJobId()];
         // Send an email to the Apex job's submitter notifying of job completion.  
          
         Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
         String[] toAddresses = new String[] {a.CreatedBy.Email};
         mail.setToAddresses(toAddresses);
    
    
        mail.setSubject('Public Housing Label Printing Completed.');
        mail.setPlainTextBody(
        'Batch Process has completed.'
      
        );
        
        try {
          Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        } catch(System.EmailException sme) {
          //DO NOTHING...
        }
    }            
}