src/objects/Applications__c.object
<CustomObject>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On List</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issued/Offer</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Refused</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/objects/Wait_List_Selection__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_at_LI_80__c</fullName>
        <label>Applicant at li-80</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Applicant_at_eli_30_75__c</fullName>
        <label>Applicant at eli-30 (75%)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Applicant_at_vli_50_25__c</fullName>
        <label>Applicant at vli-50 (25%)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bedroom_Size__c</fullName>
        <label>Bedroom Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancel_Run__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancel Run</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_vacancies_to_fill__c</fullName>
        <label>Number of vacancies to fill</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Current_Scheduler_Count__c</fullName>
        <label>Current Scheduler Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Scheduler_Count__c</fullName>
        <label>Scheduler Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Eli_Count__c</fullName>
        <label>Temp Eli Count</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Li_Count__c</fullName>
        <label>Temp Li Count</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Number_to_Select__c</fullName>
        <label>Temp Number to Select</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Vli_Count__c</fullName>
        <label>Temp Vli Count</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule_Time__c</fullName>
        <label>Schedule Time</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>12:00 AM</fullName>
                </value>
                <value>
                    <fullName>1:00 AM</fullName>
                </value>
                <value>
                    <fullName>2:00 AM</fullName>
                </value>
                <value>
                    <fullName>3:00 AM</fullName>
                </value>
                <value>
                    <fullName>4:00 AM</fullName>
                </value>
                <value>
                    <fullName>5:00 AM</fullName>
                </value>
                <value>
                    <fullName>6:00 AM</fullName>
                </value>
                <value>
                    <fullName>7:00 AM</fullName>
                </value>
                <value>
                    <fullName>8:00 AM</fullName>
                </value>
                <value>
                    <fullName>9:00 AM</fullName>
                </value>
                <value>
                    <fullName>10:00 AM</fullName>
                </value>
                <value>
                    <fullName>11:00 AM</fullName>
                </value>
                <value>
                    <fullName>12:00 PM</fullName>
                </value>
                <value>
                    <fullName>1:00 PM</fullName>
                </value>
                <value>
                    <fullName>2:00 PM</fullName>
                </value>
                <value>
                    <fullName>3:00 PM</fullName>
                </value>
                <value>
                    <fullName>4:00 PM</fullName>
                </value>
                <value>
                    <fullName>5:00 PM</fullName>
                </value>
                <value>
                    <fullName>6:00 PM</fullName>
                </value>
                <value>
                    <fullName>7:00 PM</fullName>
                </value>
                <value>
                    <fullName>8:00 PM</fullName>
                </value>
                <value>
                    <fullName>9:00 PM</fullName>
                </value>
                <value>
                    <fullName>10:00 PM</fullName>
                </value>
                <value>
                    <fullName>11:00 PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheduled_Date__c</fullName>
        <label>Scheduled Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait List Selections</relationshipLabel>
        <relationshipName>Wait_List_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Wait List Selection</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait List Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_WLTSelTrigHlprTest.cls
@isTest
public class RAD_WLTSelTrigHlprTest{

     public static testmethod void testWLS_Sec8(){
     
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
     
        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='Section 8' limit 1];
        Test.startTest();
        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        
        wls.Wait_List_Type__c = wlt.id;
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        
        wls.RAD_Temp_Eli_Count__c = 0;
        wls.RAD_Temp_Vli_Count__c = 0;
        wls.RAD_Temp_Li_Count__c = 0;
        wls.RAD_Current_Scheduler_Count__c =0;
        wls.RAD_Scheduler_Count__c =2;
        
        
        insert wls;
        
        wls.Applicant_at_eli_30_75__c = 2;
        wls.Applicant_at_vli_50_25__c = 1;
        wls.Applicant_at_LI_80__c     = 0;
        update wls;
        
        
        wls.Status__c = 'Scheduled';
        update wls;
        
        wls.RAD_Scheduler_Count__c = 1;
        update wls;
        
        
        Test.stopTest();
        
     }
     
     
     public static testmethod void testWLS_ModRhb(){
     
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;     
        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='Mod Rehab' limit 1];
        Test.startTest();
        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        
        wls.Wait_List_Type__c = wlt.id;
        wls.Bedroom_Size__c = 1;
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        
        wls.RAD_Temp_Number_to_Select__c = 0;
        wls.RAD_Current_Scheduler_Count__c =0;
        wls.RAD_Scheduler_Count__c =2;
        
        
        
        
        insert wls;
        
        wls.Applicant_at_eli_30_75__c = 0;
        wls.Applicant_at_vli_50_25__c = 0;
        wls.Applicant_at_LI_80__c     = 0;
        update wls;
        
        
        wls.Status__c = 'Scheduled';
        update wls;
        
        wls.RAD_Temp_Number_to_Select__c = 3;
        wls.RAD_Scheduler_Count__c = 1;
        update wls;
        
        
        Test.stopTest();
        
     }
     
     public static testmethod void testWLS_PubHsg(){
     
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
             
        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='Public Housing' limit 1];
        Test.startTest();
        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        
        wls.Wait_List_Type__c = wlt.id;
        wls.Bedroom_Size__c = 1;
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        
        wls.RAD_Temp_Eli_Count__c = 0;
        wls.RAD_Temp_Vli_Count__c = 0;
        wls.RAD_Temp_Li_Count__c = 0;
        wls.RAD_Current_Scheduler_Count__c =0;
        wls.RAD_Scheduler_Count__c =2;
        
        
        insert wls;
        
        wls.Applicant_at_eli_30_75__c = 2;
        wls.Applicant_at_vli_50_25__c = 1;
        wls.Applicant_at_LI_80__c     = 0;
        update wls;
        
        
        wls.Status__c = 'Scheduled';
        update wls;
        
        wls.RAD_Scheduler_Count__c = 1;
        update wls;
        
        
        Test.stopTest();
        
     }
     
     public static testmethod void testWLS_ProjBsd(){

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
        
        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='Project Based' limit 1];
        Test.startTest();
        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        
        wls.Wait_List_Type__c = wlt.id;
        wls.Bedroom_Size__c = 1;
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        
        wls.RAD_Temp_Eli_Count__c = 0;
        wls.RAD_Temp_Vli_Count__c = 0;
        wls.RAD_Temp_Li_Count__c = 0;
        wls.RAD_Current_Scheduler_Count__c =0;
        wls.RAD_Scheduler_Count__c =2;
        
        
        insert wls;
        
        wls.Applicant_at_eli_30_75__c = 2;
        wls.Applicant_at_vli_50_25__c = 1;
        wls.Applicant_at_LI_80__c     = 0;
        update wls;
        
        
        wls.Status__c = 'Scheduled';
        update wls;
        
        wls.RAD_Scheduler_Count__c = 1;
        update wls;
        
        
        Test.stopTest();
        
     }
     
     public static testmethod void testWLS_ProjSngl(){

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;

        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='Project Based Single' limit 1];
        Test.startTest();
        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        
        wls.Wait_List_Type__c = wlt.id;
        wls.Bedroom_Size__c = 1;
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        
        wls.RAD_Temp_Eli_Count__c = 0;
        wls.RAD_Temp_Vli_Count__c = 0;
        wls.RAD_Temp_Li_Count__c = 0;
        wls.RAD_Current_Scheduler_Count__c =0;
        wls.RAD_Scheduler_Count__c =2;
        
        
        insert wls;
        
        wls.Applicant_at_eli_30_75__c = 2;
        wls.Applicant_at_vli_50_25__c = 1;
        wls.Applicant_at_LI_80__c     = 0;
        update wls;
        
        
        wls.Status__c = 'Scheduled';
        update wls;
        
        wls.RAD_Scheduler_Count__c = 1;
        update wls;
        
        
        Test.stopTest();
        
     }
     
    public static testmethod void testWLS_Others(){

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;

        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='Section 8' limit 1];
        Test.startTest();

        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        
        wls.Wait_List_Type__c = wlt.id;
        
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        
        wls.RAD_Temp_Eli_Count__c = 0;
        wls.RAD_Temp_Vli_Count__c = 0;
        wls.RAD_Temp_Li_Count__c = 0;
        wls.RAD_Current_Scheduler_Count__c =0;
        wls.RAD_Scheduler_Count__c =null;
        wls.Cancel_Run__c =false;
        wls.Status__c = 'New';
        
        insert wls;
        wls.RAD_Scheduler_Count__c = Null;
        wls.Status__c = 'Scheduled';
        wls.Wait_List_Type__c = wlt.id;
        wls.Cancel_Run__c =true;
        update wls;
        
        
        
        
        Test.stopTest();
    }
      public static testmethod void NED(){

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
      
        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='NED' limit 1];
        Test.startTest();
        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        
        wls.Wait_List_Type__c = wlt.id;
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        //wls.Bedroom_Size__c = 1;
        wls.RAD_Temp_Eli_Count__c = 0;
        wls.RAD_Temp_Vli_Count__c = 0;
        wls.RAD_Temp_Li_Count__c = 0;
        wls.RAD_Current_Scheduler_Count__c =0;
        wls.RAD_Scheduler_Count__c =2;
        
        
        insert wls;
        
        wls.Applicant_at_eli_30_75__c = 2;
        wls.Applicant_at_vli_50_25__c = 1;
        wls.Applicant_at_LI_80__c     = 0;
        update wls;
        
        
        wls.Cancel_Run__c =false;
        wls.Status__c = 'Scheduled';
        update wls;
        
        wls.RAD_Scheduler_Count__c = 1;
        update wls;
        
        
        Test.stopTest();
        
     }
      public static testmethod void testWLS_Others_NED(){

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list; 

        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='NED' limit 1];
        Test.startTest();

        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        
        wls.Wait_List_Type__c = wlt.id;
        
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        //wls.Bedroom_Size__c = 1;
        wls.RAD_Temp_Eli_Count__c = 0;
        wls.RAD_Temp_Vli_Count__c = 0;
        wls.RAD_Temp_Li_Count__c = 0;
        wls.RAD_Current_Scheduler_Count__c =0;
        wls.RAD_Scheduler_Count__c =null;
       wls.Status__c = 'scheduled';
        
        
        insert wls;
       
        
        wls.Wait_List_Type__c = wlt.id;
        wls.Cancel_Run__c =true;
        update wls;
        
        wls.Cancel_Run__c =false;
        wls.Status__c = 'Scheduled';
        update wls;
        
        
        Test.stopTest();
    }
    public static testmethod void testWLS_Others_Public_Housing(){

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
        
        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='Public Housing' limit 1];
        Test.startTest();

        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        
        wls.Wait_List_Type__c = wlt.id;
        
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        wls.Bedroom_Size__c = 2;
        wls.RAD_Temp_Eli_Count__c = 0;
        wls.RAD_Temp_Vli_Count__c = 0;
        wls.RAD_Temp_Li_Count__c = 0;
        wls.RAD_Current_Scheduler_Count__c =0;
        wls.RAD_Scheduler_Count__c =null;
       wls.Status__c = 'scheduled';
        
        
        insert wls;
       
        
        wls.Wait_List_Type__c = wlt.id;
        wls.Cancel_Run__c =true;
        update wls;
        
        wls.Cancel_Run__c =false;
        wls.Status__c = 'Scheduled';
        update wls;
        
        
        Test.stopTest();
    }
      public static testmethod void testWLS_Others_Project_Based(){

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
        
        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='Project Based' limit 1];
        Test.startTest();

        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        
        wls.Wait_List_Type__c = wlt.id;
        
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        wls.Bedroom_Size__c = 2;
        wls.RAD_Temp_Eli_Count__c = 0;
        wls.RAD_Temp_Vli_Count__c = 0;
        wls.RAD_Temp_Li_Count__c = 0;
        wls.RAD_Current_Scheduler_Count__c =0;
        wls.RAD_Scheduler_Count__c =null;
       wls.Status__c = 'scheduled';
        
        
        insert wls;
       
        
        wls.Wait_List_Type__c = wlt.id;
        wls.Cancel_Run__c =true;
        update wls;
        
        wls.Cancel_Run__c =false;
        wls.Status__c = 'Scheduled';
        update wls;
        
        
        Test.stopTest();
    }
    public static testmethod void testWLS_Others_Project_Based_Single(){

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='Project Based Single' limit 1];
        Test.startTest();

        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        
        wls.Wait_List_Type__c = wlt.id;
        
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '4:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        wls.Bedroom_Size__c = 2;
        wls.RAD_Temp_Eli_Count__c = 0;
        wls.RAD_Temp_Vli_Count__c = 0;
        wls.RAD_Temp_Li_Count__c = 0;
        wls.RAD_Current_Scheduler_Count__c =0;
        wls.RAD_Scheduler_Count__c =null;
       wls.Status__c = 'scheduled';
        
        
        insert wls;
       
        
        wls.Wait_List_Type__c = wlt.id;
        wls.Cancel_Run__c =true;
        update wls;
        
        wls.Cancel_Run__c =false;
        wls.Status__c = 'Scheduled';
        update wls;
        
        
        Test.stopTest();
    }
     public static testmethod void testWLS_Others_Mod_Rehab(){

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
        
        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='Mod Rehab' limit 1];
        Test.startTest();

        Wait_List_Selection__c wls = new Wait_List_Selection__c();
        
        wls.Wait_List_Type__c = wlt.id;
        
        wls.Scheduled_Date__c = Date.Today()+1;
        wls.Schedule_Time__c = '1:00 PM';
        wls.Number_of_vacancies_to_fill__c=3;
        wls.Bedroom_Size__c = 2;
        wls.RAD_Temp_Eli_Count__c = 0;
        wls.RAD_Temp_Vli_Count__c = 0;
        wls.RAD_Temp_Li_Count__c = 0;
        wls.RAD_Current_Scheduler_Count__c =0;
        wls.RAD_Scheduler_Count__c =null;
       wls.Status__c = 'scheduled';
        
        
        insert wls;
       
        
        wls.Wait_List_Type__c = wlt.id;
        wls.Cancel_Run__c =true;
        update wls;
        
        wls.Cancel_Run__c =false;
        wls.Status__c = 'Scheduled';
        update wls;
        
        
        Test.stopTest();
    }
}