src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Live_Work_in_City_of_San_Diego__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Applicant lives or works within the City of San Diego</description>
        <label>Live/Work in City of San Diego</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RAD_Next_Purge_Request_Date__c</fullName>
        <label>Next Update Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Send_To_Boomi__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag is checked by Boomi to determine if a record is to be picked up and processed.</description>
        <inlineHelpText>If the box is checked, Boomi will pull the record on the next poll.  If the box is unchecked, Boomi will not pull the record.</inlineHelpText>
        <label>Send To Boomi</label>
        <type>Checkbox</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Memo__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Memos</relationshipLabel>
        <relationshipName>Memos_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DateTimeMilliseconds__c</fullName>
        <description>This stores the number of milliseconds since January 1 1970</description>
        <label>DateTimeMilliseconds</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_and_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ErrorMemoType__c</fullName>
        <description>This is used to determine the type of error that caused the need for a memo. From this we can send out the correct letter.</description>
        <label>ErrorMemoType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PurgeUpdateFailure</fullName>
                </value>
                <value>
                    <fullName>FieldUpdateEmailFailure</fullName>
                </value>
                <value>
                    <fullName>PurgeReminderFailure</fullName>
                </value>
                <value>
                    <fullName>PurgeEmailFailure</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>Showing</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>Rejection</fullName>
                </value>
                <value>
                    <fullName>Move in</fullName>
                </value>
                <value>
                    <fullName>Wait List</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>A-App Status(Not Lv/wk SD)</fullName>
                </value>
                <value>
                    <fullName>A1- Out our Jurisdiction</fullName>
                </value>
                <value>
                    <fullName>B-App Status(iv/wk SD)</fullName>
                </value>
                <value>
                    <fullName>C-App Trans Received</fullName>
                </value>
                <value>
                    <fullName>D- App Trans to County</fullName>
                </value>
                <value>
                    <fullName>D1-App National City</fullName>
                </value>
                <value>
                    <fullName>D2- App Oceanside</fullName>
                </value>
                <value>
                    <fullName>D3-App Carlsbad</fullName>
                </value>
                <value>
                    <fullName>D4-App Encinitas</fullName>
                </value>
                <value>
                    <fullName>Ltr1- WL Confirmation</fullName>
                </value>
                <value>
                    <fullName>Ltr4-WL NE State</fullName>
                </value>
                <value>
                    <fullName>LtrIT-WL Ineligible to Trans</fullName>
                </value>
                <value>
                    <fullName>LtrUT-WL Unable to Trans</fullName>
                </value>
                <value>
                    <fullName>Ltr7- WL Claim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_To_Boomi__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag is checked by Boomi to determine if a record is to be picked up and processed.</description>
        <inlineHelpText>If the box is checked, Boomi will pull the record on the next poll.  If the box is unchecked, Boomi will not pull the record.</inlineHelpText>
        <label>Send To Boomi</label>
        <type>Checkbox</type>
    </fields>
    <label>Memos</label>
    <nameField>
        <label>Memo Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RAD_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>RAD_Purge_Extension_Months__c</fullName>
        <description>Purge Extension in months</description>
        <label>Purge Extension(Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update_Duration_Months__c</fullName>
        <label>Update Duration (Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RAD Configuration</label>
    <nameField>
        <label>RAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MemosTriggerHandler.cls
public class MemosTriggerHandler extends TriggerHandler 
{	
    public MemosTriggerHandler() 
    {
      //this.setMaxLoopCount(1);
    }

    public override void beforeUpdate() 
    {
      for(Memo__c memo:(List<Memo__c>) Trigger.new)
        {
          if(!(UserInfo.getName() =='Dell Boomi'))
            memo.Send_To_Boomi__c=true;
        }
    }
    public override void afterUpdate()
    {
    
    }
    public override void beforeInsert() 
    {
      for(Memo__c memo:(List<Memo__c>) Trigger.new)
        {
          memo.DateTimeMilliseconds__c=String.valueOf(memo.Date_and_Time__c.getTime());
            if(!(UserInfo.getName() =='Dell Boomi'))
            memo.Send_To_Boomi__c=true;
        }
    
    }
    public override void afterInsert() 
    {
      List<Memo__c> lstMemos = [Select Id, Name, Result__c,Applications__r.Applicant__c, ErrorMemoType__c, Applications__r.Applicant__r.MailingAddress, Applications__r.Applicant__r.Email, Applications__r.Applicant__r.Paperless_Email_only__c from Memo__c where id  in : trigger.new];
       List<Messaging.SingleEmailMessage> emailLst = new List<Messaging.SingleEmailMessage>();
        EmailTemplate templateId_transfLett = [Select id from EmailTemplate where name ='Transfer Letters' LIMIT 1];
        if(lstMemos != NULL)
        { List<ID> letterList=new List<ID>();
          for(Memo__c memo: lstMemos)
          {
            if(memo.Applications__r.Applicant__r.Email!='' && memo.Applications__r.Applicant__r.Paperless_Email_only__c == True && (memo.Result__c == 'D1-App National City' || memo.Result__c == 'D2- App Oceanside') )
              {
          		  Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(templateId_transfLett.Id, memo.Applications__r.Applicant__c, memo.Id);
                  String[] toAddresses = new String[] {memo.Applications__r.Applicant__r.Email};
                  mail.setToAddresses(toAddresses);
                  
                    Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEMailMessage[] {mail});
                }
              if((memo.ErrorMemoType__c =='FieldUpdateEmailFailure')||(memo.ErrorMemoType__c =='PurgeReminderFailure')||(memo.ErrorMemoType__c =='PurgeUpdateFailure')){
                  letterList.add(memo.id);
              }  
              
          
      }
         if(letterList.size()>0){
             createLetters(letterList);
         }      
    }
    }
    
    public override void beforeDelete() 
    {
    
    }
    public override void afterDelete() 
    {
    
    }
    public override void afterUndelete()
    {
    
    }
    @future(callout=true)
    public static void createLetters(List<ID> memoIDList){
        //This takes a list of memos, and creates letters for those clients
        List<Document> docList = new List<Document>();
        List<memo__c> memoList = new List<Memo__c>([SELECT Id, ErrorMemoType__c, Applications__r.RAD_Next_Purge_Request_Date__c, Applications__r.Applicant__r.age1__c, Applications__r.id, Applications__r.name, Applications__r.Live_Work_in_City_of_San_Diego__c FROM Memo__c WHERE id in :memoIDList]);
        Document doc = new Document();
        Blob b = null;
        Id folderWeeklyStatusId;
        Id folderWeeklyUpdateId;
        for(Folder f:[select id, name from folder where name IN ('RAD Wait List - Status Letter','Update Letter')]){
            if(f.name == 'RAD Wait List - Status Letter')
                folderWeeklyStatusId = f.Id;
            else if (f.name == 'Update Letter')
            	folderWeeklyUpdateId = f.Id;
        }                               
        
        PageReference pdf = null;  
        RAD_Configuration__c cnfg = [select Update_Duration_Months__c, RAD_Purge_Extension_Months__c from  RAD_Configuration__c where name = 'Main Configurations' limit 1];        
        Integer extnMonths = Integer.valueOf(cnfg.RAD_Purge_Extension_Months__c);
        for(Memo__c memo:memoList){
            if(memo.ErrorMemoType__c=='FieldUpdateEmailFailure'){
                if(memo.Applications__r.Live_Work_in_City_of_San_Diego__c){
                    pdf = Page.RAD_WeeklyUpdatePDF_SD;                                             
                }
                else{
                    pdf = Page.RAD_WeeklyUpdatePDF_NONSD;     
                }
                pdf.setRedirect(true);
                pdf.getParameters().put('id', memo.Applications__r.id);
                if (!Test.IsRunningTest()) 
                {
                    b = pdf.getContent(); 
                }    
                
                
                doc = new Document();
                
                doc.name = memo.Applications__r.name+'_'+Date.Today()+'.pdf';
                doc.body = b;
                
                doc.FolderId =folderWeeklyStatusId;
                docList.add(doc); 
        	}
        	else if (memo.ErrorMemoType__c=='PurgeUpdateFailure'){
                if(memo.Applications__r.Applicant__r.age1__c>62){
                    pdf = Page.RAD_PurgeUpdtReqEld;                                             
                }
                else{
                    pdf = Page.RAD_PurgeUpdtReqNonEld;     
                }
                pdf.setRedirect(true);
                pdf.getParameters().put('id', memo.Applications__r.id);
                if (!Test.IsRunningTest()) 
                {
                    b = pdf.getContent(); 
                }    
                
                
                doc = new Document();
                
                doc.name = 'ReApply before '+ memo.applications__r.RAD_Next_Purge_Request_Date__c.addMonths(extnMonths) +': '+ memo.applications__r.Name +'.pdf';
                doc.body = b;
                
                doc.FolderId =folderWeeklyStatusId;
                docList.add(doc); 
            
        	}
        	else if (memo.ErrorMemoType__c=='PurgeReminderFailure'){
                if(memo.Applications__r.Applicant__r.age1__c>62){
                    pdf = Page.RAD_PurgeFinlRemndrEld;                                             
                }
                else{
                    pdf = Page.RAD_PurgeFinlRemndrNonEld;     
                }
                pdf.setRedirect(true);
                pdf.getParameters().put('id', memo.Applications__r.id);
                if (!Test.IsRunningTest()) 
                {
                    b = pdf.getContent(); 
                }    
                
                
                doc = new Document();
                
                doc.name = 'ReApply before '+ memo.applications__r.RAD_Next_Purge_Request_Date__c.addMonths(extnMonths) +': '+ memo.applications__r.Name +'.pdf';
                doc.body = b;
                
                doc.FolderId =folderWeeklyStatusId;
                docList.add(doc); 
            
        	}
        }
        try{
        	List<Database.SaveResult> docResultList   =  Database.insert(docList, false);
        }
        catch(Exception e)
        {
            System.debug('Failed to insert memo documents: '+ e);
        }
    }
}