src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Paperless_Email_only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paperless/Email only:</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>Rental Assistance Wait List Portal Record Type</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On List</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issued/Offer</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Refused</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RAD_Exception_Log__c.object
<CustomObject>
    <fields>
        <fullName>RAD_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RAD_Error_Source__c</fullName>
        <label>Error Source</label>
        <type>TextArea</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <label>Exception Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Selection_Records__c.object
<CustomObject>
    <fields>
        <fullName>RAD_Wait_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List</label>
        <referenceTo>Enrolled_Wait_List__c</referenceTo>
        <relationshipLabel>Selection Records</relationshipLabel>
        <relationshipName>Selection_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selection_ID__c</fullName>
        <label>Wait List Selection</label>
        <referenceTo>Wait_List_Selection__c</referenceTo>
        <relationshipLabel>Selection Records</relationshipLabel>
        <relationshipName>Selection_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Selection Record</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selection Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_MRSelctdNtfyBatch.cls
//This class is used for notifying the MRapplicants via pdf with cover letter or email

global class RAD_MRSelctdNtfyBatch implements Database.batchable<sObject>,Database.Stateful{
    String query;
    String wlsIdd;
    
    global RAD_MRSelctdNtfyBatch(String wlsId)
    {

        wlsIdd = wlsId;

        query  = 'Select RAD_Wait_List__c, RAD_Wait_List__r.Name, '+
                 ' RAD_Wait_List__r.Applications__c,RAD_Wait_List__r.Applications__r.Name,RAD_Wait_List__r.Applications__r.Applicant__c, '+
                 ' RAD_Wait_List__r.Applications__r.Applicant__r.Name,RAD_Wait_List__r.Applications__r.Applicant__r.Email, '+
                 ' RAD_Wait_List__r.Applications__r.Applicant__r.Paperless_Email_only__c'+
                 ' from Selection_Records__c where Selection_ID__c =:wlsIdd and Status__c=\'Selected\' and RAD_Wait_List__r.Wait_List_Type__r.Name =\'Mod Rehab\'';

                system.debug('RAD_MRSelctdNtfyBatch strQuery------->'+query);               
       
    }

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Selection_Records__c> scope)
    {
        List<Document> docList = new List<Document>();
        Document doc = new Document();
        Document doc1 = new Document();
        Blob b = null;
        /*Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
        List<Messaging.SingleEmailMessage> emailLst = new List<Messaging.SingleEmailMessage>(); */
        Id sec8FolderId;
        if(!Test.isRunningTest()){
            sec8FolderId = [select id from folder where name ='Intake Appointment - MR'].Id;
        }
        String fName= '';
               
       /* EmailTemplate templateId = [Select id from EmailTemplate where name ='NEDNotification']; */
               
        PageReference pdf = null; 
              
        
        List<RAD_Exception_Log__c> excpLogs = new List<RAD_Exception_Log__c>();
        RAD_Exception_Log__c eLog = new RAD_Exception_Log__c();                               
 
          
           for(Selection_Records__c sr :scope)    
           {
                
                if(sr.RAD_Wait_List__r.Applications__r.Applicant__c == null){
                    continue;
                }
                
               /* if( String.isBlank(sr.RAD_Wait_List__r.Applications__r.Applicant__r.Email) && sr.RAD_Wait_List__r.Applications__r.Applicant__r.Paperless_Email_only__c == false ){ */ 
            
                    pdf = Page.RAD_PDF_MRNotification;           
                    pdf.setRedirect(true);
                    pdf.getParameters().put('id', sr.RAD_Wait_List__r.id);
                    if(!Test.isRunningTest()){ 
                        b = pdf.getContent();
                    }   

                    
                    doc = new Document();
                    fName = sr.RAD_Wait_List__r.Applications__r.Name + '_Intake Appointment - MR.pdf';
                    //System.debug('The file name is '+ fName);
                    doc.name = fName;
                   
                    doc.body = b;
                    if(!Test.isRunningTest()){
                        doc.FolderId =sec8FolderId ;
                    }
                    docList.add(doc);
                    
                
           /*} */
            
               /*else if( String.isNotBlank(sr.RAD_Wait_List__r.Applications__r.Applicant__r.Email) ){
                    email = new Messaging.SingleEmailMessage(); 
                    email.setTemplateID(templateId.Id);
                    email.setTargetObjectId (sr.RAD_Wait_List__r.Applications__r.Applicant__c);//sending to applicant
                    emailLst.add(email);
                } */
                //DO NOTHING
     
       } 

        //totalNEDCount += scope.size(); 
        //totalsection8DocCnt += docList.size();
        // send these count to the batch submitter
    
    
        if(!docList.isEmpty()){
            List<Database.SaveResult> docResultList   =  Database.insert(docList, false);
            for(Integer i=0;i<docResultList.size();i++){
                
                    if(!docResultList[i].isSuccess()){
                         eLog = new RAD_Exception_Log__c();
                         eLog.RAD_Error_Source__c = 'Batch Error when processing MR selection letter';
                         eLog.RAD_Error_Message__c = 'Creating Selection Record: '+docResultList[i].getErrors();
        
                         excpLogs.add(eLog);
                    }
                
            }
        }
            
        if(!excpLogs.isEmpty()){
                Database.insert(excpLogs, false);
        }

  /*  Messaging.SendEmailResult [] results = Messaging.sendEmail(emailLst, false); */
   //TODO find out how many failed/email bounced, and put them
    //CHK FOR BOUNCED MESSAGE
    
    }
    
    global void finish(Database.BatchableContext BC)
    {
        AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            from AsyncApexJob where Id =
            :BC.getJobId()];
         // Send an email to the Apex job's submitter notifying of job completion.  
          
         Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
         String[] toAddresses = new String[] {a.CreatedBy.Email};
         mail.setToAddresses(toAddresses);
    
    
        mail.setSubject('Rental Assistance MR Notification Completed');
        mail.setPlainTextBody(
        'Batch Process has completed.'
      
        );
        
        try {
          Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        } catch(System.EmailException sme) {
          //DO NOTHING...
        }
    }            
}