src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Update Required</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>On List</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RAD_Next_Purge_Date__c</fullName>
        <description>This is informational field, which will store the end date of Grace Period.</description>
        <label>Grace Period End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RAD_Next_Purge_Request_Date__c</fullName>
        <label>Next Update Request Date</label>
        <type>DateTime</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age1__c</fullName>
        <formula>IF( NOT( ISBLANK(Date_of_Birth__c) ) , 
IF( DATE( 2000 , MONTH( Date_of_Birth__c ) , DAY( Date_of_Birth__c ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ), 
YEAR (Today()) - YEAR (Date_of_Birth__c), 
YEAR (Today()) - YEAR ( Date_of_Birth__c ) -1 ), 
null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Paperless_Email_only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paperless/Email only:</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>Rental Assistance Wait List Portal Record Type</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onlist</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issue/Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Memo__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Memos</relationshipLabel>
        <relationshipName>Memos_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ErrorMemoType__c</fullName>
        <description>This is used to determine the type of error that caused the need for a memo. From this we can send out the correct letter.</description>
        <label>ErrorMemoType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PurgeUpdateFailure</fullName>
                </value>
                <value>
                    <fullName>FieldUpdateEmailFailure</fullName>
                </value>
                <value>
                    <fullName>PurgeReminderFailure</fullName>
                </value>
                <value>
                    <fullName>PurgeEmailFailure</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes / Desc</label>
        <length>1998</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>Showing</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>Rejection</fullName>
                </value>
                <value>
                    <fullName>Move in</fullName>
                </value>
                <value>
                    <fullName>Wait List</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>Entity Alert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Memos</label>
    <nameField>
        <label>Memo Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RAD_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>RAD_Purge_Extension_Months__c</fullName>
        <description>Purge Extension in months</description>
        <label>Purge Extension(Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update_Duration_Months__c</fullName>
        <label>Update Duration (Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RAD Configuration</label>
    <nameField>
        <label>RAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RAD_Exception_Log__c.object
<CustomObject>
    <fields>
        <fullName>RAD_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RAD_Error_Source__c</fullName>
        <label>Error Source</label>
        <type>TextArea</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <label>Exception Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_DailyBatchToPurge.cls
//ENSURE FOLDER EXIST BEFORE EXECUTING THE BATCH
//System assumes 
global class RAD_DailyBatchToPurge implements Database.batchable<sObject>,Database.Stateful{
    String query;
    global Integer totalPurgeCount;
    global Integer unprocessedCount;
    global Integer totalPurgeReqDocCnt;
    global String updateFolderId;
    global String reminderFolderId;
    


    global RAD_DailyBatchToPurge ()
    {

        
        query = 'Select ID,Name, RAD_Next_Purge_Request_Date__c , RAD_Next_Purge_Date__c, '+ 
                    ' Applicant__c, applicant__r.EmailBouncedDate, Applicant__r.Email, Applicant__r.Paperless_Email_only__c, Applicant__r.Age1__c, '+
                    ' Application_Status__c, (Select ID, Current_Status__c  From Enrolled_Wait_Lists__r  where Current_Status__c =\'Onlist\' ) from Applications__c '+ 
                    ' where RAD_Next_Purge_Request_Date__c < = TODAY and '+
                    ' Application_Status__c in (\'Update Required\',\'Submitted\') '+
                    ' limit 29 ' ;
        system.debug(' Purge query ' +query );
        
        //removed ,\'Update Required\' from the query
                    
        updateFolderId = null;
        reminderFolderId = null;
        
        for(Folder fldr : [select id,name  from folder where name in ('Update Letter', 'Reminder Letter') ]){
            if( fldr.name == 'Update Letter' ){
                updateFolderId = fldr.id;
            }
            if(fldr.name == 'Reminder Letter'){
                reminderFolderId = fldr.id;
            }
        }
        
        totalPurgeCount = 0;
        unprocessedCount = 0;
        totalPurgeReqDocCnt = 0;
       
        
    }

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Applications__c> scope)
    {
        List<Document> docList = new List<Document>();
        Document doc = new Document();
        Blob b = null;
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
        List<Messaging.SingleEmailMessage> emailLst = new List<Messaging.SingleEmailMessage>();
        //Id folderReApplyId = [select id from folder where name ='Re-Apply Notification'].Id;
        

       
        EmailTemplate templateId = [Select id from EmailTemplate where name = 'Re-ApplyUpdateNotification'];
        
        PageReference pdf = null;        
        
        RAD_Configuration__c cnfg = [select Update_Duration_Months__c, RAD_Purge_Extension_Months__c from  RAD_Configuration__c where name = 'Main Configurations' limit 1];
        Integer extnMonths = Integer.valueOf(cnfg.RAD_Purge_Extension_Months__c);
        
        List<Memo__c> memoLst = new List<Memo__c>();
        Memo__c mmo = new Memo__c();
        
        List<Enrolled_Wait_List__c> wls2Updt = new List<Enrolled_Wait_List__c>();
        Map<Id,Applications__c> appMap = new Map<Id, Applications__c>();
        for(Applications__c appl :scope){
            appMap.put(appl.id, appl);
            //if appl has wl with onlist
            List<Enrolled_Wait_List__c> wls = appl.Enrolled_Wait_Lists__r;
            
            if(appl.Applicant__c == null){
                continue;
            }
            System.debug('appplication is '+appl);
            //if exceeding the final purge date, make appl +wl status Removed, clear off the next purge and next purge req date
            
            
            if( Datetime.Now() > (appl.RAD_Next_Purge_Request_Date__c.addMonths(extnMonths))){
                appl.Application_Status__c = 'Removed';
                appl.RAD_Next_Purge_Request_Date__c = null;
                appl.RAD_Next_Purge_Date__c = null;
                
                for(Enrolled_Wait_List__c wl : wls){
                    wl.Current_Status__c = 'Removed';
                    wls2Updt.add(wl);
                }

                
             //else today has just crossed purge request date, update Submitted application, keep the WL as is   
            }else if( Datetime.Now() >= (appl.RAD_Next_Purge_Request_Date__c ) && appl.Application_Status__c == 'Submitted' ){
                system.debug(' $$$$ Condition 2' +appl.id   +( Datetime.Now() >= (appl.RAD_Next_Purge_Request_Date__c ) && appl.Application_Status__c == 'Submitted' ) );
                appl.Application_Status__c = 'Update Required';
                
                //CREATE MEMO 
                
                
                if( String.isBlank(appl.Applicant__r.Email) && appl.Applicant__r.Paperless_Email_only__c == false ){
                
                    //pdf = Page.RAD_PDF_ReApplyUpdateNotification;           
                    if(appl.Applicant__r.Age1__c > 62){
                        pdf = Page.RAD_PurgeUpdtReqEld;           
                    }else{
                        pdf = Page.RAD_PurgeUpdtReqNonEld;           
                    }
                    pdf.setRedirect(true);
                    pdf.getParameters().put('id', appl.id);
                    if (!Test.IsRunningTest()) 
                    {
                      b = pdf.getContent();
                    }
                    doc = new Document();
                    doc.name = 'ReApply before '+ appl.RAD_Next_Purge_Request_Date__c.addMonths(extnMonths) +': '+ appl.Name +'.pdf';
                    doc.body = b;
                    doc.FolderId = updateFolderId ;
                    docList.add(doc);
                    
                    mmo = new Memo__c();
                    //mmo.Subject__c = 'Update letter sent';
                    mmo.Name = 'Update letter sent';
                    mmo.Type__c = 'Wait List';
                    mmo.Notes__c = 'System Generated Memo';
                    mmo.Applications__c = appl.id;
                    memoLst.add(mmo);
                
                }else if(  String.isNotBlank(appl.Applicant__r.Email) ){
                    if(appl.applicant__r.EmailBouncedDate==null){    
                        email = new Messaging.SingleEmailMessage(); 
                        
                        if(appl.Applicant__r.Age1__c > 62){
                            email.setTemplateID(templateId.Id);
                        }else{
                            email.setTemplateID(templateId.Id);
                        }
                        String [] toAddresses = new String[] {appl.Applicant__r.Email};
                        System.debug('rhathi sending to '+appl.Applicant__r.Email);
                        //email.setSubject('ReApply Notification');
                        //email.setToAddresses(toAddresses);
                        //email.setTargetObjectId ('003r0000006B9yw');//sending to myself...should be applicant
                        
                        email.setTargetObjectId (appl.Applicant__c);//sending to applicant
                        //email.setWhatId(appl.id); //Your Record Id if applicable
                        //email.setorgWideEmailAddressId('0D2r00000004Cr5');
    
    
                        emailLst.add(email);
                        
                        mmo = new Memo__c();
                        //mmo.Subject__c = 'Update email sent';
                        mmo.Name = 'Update email sent';
                        mmo.Type__c = 'Wait List';
                        mmo.Notes__c = 'System Generated Memo';
                        mmo.Applications__c = appl.id;
                        memoLst.add(mmo);
                	}
                    else{
                        //Bounced email -- so create memo that sends letter
                    	
                        memoLst.add(createMemo(appl, 'BounceUpdate'));
                    }
                }else{
                    //DO NOTHING
                }
            }else if( (Date.Today() == (appl.RAD_Next_Purge_Date__c).addDays(-10).date() ) && appl.Application_Status__c == 'Update Required' ){
                
                //CREATE MEMO ???check with Ajay for reminder

                
                if( String.isBlank(appl.Applicant__r.Email) && appl.Applicant__r.Paperless_Email_only__c == false ){
                    
                    System.debug('rhathi sending reminder');                
                    
                    //pdf = Page.RAD_PDF_ReApplyUpdateNotification;           
                    if(appl.Applicant__r.Age1__c > 62){
                        pdf = Page.RAD_PurgeFinlRemndrEld;           
                    }else{
                        pdf = Page.RAD_PurgeFinlRemndrNonEld;           
                    }
                    pdf.setRedirect(true);
                    pdf.getParameters().put('id', appl.id);
                    if (!Test.IsRunningTest()) 
                    {
                      b = pdf.getContent();
                    }
                    
                    doc = new Document();
                    doc.name = 'Final Reminder : '+ appl.Name +'.pdf';
                    doc.body = b;
                    doc.FolderId = reminderFolderId;
                    docList.add(doc);
                    
                    mmo = new Memo__c();
                    //mmo.Subject__c = 'Update letter sent';
                    mmo.Name = 'Update letter sent';
                    mmo.Type__c = 'Wait List';
                    mmo.Notes__c = 'System Generated Memo';
                    mmo.Applications__c = appl.id;
                    memoLst.add(mmo);
                
                }else if(  String.isNotBlank(appl.Applicant__r.Email) ){
                    if(appl.applicant__r.EmailBouncedDate==null){
                        email = new Messaging.SingleEmailMessage(); 
                        
                        if(appl.Applicant__r.Age1__c > 62){
                            email.setTemplateID(templateId.Id);
                        }else{
                            email.setTemplateID(templateId.Id);
                        }
                        String [] toAddresses = new String[] {appl.Applicant__r.Email};
                        System.debug('rhathi sending to '+appl.Applicant__r.Email);
                        //email.setSubject('ReApply Notification');
                        //email.setToAddresses(toAddresses);
                        //email.setTargetObjectId ('003r0000006B9yw');//sending to myself...should be applicant
                        
                        email.setTargetObjectId (appl.Applicant__c);//sending to applicant
                        //email.setWhatId(appl.id); //Your Record Id if applicable
                        //email.setorgWideEmailAddressId('0D2r00000004Cr5');
    
    
                        emailLst.add(email);
                        
                        mmo = new Memo__c();
                        //mmo.Subject__c = 'Update email sent';
                        mmo.Name = 'Update email sent';
                        mmo.Type__c = 'Wait List';
                        mmo.Notes__c = 'System Generated Memo';
                        mmo.Applications__c = appl.id;
                        memoLst.add(mmo);
                    }
                    else{
                        
                        //Bounced email -- so create memo
                    	
                        memoLst.add(createMemo(appl, 'BounceReminder'));
                       
                    }
                }else{
                    //DO NOTHING
                }
            }
        }//for        
       totalPurgeCount += scope.size(); 
       totalPurgeReqDocCnt += docList.size();
        List<Database.SaveResult> applnResultList =  Database.update(scope, false);
        system.debug('$$$$ updating ApplicationRecords ' +scope );
        List<Database.SaveResult> wlResultList =  Database.update(wls2Updt, false);
        List<Database.SaveResult> docResultList   =  Database.insert(docList, false);
        Messaging.SendEmailResult [] results = Messaging.sendEmail(emailLst, false);
        List<Database.SaveResult> memoResultLst =  Database.insert(memoLst, false);
        
        if (!results.isEmpty() && !results.get(0).isSuccess()) {
            System.StatusCode statusCode = results.get(0).getErrors()[0].getStatusCode();
            String errorMessage = results.get(0).getErrors()[0].getMessage();
            System.debug('error message '+errorMessage);
             RAD_Exception_Log__c eLog = new RAD_Exception_Log__c();
            eLog.RAD_Error_Source__c = 'email error';
            eLog.RAD_Error_Message__c = errorMessage ;
            insert elog;
            //Iterate through results here and create memos for failure
            for(Messaging.SendEmailResult res:results){
            	if (!res.success) 
                {   //Go through the results and set up memos for failed emails
                    if(appMap.get(res.getErrors()[0].getTargetObjectId()).Application_Status__c=='Submitted')
                        createMemo((appMap.get(res.getErrors()[0].getTargetObjectId())), 'PurgeReminderFailure ');
                    else if(appMap.get(res.getErrors()[0].getTargetObjectId()).Application_Status__c=='Update Required')
                        createMemo(appMap.get(res.getErrors()[0].getTargetObjectId()), 'PurgeUpdateFailure ');
                }
            }
        }   
 
        
        
    }
    
    global void finish(Database.BatchableContext BC)
    {
        AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            from AsyncApexJob where Id =
            :BC.getJobId()];
         // Send an email to the Apex job's submitter notifying of job completion.  
          
         Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
         String[] toAddresses = new String[] {a.CreatedBy.Email};
         mail.setToAddresses(toAddresses);
    
    
        mail.setSubject('Rental Assistance Purge Batch Completed');
        mail.setPlainTextBody(
        'Batch Process has completed.'+
        '\nTotal Application(s) for Processing: '+totalPurgeCount+
        '\nTotal Purge Document loaded: '+totalPurgeReqDocCnt 
        
        );
        
        try {
          Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        } catch(System.EmailException sme) {
          //DO NOTHING...
        }
    }            
    public static Memo__c createMemo(applications__c app, String type){
        Memo__c mmo = new Memo__c();
        if(type=='BounceUpdate'){
            mmo.Subject__c = 'Email bounce from Purge Update';
            mmo.Name = 'Email bounce from Purge Update';
			mmo.ErrorMemoType__c='PurgeUpdateFailure';
        }
        else if (type=='BounceReminder'){
            mmo.Subject__c = 'Email bounce from Purge Reminder';
            mmo.Name = 'Email bounce from Purge Reminder';
            mmo.ErrorMemoType__c='PurgeReminderFailure';
        }
        else if (type=='PurgeReminderEmail'){
            mmo.Subject__c = 'Email failure from Purge Reminder';
            mmo.Name = 'Email failure from Purge Reminder';
            mmo.ErrorMemoType__c='PurgeReminderFailure';
        }
        else if (type=='PurgeUpdateEmail'){
            mmo.Subject__c = 'Email failure from Purge Update';
            mmo.Name = 'Email failure from Purge Update';
            mmo.ErrorMemoType__c='PurgeUpdateFailure';
        }
        mmo.Type__c = 'Wait List';
        mmo.Notes__c = 'System Generated Memo';
        mmo.Applications__c = app.id;
        
        return mmo;
    }

}