src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applied_Date_time__c</fullName>
        <description>Applied Date/time on Application to map to Yardi Applied Date</description>
        <inlineHelpText>Applied Date/time</inlineHelpText>
        <label>Applied Date/time</label>
        <type>DateTime</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bed_size__c</fullName>
        <label>Bed size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onlist</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issue/Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lottery__c</fullName>
        <label>Lottery</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prefernce_Point__c</fullName>
        <label>Preference Point</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RAD_Exception_Log__c.object
<CustomObject>
    <fields>
        <fullName>RAD_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RAD_Error_Source__c</fullName>
        <label>Error Source</label>
        <type>TextArea</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <label>Exception Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/objects/Wait_List_Selection__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_at_LI_80__c</fullName>
        <label>Applicant at li-80</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Applicant_at_eli_30_75__c</fullName>
        <label>Applicant at eli-30 (75%)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Applicant_at_vli_50_25__c</fullName>
        <label>Applicant at vli-50 (25%)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bedroom_Size__c</fullName>
        <label>Bedroom Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_vacancies_to_fill__c</fullName>
        <label>Number of vacancies to fill</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_to_Select_from_List__c</fullName>
        <formula>CEILING (Number_of_vacancies_to_fill__c * (100 / VALUE( Wait_List_Type__r.Lease_Up__c ) ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number to Select from List</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Current_Scheduler_Count__c</fullName>
        <label>Current Scheduler Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Scheduler_Count__c</fullName>
        <label>Scheduler Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Eli_Count__c</fullName>
        <label>Temp Eli Count</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Li_Count__c</fullName>
        <label>Temp Li Count</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Number_to_Select__c</fullName>
        <label>Temp Number to Select</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Vli_Count__c</fullName>
        <label>Temp Vli Count</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait List Selections</relationshipLabel>
        <relationshipName>Wait_List_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Wait List Selection</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait List Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_PBSSeln_Batch.cls
//This class generates random number for lottery selection for onlist Proj Based Single WL for the default bedroom count of 1 and 
//counts the wl records for processing.

global class RAD_PBSSeln_Batch implements Database.batchable<sObject>,Database.Stateful{
    String query;
     global Set<String> rannumset; 
     global String wlsidd;
     global Decimal totalRecordCount;
     global Decimal eli;
     global Decimal vli;
     global Decimal li;
     global Decimal schrcount;
    
    
    global RAD_PBSSeln_Batch(string wlsid){
    
    wlsidd=wlsid;
    rannumset=new Set<String>(); 

    totalRecordCount = 0;
        
        query = 'Select ID, Lottery__c ' +
                ' from Enrolled_Wait_List__c where CreatedDate >= 2018-07-19T19:12:41.000+0000 and Bed_size__c=1 and  Current_Status__c = \'Onlist\' and Wait_List_Type__r.Name =\'Project Based Single\' '+
                ' order by Prefernce_Point__c desc,Applications__r.Applied_Date_time__c asc' ;                               
        
        
        system.debug('Query is-----'+ query); 
    
    }
    
    
    global  Database.QueryLocator start(Database.BatchableContext BC)
        
    {
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Enrolled_Wait_List__c> scope)    
    {
    
     List<RAD_Exception_Log__c> excpLogs = new List<RAD_Exception_Log__c>();
        RAD_Exception_Log__c eLog = new RAD_Exception_Log__c();
        
        System.debug('chk scope '+scope.size());
        
        String str ='';
        String randomNumber = '';
        for(Enrolled_Wait_List__c wl : scope )    
        {
            
            
            str = String.valueof(Math.abs(Crypto.getRandomLong()));
            randomNumber = str.substring(0,6);
            

            while(ranNumSet.contains(randomNumber) == true ){

            str = String.valueof(Math.abs(Crypto.getRandomLong()));
            randomNumber = str.substring(0,6);
            
            }
            
            wl.Lottery__c =Integer.valueof(randomNumber);
            ranNumSet.add(randomNumber);
            
            
            
        } 
        
        
        if(!scope.isEmpty()){
        
            totalRecordCount += scope.size(); 
            
            List<Database.SaveResult> wlResultList = Database.update(scope, false);
            for(Integer i=0;i<wlResultList.size();i++){
            
                if(!wlResultList[i].isSuccess()){
                     eLog = new RAD_Exception_Log__c();
                     eLog.RAD_Error_Source__c = 'Error when updating lottery number on WL-Project Based Single: '+ scope[i].id ;
                     eLog.RAD_Error_Message__c = 'Lottery Number Generation -PBV: '+wlResultList[i].getErrors();
    
                     excpLogs.add(eLog);
                }
            
            }
        }
        
        
        
        if(!excpLogs.isEmpty()){
            Database.insert(excpLogs, false);
        }    
    


        //system.debug(totalRecordCount); 
        //system.debug('set size is--->'+rannumset.size());
        //system.debug(rannumset);
        

    } 
    
        
       
    global void finish(Database.BatchableContext BC)     
    {    
        // Set Application Trigger on during run.
        SwitchTrigger__c AppTrigger = SwitchTrigger__c.getInstance('Applications__c');
        if(AppTrigger != Null) {
            AppTrigger.Active__c = false;
            update AppTrigger;
        }    
        Wait_List_Selection__c  wls = [Select Applicant_at_eli_30_75__c, Applicant_at_vli_50_25__c, Applicant_at_LI_80__c, Bedroom_Size__c, RAD_Temp_Number_to_Select__c,
                                     Number_of_vacancies_to_fill__c,RAD_Scheduler_Count__c,RAD_Temp_Eli_Count__c,RAD_Temp_Vli_Count__c,RAD_Current_Scheduler_Count__c, RAD_Temp_Li_Count__c, Number_to_Select_from_List__c, Wait_List_Type__r.Id, Wait_List_Type__r.Name 
                                     from Wait_List_Selection__c where id =:wlsidd limit 1];
                                     
        
        wls.RAD_Temp_Eli_Count__c = wls.Applicant_at_eli_30_75__c==null?0:wls.Applicant_at_eli_30_75__c;
        wls.RAD_Temp_Vli_Count__c = wls.Applicant_at_vli_50_25__c==null?0:wls.Applicant_at_vli_50_25__c;
        wls.RAD_Temp_Li_Count__c  = wls.Applicant_at_LI_80__c==null?0:wls.Applicant_at_LI_80__c; 
        
        wls.RAD_Scheduler_Count__c = totalRecordCount.divide(1000, 0, System.RoundingMode.UP);
        wls.RAD_Current_Scheduler_Count__c = 0; 
        

        system.debug('schedular count is'+wls.RAD_Scheduler_Count__c); 
        
        Database.update(wls, false);
                                                                                   
          
    }            
    
}