src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>American_Indian__c</fullName>
        <defaultValue>false</defaultValue>
        <label>American Indian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Applied_Date_time__c</fullName>
        <description>Applied Date/time on Application to map to Yardi Applied Date</description>
        <inlineHelpText>Applied Date/time</inlineHelpText>
        <label>Applied Date/time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Asian__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Black__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Black</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Not Hispanic or Latino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Annual_Income__c</fullName>
        <label>Family Annual Income</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pacific_Islander__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pacific Islander</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <label>Social Security Number1</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_People__c</fullName>
        <label>Total People</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>White__c</fullName>
        <defaultValue>false</defaultValue>
        <label>White</label>
        <type>Checkbox</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Code__c</fullName>
        <label>Property Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prospect_Number_YARDI__c</fullName>
        <label>Prospect Number(YARDI)</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SSN_TaxID__c</fullName>
        <label>SSN / TaxID</label>
        <length>15</length>
        <maskChar>asterisk</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Tenant_Number_YARDI__c</fullName>
        <label>Tenant Number (YARDI)</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bed_size__c</fullName>
        <label>Bed size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onlist</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issue/Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prefernce_Point__c</fullName>
        <label>Preference Point</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_Code__c</fullName>
        <label>Property Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Property_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RAD_Selection_Marker__c</fullName>
        <label>Selection Marker</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Original_Datetime__c</fullName>
        <description>This field is auto populated from a trigger based on the conversion of the RAD_Date_and_Time_with_Seconds__c string field that is converted to a date/time field</description>
        <label>Original Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On List</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issued/Offer</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Refused</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Selection_Records__c.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HH_Occ__c</fullName>
        <label>Total People</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prospect__c</fullName>
        <label>Prospect</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resident__c</fullName>
        <label>Resident</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <label>SSN</label>
        <length>15</length>
        <maskChar>asterisk</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Selection Record</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selection Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Wait_List_Selection__c.object
<CustomObject>
    <fields>
        <fullName>Bedroom_Size__c</fullName>
        <label>Bedroom Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_Code__c</fullName>
        <label>Property Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Property_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RAD_Current_Scheduler_Count__c</fullName>
        <label>Current Scheduler Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Scheduler_Count__c</fullName>
        <label>Scheduler Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Eli_Count__c</fullName>
        <label>Temp Eli Count</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Li_Count__c</fullName>
        <label>Temp Li Count</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Vli_Count__c</fullName>
        <label>Temp Vli Count</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait List Selections</relationshipLabel>
        <relationshipName>Wait_List_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Wait List Selection</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait List Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_PubHsgScheduler.cls
//RUN ONLY ONCE
global class RAD_PubHsgScheduler implements Schedulable{

    global String  wlsidd;   
    global Decimal tEli;
    global Decimal tVli;
    global Decimal tLi;
    global Decimal totalRecordCount;
    global Decimal currentSchdlrCount;
        
    public RAD_PubHsgScheduler(String wlsId){
        
        System.debug('rhathi in RAD_PubHsgScheduler wlsid is '+wlsId);
        this.wlsidd =  wlsId;
        totalRecordCount = 0;
        
        
    }           

    
    global void execute(SchedulableContext sc){
    
        System.debug('Rhathi in PubLIC Hsg Scheduler execute ');
        
        Wait_List_Selection__c wls = [Select RAD_Temp_Eli_Count__c, RAD_Temp_Vli_Count__c, RAD_Temp_Li_Count__c, RAD_Scheduler_Count__c, RAD_Current_Scheduler_Count__c, Bedroom_Size__c, Property_Code__c  from Wait_List_Selection__c where id =: wlsidd limit 1];           
        system.debug('$$$$ PHScheduler wls rec' +wls);
        
        tEli = wls.RAD_Temp_Eli_Count__c;
        tVli = wls.RAD_Temp_Vli_Count__c;
        tLi  = wls.RAD_Temp_Li_Count__c;

        wls.RAD_Current_Scheduler_Count__c = wls.RAD_Current_Scheduler_Count__c != Null ? wls.RAD_Current_Scheduler_Count__c + 1 : 1;
        
        currentSchdlrCount = wls.RAD_Current_Scheduler_Count__c;
       
       
        List<Selection_Records__c> selRecList = new List<Selection_Records__c>();
        Selection_Records__c selRec = new Selection_Records__c();
        
        List<Enrolled_Wait_List__c> wlLst = new List<Enrolled_Wait_List__c>();
        
        List<Id> ctIds = new List<Id>();
        
        List<RAD_Exception_Log__c> excpLogs = new List<RAD_Exception_Log__c>();
        RAD_Exception_Log__c eLog = new RAD_Exception_Log__c();                               

        List<String>raceLst = new List<String>();
        String raceString ='';
        
        Integer posNo = 1;
        
        for(Enrolled_Wait_List__c wl : [Select name, RAD_Selection_Marker__c, Current_Status__c, Bed_size__c, 
                    Applications__r.Ethnicity__c, Applications__r.Family_Annual_Income__c, Applications__r.Total_People__c,
                    Applications__r.Applicant__r.Tenant_Number_YARDI__c, Applications__r.Applicant__r.Prospect_Number_YARDI__c,
                    Applications__r.Applicant__r.Name, Applications__r.Applicant__r.SSN_TaxID__c,  Applications__r.Applicant__r.Gender__c,
                    Applications__r.White__c, Applications__r.Black__c, Applications__r.Asian__c, Applications__r.American_Indian__c, Applications__r.Pacific_Islander__c,
                    Applications__r.Applied_Date_time__c,Limit__c, Prefernce_Point__c,SFDC_Original_Datetime__c,
                    Applications__r.Applicant__r.id
                    from Enrolled_Wait_List__c 
                    where CreatedDate>=2018-07-19T19:12:41.000+0000 and Current_Status__c = 'Onlist' and Wait_List_Type__r.Name ='Public Housing' and RAD_Selection_Marker__c != :wlsidd
                    and Bed_size__c =: wls.Bedroom_Size__c
                    order by Prefernce_Point__c desc, SFDC_Original_Datetime__c asc limit 1000]){ 
        

            // check loop for remaining counts to fill before exiting to limit records processed.
                 
            if( tEli > 0 || tVli > 0 || tLi > 0 ){
            system.debug('$$$$ PH eEli value' +tEli);  
            system.debug('$$$$ PH eEli value' +tVli); 
            system.debug('$$$$ PH eEli value' +tLi); 
                                      
                    selRec = new Selection_Records__c();
                    selRec.Status__c = wl.Current_Status__c;
                    if( tEli > 0 && wl.Limit__c  == 'eli-30'){
                       
                            selRec.Status__c = 'Selected';
                            wl.Current_Status__c = 'Selected';
                            wl.RAD_Selection_Marker__c = wlsidd;
                            wl.Property_Code__c = wls.Property_Code__c;
system.debug('$$$$ condition 1 ' +wl);                             
                            wlLst.add(wl);

                            tEli--;
                            
                            ctIds.add(wl.Applications__r.Applicant__r.id);
                            
                        

                    }
                    else if( tVli > 0 && wl.Limit__c  == 'vli-50'){

                        
                            selRec.Status__c = 'Selected';
                            wl.Current_Status__c = 'Selected';
                            wl.RAD_Selection_Marker__c = wlsidd;
                            wl.Property_Code__c = wls.Property_Code__c;
system.debug('$$$$ condition 2 ' +wl);                            
                            wlLst.add(wl);
                            tVli--;
                            
                            ctIds.add(wl.Applications__r.Applicant__r.id);
                            

                    }
                    else if(tLi > 0 && wl.Limit__c  == 'li-80'){

                        
                            selRec.Status__c = 'Selected';
                            wl.Current_Status__c = 'Selected';
                            wl.RAD_Selection_Marker__c = wlsidd;
                            wl.Property_Code__c = wls.Property_Code__c;
system.debug('$$$$ condition 3 li80' +wl); 
                            wlLst.add(wl);

                            tLi--;
                            
                            ctIds.add(wl.Applications__r.Applicant__r.id);
       

                    }else{
                        selRec.Status__c = 'Not selected due to income target';
                        
                        wl.RAD_Selection_Marker__c = wlsidd;
                        wl.Property_Code__c = wls.Property_Code__c;
system.debug('$$$$ condition 4 ' +wl);
                        wlLst.add(wl);
                    }
                    
                    
                    //add this selection record in list
                    raceLst = new List<String>();
 
                    selRec.Position__c = posNo + ((currentSchdlrCount-1) * 1000); 
                    posNo++;
                    selRec.Prospect__c = wl.Applications__r.Applicant__r.Prospect_Number_YARDI__c;
                    selRec.Resident__c = wl.Applications__r.Applicant__r.Tenant_Number_YARDI__c;
                    selRec.Name__c = wl.Applications__r.Applicant__r.Name;
                    selRec.SSN__c = wl.Applications__r.Applicant__r.SSN_TaxID__c;
                    selRec.Gender__c = wl.Applications__r.Applicant__r.Gender__c;
                    selRec.HH_Occ__c = wl.Applications__r.Total_People__c;
                    //RACE
                    if(wl.Applications__r.White__c == true){
                        raceLst.add('White');
                    }
                    if(wl.Applications__r.Black__c == true){
                        raceLst.add('Black');
                    }
                    if(wl.Applications__r.Asian__c== true){
                        raceLst.add('Asian');
                    }
                    if(wl.Applications__r.American_Indian__c == true){
                        raceLst.add('American Indian');
                    }
                    if(wl.Applications__r.Pacific_Islander__c == true){
                        raceLst.add('Pacific Islander');
                    }       
                    
                    raceString = string.join(raceLst , ',');
                    selRec.Race__c = raceString;
                    selRec.HH_Ethnicity__c = wl.Applications__r.Ethnicity__c;
                    selRec.HH_Income__c = wl.Applications__r.Family_Annual_Income__c;
                    selRec.Income_Target__c = wl.Limit__c;
                    selRec.Pref_Points__c = wl.Prefernce_Point__c==null?0:wl.Prefernce_Point__c;
                    selRec.Bed_Rooms__c = String.Valueof(wl.Bed_size__c);
                    //selRec.App_Date_Time__c = wl.RAD_Applied_Date_and_Time__c; 
                    selRec.App_Date_Time__c = wl.Applications__r.Applied_Date_time__c;                       
                    
                    
                    selRec.Selection_ID__c = wlsIdd;
                    selRec.RAD_Wait_List__c = wl.id;
                    
                    
                    
                    selRecList.add(selRec);
                        
                }else{
                    break;
                }
  
        } //for 10000
            
        //UPDATE THE WAITLIST         
        if(!wlLst.isEmpty()){
            List<Database.SaveResult> wlResultList = Database.update(wlLst, false);
            for(Integer i=0;i<wlResultList .size();i++){
            
                if(!wlResultList[i].isSuccess()){
                     eLog = new RAD_Exception_Log__c();
                     eLog.RAD_Error_Source__c = 'Error when updating WL in RAD_PubHsgScheduler: '+ wlLst[i].id ;
                     eLog.RAD_Error_Message__c = 'Public Housing Selection: '+wlResultList[i].getErrors();
                     eLog.RAD_Exception_Object_Name__c = 'Wait List Selection: '+wls.id;
    
                     excpLogs.add(eLog);
                }
            
            }
        }
        
        //INSERT THE SRs        
        if(!selRecList.isEmpty()){
            List<Database.SaveResult> srResultList = Database.insert(selRecList, false);
             RAD_checkTnumberafterSelection.checkTnumber(wlsidd);
             system.debug('$$$$ check tnumber method started');           
            for(Integer i=0;i<srResultList.size();i++){
            
                if(!srResultList[i].isSuccess()){
                     eLog = new RAD_Exception_Log__c();
                     eLog.RAD_Error_Source__c = 'Error when inserting SR in RAD_PubHsgScheduler: '+ selRecList[i].id ;
                     eLog.RAD_Error_Message__c = 'Public Housing Selection: '+srResultList[i].getErrors();
                     eLog.RAD_Exception_Object_Name__c = 'Wait List Selection: '+wls.id;
    
                     excpLogs.add(eLog);
                }
            
            }
        }
        
        //UPDATE SELECTED CONTACT 7 SEP 2017
        if(!ctIds.isEmpty()){
            List<Contact> ctList = new List<Contact>();
            for(Contact ct : [Select Property_Code__c, RAD_Is_Selected__c from Contact where id in :ctIds]){
                ct.RAD_Is_Selected__c = true;
                ct.Property_Code__c = wls.Property_Code__c == null?0:Decimal.valueOf(wls.Property_Code__c);
                ctList.add(ct);
            }
            
            List<Database.SaveResult> ctResultList = Database.update(ctList, false);
            for(Integer i=0;i<ctResultList.size();i++){
            
                if(!ctResultList[i].isSuccess()){
                     eLog = new RAD_Exception_Log__c();
                     eLog.RAD_Error_Source__c = 'Error when updating Contact in RAD_PubHsgScheduler : '+ ctList[i].id ;
                     eLog.RAD_Error_Message__c = 'Public Housing Selection - Contact Update : '+ ctResultList[i].getErrors();
                     eLog.RAD_Exception_Object_Name__c = 'Wait List Selection: '+wls.id;
    
                     excpLogs.add(eLog);
                }
            
            }
        }      
        
        if(!excpLogs.isEmpty()){
            Database.insert(excpLogs, false);
        }        
        
        wls.RAD_Temp_Eli_Count__c = tEli;
        wls.RAD_Temp_Vli_Count__c = tVli;
        wls.RAD_Temp_Li_Count__c = tLi;
        
        wls.RAD_Scheduler_Count__c = wls.RAD_Scheduler_Count__c != Null ? wls.RAD_Scheduler_Count__c - 1 : 0;
        
        if(tEli ==0 && tVli == 0 && tLi == 0){
            wls.RAD_Scheduler_Count__c = 0; 
        }
        
        if(wls.RAD_Scheduler_Count__c == 0){
            wls.Status__c = 'Completed';
            // Set Application Trigger on during run.
            SwitchTrigger__c AppTrigger = SwitchTrigger__c.getInstance('Applications__c');
            if(AppTrigger != Null) {
                AppTrigger.Active__c = true;
                update AppTrigger;
            }
        }
        
        System.debug('rhathi update wls');
        
        try{
            update wls;
            
        }catch(Exception e){
            System.debug('rhathi public hsg exception wls');
            eLog = new RAD_Exception_Log__c();
            eLog.RAD_Error_Source__c = 'Error when updating WLS in RAD_PubHsgScheduler: '+ wls.id ;
            eLog.RAD_Error_Message__c = e.getMessage();
            eLog.RAD_Exception_Object_Name__c = 'Wait List Selection: '+wls.id;
            insert eLog;
            
        
        }
        
        String abortId = sc.getTriggerId();
        System.abortJob(abortId);
           
    }       
                
}