src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Not Hispanic or Latino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Annual_Income__c</fullName>
        <label>Family Annual Income</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Family</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Homeless_with_disability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Homeless with disability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Live_Work_in_City_of_San_Diego__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Applicant lives or works within the City of San Diego</description>
        <label>Live/Work in City of San Diego</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_Elderly_Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Elderly Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <label>Social Security Number1</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spouse_Co_Head_If_applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Spouse/Co-Head/If applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_people_in_the_H_H_Adults__c</fullName>
        <label># of people in the H/H - Adults</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checkbox_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Community Global User</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Housing Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Inspector</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>On-Site Manager</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Property Manager</fullName>
                </value>
                <value>
                    <fullName>Rehab HC Specialist</fullName>
                </value>
                <value>
                    <fullName>Resident Manager</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First - Housing Our Heroes</fullName>
                </value>
                <value>
                    <fullName>Landlord/Owner</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Community Member</fullName>
                </value>
                <value>
                    <fullName>Housing Specialist</fullName>
                </value>
                <value>
                    <fullName>Section 3 Resident</fullName>
                </value>
                <value>
                    <fullName>Primary Business Contact</fullName>
                </value>
                <value>
                    <fullName>Business Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Business Admin Contact</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Payroll Contact</fullName>
                </value>
                <value>
                    <fullName>Co-Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First Client_FY18</fullName>
                </value>
                <value>
                    <fullName>Housing First Client - FY17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SSN_TaxID__c</fullName>
        <label>SSN / TaxID</label>
        <length>15</length>
        <maskChar>asterisk</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onlist</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issue/Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YARDI_HMY__c</fullName>
        <label>YARDI HMY</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RAD_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Portal_Contact_Address__c</fullName>
        <label>Portal Contact Address</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Portal_Forgot_Password_Note__c</fullName>
        <label>Portal Forgot Password Note</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Portal_Forgot_UserName_Note__c</fullName>
        <label>Portal Forgot UserName Note</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RAD_Purge_Extension_Months__c</fullName>
        <description>Purge Extension in months</description>
        <label>Purge Extension(Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update_Duration_Months__c</fullName>
        <label>Update Duration (Months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RAD Configuration</label>
    <nameField>
        <label>RAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <fields>
        <fullName>RADDisabled_Family__c</fullName>
        <label>Disabled</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADFamily__c</fullName>
        <label>Family</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADHomeless_with_disability__c</fullName>
        <label>Homeless with disability</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADLive_Work_in_City_of_San_Diego__c</fullName>
        <label>Live/Work in City of San Diego</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADNon_Elderly_Disabled__c</fullName>
        <label>Elderly</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADVeteran_Active_Military__c</fullName>
        <label>Veteran / Active Military</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YARDI_HMY__c</fullName>
        <externalId>true</externalId>
        <label>YARDI ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_WaitListHelper_Test.cls
@isTest
public  class RAD_WaitListHelper_Test
{
public static testmethod void RAD_WaitListHelperTest()
{
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        
        insert sw_list;            
RAD_Configuration__c  confg = new RAD_Configuration__c(Name = 'Main Configurations', Update_Duration_Months__c = 6, RAD_Purge_Extension_Months__c =1,
                RAD_Portal_Forgot_Password_Note__c ='This is Forgotten Password Note', RAD_Portal_Forgot_UserName_Note__c ='This is Forgotten Username Note',
                RAD_Portal_Contact_Address__c = 'This is Portal Contact Address', Announcement__c = 'This is Announcement');

            insert confg;
        Contact c = new contact(Gender__c='Male',LastName = 'sagar', Contact_Type__c = 'Asset Manager');
        
        insert c;
        c.SSN_TaxID__c='123456789';
        update c;
        Applications__c app = new Applications__c();
        app.Applicant__c=c.id;
        app.Ethnicity__c='test';
        app.SSN__c='123456789';
        app.Family__c=true;
        app.Homeless_with_disability__c=true;
        app.Family_Annual_Income__c=Decimal.valueof('1000');
        app.of_people_in_the_H_H_Adults__c=1;
        app.Homeless_with_disability__c=true;
        app.Spouse_Co_Head_If_applicable__c=true;
        insert app;
        
         Wait_List_Type__c  wlt=new  Wait_List_Type__c();
         wlt.Name='Mod Rehab';
         wlt.YARDI_HMY__c=Decimal.valueof('12345');
         wlt.RADFamily__c=1;
         wlt.RADDisabled_Family__c=1;
         wlt.RADHomeless_with_disability__c=1;
         wlt.RADLive_Work_in_City_of_San_Diego__c=1;
         wlt.RADVeteran_Active_Military__c=1;
         wlt.RADNon_Elderly_Disabled__c=1;
      
         insert wlt;
    
     
     
     
     Enrolled_Wait_List__c ew=new Enrolled_Wait_List__c();
     ew.Current_Status__c='OnList'; 
     ew.Wait_List_Type__c=wlt.id;
     //ew.Prefernce_Point__c=Decimal.valueof('3'); 
     ew.Applications__c=app.id;  
     ew.Status__c ='On List';
     ew.Portal_Status__c='Active';
     insert ew;
     Decimal pref;
  
  Test.StartTest();
   //RAD_WaitListHelper wlh = new  RAD_WaitListHelper();
     RAD_WaitListHelper.calculatePrefPoints(ew,wlt);
    
     
  Test.StopTest();
  
}
public static testmethod void RAD_WaitListHelperTest2()
{
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        
        insert sw_list;            
RAD_Configuration__c  confg = new RAD_Configuration__c(Name = 'Main Configurations', Update_Duration_Months__c = 6, RAD_Purge_Extension_Months__c =1,
                RAD_Portal_Forgot_Password_Note__c ='This is Forgotten Password Note', RAD_Portal_Forgot_UserName_Note__c ='This is Forgotten Username Note',
                RAD_Portal_Contact_Address__c = 'This is Portal Contact Address', Announcement__c = 'This is Announcement');

            insert confg;
        Contact c = new contact(Gender__c='Male',LastName = 'sagar', Contact_Type__c = 'Asset Manager');
        
        insert c;
        c.SSN_TaxID__c='123456789';
        update c;
        Applications__c app = new Applications__c();
        app.Applicant__c=c.id;
        app.Ethnicity__c='test';
        app.SSN__c='123456789';
        app.Family__c=true;
        app.Homeless_with_disability__c=true;
        app.Family_Annual_Income__c=Decimal.valueof('1000');
        app.of_people_in_the_H_H_Adults__c=1;
        app.Homeless_with_disability__c=true;
        insert app;
        
         Wait_List_Type__c  wlt=new  Wait_List_Type__c();
         wlt.Name='Mod Rehab';
         wlt.YARDI_HMY__c=Decimal.valueof('12345');
         wlt.RADFamily__c=1;
         wlt.RADDisabled_Family__c=1;
         wlt.RADHomeless_with_disability__c=1;
         wlt.RADLive_Work_in_City_of_San_Diego__c=1;
         wlt.RADVeteran_Active_Military__c=1;
         wlt.RADNon_Elderly_Disabled__c=1;
      
         insert wlt;
       
       Wait_List_Income_Limit__c wilimit=new  Wait_List_Income_Limit__c ();
       wilimit.Code__c='test';
       //wilimit.Percent_Income_Limit__c='10%';
       insert wilimit;
       
    
   Wait_List_Income_Limit_Details__c wl=new Wait_List_Income_Limit_Details__c();
    wl.Limit_Effective_Date__c=Date.today();
    wl.Limit_Effective_Date__c=Date.today();
   //wl.Percent_Income_Limit__c =1;
   wl.Income_Limit__c=wilimit.id;
    insert wl;
     
     
     Enrolled_Wait_List__c ew=new Enrolled_Wait_List__c();
     ew.Current_Status__c='Selected'; 
     ew.Wait_List_Type__c=null;
     //ew.Prefernce_Point__c=Decimal.valueof('3'); 
     ew.Applications__c=app.id;  
     ew.Status__c ='On List';
     ew.Portal_Status__c='Active';
     insert ew;
     Decimal pref;
  
  Test.StartTest();
   //RAD_WaitListHelper wlh = new  RAD_WaitListHelper();
     RAD_WaitListHelper.calculatePrefPoints(ew,wlt);
    
     
  Test.StopTest();
}
public static testmethod void RAD_WaitListHelperTest3()
{
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        
        insert sw_list;            
RAD_Configuration__c  confg = new RAD_Configuration__c(Name = 'Main Configurations', Update_Duration_Months__c = 6, RAD_Purge_Extension_Months__c =1,
                RAD_Portal_Forgot_Password_Note__c ='This is Forgotten Password Note', RAD_Portal_Forgot_UserName_Note__c ='This is Forgotten Username Note',
                RAD_Portal_Contact_Address__c = 'This is Portal Contact Address', Announcement__c = 'This is Announcement');

            insert confg;
        Contact c = new contact(Gender__c='Male',LastName = 'sagar', Contact_Type__c = 'Asset Manager');
        
        insert c;
        c.SSN_TaxID__c='123456789';
        update c;
        Applications__c app = new Applications__c();
        app.Applicant__c=c.id;
        app.Ethnicity__c='test';
        app.SSN__c='123456789';
        app.Family__c=true;
        app.Homeless_with_disability__c=true;
        app.Family_Annual_Income__c=Decimal.valueof('1000');
        app.of_people_in_the_H_H_Adults__c=1;
        app.Homeless_with_disability__c=true;
        app.Spouse_Co_Head_If_applicable__c=false;
        app.Live_Work_in_City_of_San_Diego__c=true;
        app.Non_Elderly_Disabled__c=true;
        app.Veteran_Family_of__c=true;
        insert app;
        
         Wait_List_Type__c  wlt=new  Wait_List_Type__c();
         wlt.Name='Mod Rehab';
         wlt.YARDI_HMY__c=Decimal.valueof('12345');
         wlt.RADFamily__c=1;
         wlt.RADDisabled_Family__c=1;
         wlt.RADHomeless_with_disability__c=1;
         wlt.RADLive_Work_in_City_of_San_Diego__c=1;
         wlt.RADVeteran_Active_Military__c=1;
         wlt.RADNon_Elderly_Disabled__c=1;
      
         insert wlt;
     
     Enrolled_Wait_List__c ew=new Enrolled_Wait_List__c();
     ew.Current_Status__c='OnList'; 
     ew.Wait_List_Type__c=wlt.id;
     //ew.Prefernce_Point__c=Decimal.valueof('3'); 
     ew.Applications__c=app.id;  
     ew.Status__c ='On List';
     ew.Portal_Status__c='Active';
     insert ew;
    
  

   //RAD_WaitListHelper wlh = new  RAD_WaitListHelper();
     RAD_WaitListHelper.calculatePrefPoints(ew,wlt);
    
     

}
public static testmethod void RAD_WaitListHelperTest4()
{
RAD_Configuration__c  confg = new RAD_Configuration__c(Name = 'Main Configurations', Update_Duration_Months__c = 6, RAD_Purge_Extension_Months__c =1,
                RAD_Portal_Forgot_Password_Note__c ='This is Forgotten Password Note', RAD_Portal_Forgot_UserName_Note__c ='This is Forgotten Username Note',
                RAD_Portal_Contact_Address__c = 'This is Portal Contact Address', Announcement__c = 'This is Announcement');

            insert confg;
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        
        insert sw_list;            
        Contact c = new contact(Gender__c='Male',LastName = 'sagar', Contact_Type__c = 'Asset Manager');
        
        insert c;
        c.SSN_TaxID__c='123456789';
        update c;
        Applications__c app = new Applications__c();
        app.Applicant__c=c.id;
        app.Ethnicity__c='test';
        app.SSN__c='123456789';
        app.Family__c=true;
        app.Homeless_with_disability__c=true;
        app.Family_Annual_Income__c=Decimal.valueof('1000');
        app.of_people_in_the_H_H_Adults__c=1;
        app.Homeless_with_disability__c=true;
        app.Spouse_Co_Head_If_applicable__c=false;
        app.Live_Work_in_City_of_San_Diego__c=true;
        app.Non_Elderly_Disabled__c=true;
        app.Veteran_Family_of__c=true;
        insert app;
        
         Wait_List_Type__c  wlt=new  Wait_List_Type__c();
         wlt.Name='Mod Rehab';
         wlt.YARDI_HMY__c=Decimal.valueof('12345');
         wlt.RADFamily__c=1;
         wlt.RADDisabled_Family__c=1;
         wlt.RADHomeless_with_disability__c=1;
         wlt.RADLive_Work_in_City_of_San_Diego__c=1;
         wlt.RADVeteran_Active_Military__c=1;
         wlt.RADNon_Elderly_Disabled__c=1;
      
         insert wlt;
     
     Enrolled_Wait_List__c ew=new Enrolled_Wait_List__c();
     ew.Current_Status__c='Removed'; 
     ew.Wait_List_Type__c=wlt.id;
     //ew.Prefernce_Point__c=Decimal.valueof('3'); 
     ew.Applications__c=app.id;  
     ew.Status__c ='On List';
     ew.Portal_Status__c='Active';
     insert ew;
     Decimal pref;
  
 
   //RAD_WaitListHelper wlh = new  RAD_WaitListHelper();
     RAD_WaitListHelper.calculatePrefPoints(ew,wlt);
    
     
}
public static testmethod void RAD_WaitListHelperTest5()
{
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        
        insert sw_list;            
RAD_Configuration__c  confg = new RAD_Configuration__c(Name = 'Main Configurations', Update_Duration_Months__c = 6, RAD_Purge_Extension_Months__c =1,
                RAD_Portal_Forgot_Password_Note__c ='This is Forgotten Password Note', RAD_Portal_Forgot_UserName_Note__c ='This is Forgotten Username Note',
                RAD_Portal_Contact_Address__c = 'This is Portal Contact Address', Announcement__c = 'This is Announcement');

            insert confg;
        Contact c = new contact(Gender__c='Male',LastName = 'sagar', Contact_Type__c = 'Asset Manager');
        
        insert c;
        c.SSN_TaxID__c='123456789';
        update c;
        Applications__c app = new Applications__c();
        app.Applicant__c=c.id;
        app.Ethnicity__c='test';
        app.SSN__c='123456789';
        app.Family__c=true;
        app.Homeless_with_disability__c=true;
        app.Family_Annual_Income__c=Decimal.valueof('1000');
        app.of_people_in_the_H_H_Adults__c=1;
        app.Homeless_with_disability__c=true;
        app.Spouse_Co_Head_If_applicable__c=false;
        app.Live_Work_in_City_of_San_Diego__c=true;
        app.Non_Elderly_Disabled__c=true;
        app.Veteran_Family_of__c=true;
        insert app;
        
         Wait_List_Type__c  wlt=new  Wait_List_Type__c();
         wlt.Name='Mod Rehab';
         wlt.YARDI_HMY__c=Decimal.valueof('12345');
         wlt.RADFamily__c=1;
         wlt.RADDisabled_Family__c=1;
         wlt.RADHomeless_with_disability__c=1;
         wlt.RADLive_Work_in_City_of_San_Diego__c=1;
         wlt.RADVeteran_Active_Military__c=1;
         wlt.RADNon_Elderly_Disabled__c=1;
      
         insert wlt;
     
     Enrolled_Wait_List__c ew=new Enrolled_Wait_List__c();
     ew.Current_Status__c='Leased'; 
     ew.Wait_List_Type__c=wlt.id;
     //ew.Prefernce_Point__c=Decimal.valueof('3'); 
     ew.Applications__c=app.id;  
     ew.Status__c ='On List';
     ew.Portal_Status__c='Active';
     insert ew;
     Decimal pref;
  
 
   //RAD_WaitListHelper wlh = new  RAD_WaitListHelper();
     RAD_WaitListHelper.calculatePrefPoints(ew,wlt);
    
}
public static testmethod void RAD_WaitListHelperTest6()
{
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        
        insert sw_list;            
RAD_Configuration__c  confg = new RAD_Configuration__c(Name = 'Main Configurations', Update_Duration_Months__c = 6, RAD_Purge_Extension_Months__c =1,
                RAD_Portal_Forgot_Password_Note__c ='This is Forgotten Password Note', RAD_Portal_Forgot_UserName_Note__c ='This is Forgotten Username Note',
                RAD_Portal_Contact_Address__c = 'This is Portal Contact Address', Announcement__c = 'This is Announcement');

            insert confg;
        Contact c = new contact(Gender__c='Male',LastName = 'sagar', Contact_Type__c = 'Asset Manager');
        
        insert c;
        c.SSN_TaxID__c='123456789';
        update c;
        Applications__c app = new Applications__c();
        app.Applicant__c=c.id;
        app.Ethnicity__c='test';
        app.SSN__c='123456789';
        app.Family__c=true;
        app.Homeless_with_disability__c=true;
        app.Family_Annual_Income__c=Decimal.valueof('1000');
        app.of_people_in_the_H_H_Adults__c=1;
        app.Homeless_with_disability__c=true;
        app.Spouse_Co_Head_If_applicable__c=false;
        app.Live_Work_in_City_of_San_Diego__c=true;
        app.Non_Elderly_Disabled__c=true;
        app.Veteran_Family_of__c=true;
        insert app;
        
         Wait_List_Type__c  wlt=new  Wait_List_Type__c();
         wlt.Name='Mod Rehab';
         wlt.YARDI_HMY__c=Decimal.valueof('12345');
         wlt.RADFamily__c=1;
         wlt.RADDisabled_Family__c=1;
         wlt.RADHomeless_with_disability__c=1;
         wlt.RADLive_Work_in_City_of_San_Diego__c=1;
         wlt.RADVeteran_Active_Military__c=1;
         wlt.RADNon_Elderly_Disabled__c=1;
      
         insert wlt;
     
     Enrolled_Wait_List__c ew=new Enrolled_Wait_List__c();
     ew.Current_Status__c='Selected'; 
     ew.Wait_List_Type__c=wlt.id;
     ew.Applications__c=app.id;       
     ew.Portal_Status__c='Active';
     insert ew;
     Decimal pref;

   //RAD_WaitListHelper wlh = new  RAD_WaitListHelper();
   RAD_WaitListHelper.calculatePrefPoints(ew,wlt);
    

}
public static testmethod void RAD_WaitListHelperTest7()
{
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        
        insert sw_list;            
RAD_Configuration__c  confg = new RAD_Configuration__c(Name = 'Main Configurations', Update_Duration_Months__c = 6, RAD_Purge_Extension_Months__c =1,
                RAD_Portal_Forgot_Password_Note__c ='This is Forgotten Password Note', RAD_Portal_Forgot_UserName_Note__c ='This is Forgotten Username Note',
                RAD_Portal_Contact_Address__c = 'This is Portal Contact Address', Announcement__c = 'This is Announcement');

            insert confg;
        Contact c = new contact(Gender__c='Male',LastName = 'sagar', Contact_Type__c = 'Asset Manager');
        
        insert c;
        c.SSN_TaxID__c='123456789';
        update c;
        Applications__c app = new Applications__c();
        app.Applicant__c=c.id;
        app.Ethnicity__c='test';
        app.SSN__c='123456789';
        app.Family__c=false;
        app.Homeless_with_disability__c=true;
        app.Family_Annual_Income__c=Decimal.valueof('1000');
        app.of_people_in_the_H_H_Adults__c=16;
        app.Homeless_with_disability__c=true;
        app.Spouse_Co_Head_If_applicable__c=false;
        app.Live_Work_in_City_of_San_Diego__c=true;
        app.Non_Elderly_Disabled__c=true;
        app.Veteran_Family_of__c=true;
        insert app;
        
         Wait_List_Type__c  wlt=new  Wait_List_Type__c();
         wlt.Name='Mod Rehab';
         wlt.YARDI_HMY__c=Decimal.valueof('12345');
         wlt.RADFamily__c=1;
         wlt.RADDisabled_Family__c=1;
         wlt.RADHomeless_with_disability__c=1;
         wlt.RADLive_Work_in_City_of_San_Diego__c=1;
         wlt.RADVeteran_Active_Military__c=1;
         wlt.RADNon_Elderly_Disabled__c=1;
      
         insert wlt;
     
     Enrolled_Wait_List__c ew=new Enrolled_Wait_List__c();
     ew.Current_Status__c ='Onlist';
     //ew.Wait_List_Type__c=wlt.id;
     ew.Applications__c=app.id;      
     insert ew;
   
   //RAD_WaitListHelper wlh = new  RAD_WaitListHelper();
    //RAD_WaitListHelper.processWLsBeforeUpdate();
   
    
}
}