src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Residential_City__c</fullName>
        <label>Residential City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_State__c</fullName>
        <label>Residential State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_Street__c</fullName>
        <label>Residential Street</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_Zipcode__c</fullName>
        <label>Residential Zipcode</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On List</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issued/Offer</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Refused</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Selection_Records__c.object
<CustomObject>
    <fields>
        <fullName>RAD_Wait_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List</label>
        <referenceTo>Enrolled_Wait_List__c</referenceTo>
        <relationshipLabel>Selection Records</relationshipLabel>
        <relationshipName>Selection_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selection_ID__c</fullName>
        <label>Wait List Selection</label>
        <referenceTo>Wait_List_Selection__c</referenceTo>
        <relationshipLabel>Selection Records</relationshipLabel>
        <relationshipName>Selection_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Selection Record</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selection Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Wait_List_Selection__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait List Selections</relationshipLabel>
        <relationshipName>Wait_List_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Wait List Selection</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait List Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_RefLetterpdf.cls
public class RAD_RefLetterpdf{
    public Wait_List_Selection__c  wlcon {get;set;}
    
    public list<Selection_Records__c>  selList;
    
    public String wlsId {get;set;}
    
    public  RAD_RefLetterpdf(ApexPages.StandardController stdController ) {
        this.wlcon = (Wait_List_Selection__c)stdController.getRecord(); 
        
    }  
    
    public List<Selection_Records__c> getSelList()     
    {
        wlsId=wlcon.id;
        
        List<Selection_Records__c> selList=[select Name ,Selection_ID__c,Selection_ID__r.Name,RAD_Wait_List__c,RAD_Wait_List__r.Wait_List_Type__r.Name,Status__c,
            RAD_Wait_List__r.Applications__c,RAD_Wait_List__r.Applications__r.Name,RAD_Wait_List__r.Applications__r.Applicant__c,
            RAD_Wait_List__r.Applications__r.Applicant__r.Name,RAD_Wait_List__r.Applications__r.Applicant__r.Email,RAD_Wait_List__r.Applications__r.Applicant__r.Phone,
            RAD_Wait_List__r.Applications__r.Applicant__r.MailingStreet, RAD_Wait_List__r.Applications__r.Applicant__r.Mailingcity,
            RAD_Wait_List__r.Applications__r.Applicant__r.MailingState,RAD_Wait_List__r.Applications__r.Applicant__r.Mailingpostalcode,
            RAD_Wait_List__r.Applications__r.Applicant__r.Residential_Street__c,RAD_Wait_List__r.Applications__r.Applicant__r.Residential_City__c,
            RAD_Wait_List__r.Applications__r.Applicant__r.Residential_State__c,RAD_Wait_List__r.Applications__r.Applicant__r.Residential_Zipcode__c,
            RAD_Wait_List__r.Applications__r.Applicant__r.MobilePhone from Selection_Records__c 
                 where Status__c='Selected' and Selection_ID__c=:wlsId ];
        
        
        return selList;
    }
    
    
}