src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>IF( NOT( ISBLANK(DOB__c) ) , 
IF( DATE( 2000 , MONTH( DOB__c ) , DAY( DOB__c ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ), 
YEAR (Today()) - YEAR (DOB__c), 
YEAR (Today()) - YEAR ( DOB__c ) -1 ), 
null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>American_Indian__c</fullName>
        <defaultValue>false</defaultValue>
        <label>American Indian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Update Required</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>On List</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Are_you_in_Active_duty_with_US_Army__c</fullName>
        <label>Are you in active duty with US military</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Are_you_or_your_spouse_co_head_disabled__c</fullName>
        <label>Are you or your spouse/co-head disabled</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Are_you_veteran_or_a_family_of_a_ventera__c</fullName>
        <label>Are you veteran or a family of veteran</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Asian__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Black__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Black</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible Citizen</fullName>
                </value>
                <value>
                    <fullName>Eligible Non - Citizen</fullName>
                </value>
                <value>
                    <fullName>Ineligible Non-Citizen</fullName>
                </value>
                <value>
                    <fullName>Pending Verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dependents_Children_under_age_of_18__c</fullName>
        <label>Dependents/Children under age of 18</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Disable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disabled_Family__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Displaced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Displaced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High School</fullName>
                </value>
                <value>
                    <fullName>Masters</fullName>
                </value>
                <value>
                    <fullName>No formal education</fullName>
                </value>
                <value>
                    <fullName>Primary education</fullName>
                </value>
                <value>
                    <fullName>Secondary education</fullName>
                </value>
                <value>
                    <fullName>GED</fullName>
                </value>
                <value>
                    <fullName>Vocational qualification</fullName>
                </value>
                <value>
                    <fullName>Doctorate or higher</fullName>
                </value>
                <value>
                    <fullName>Bachelors</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Some college</fullName>
                </value>
                <value>
                    <fullName>Middle School</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Elderly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Elderly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Employment_Zip_Code__c</fullName>
        <label>Employment Zip Code</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Not Hispanic or Latino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Annual_Income__c</fullName>
        <label>Family Annual Income</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Family</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>Spouse First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hearing_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hearing Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Homeless__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Homeless</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Homeless_with_disability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Homeless with disability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Spouse Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Work_in_City_of_San_Diego__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Applicant lives or works within the City of San Diego</description>
        <label>Live/Work in City of San Diego</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobility_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobility Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Near_Elderly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Near Elderly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_Elderly_Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Elderly Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Architecture and Engineering</fullName>
                </value>
                <value>
                    <fullName>Unemployed</fullName>
                </value>
                <value>
                    <fullName>Arts Design Entertainment Sports and Media</fullName>
                </value>
                <value>
                    <fullName>Building Grounds Cleaning and Maintenance</fullName>
                </value>
                <value>
                    <fullName>Business and Financial Operations</fullName>
                </value>
                <value>
                    <fullName>Community and Social Service</fullName>
                </value>
                <value>
                    <fullName>Computer and Mathematical</fullName>
                </value>
                <value>
                    <fullName>Construction and Extraction</fullName>
                </value>
                <value>
                    <fullName>Education Training and Library</fullName>
                </value>
                <value>
                    <fullName>Farming Fishing and Forestry</fullName>
                </value>
                <value>
                    <fullName>Food Preparation and Serving</fullName>
                </value>
                <value>
                    <fullName>Healthcare Practitioners and Technical</fullName>
                </value>
                <value>
                    <fullName>Healthcare Support</fullName>
                </value>
                <value>
                    <fullName>Installation Maintenance and Repair</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Life or Physical or Social Science</fullName>
                </value>
                <value>
                    <fullName>Management</fullName>
                </value>
                <value>
                    <fullName>Military Specific</fullName>
                </value>
                <value>
                    <fullName>Office and Administrative Support</fullName>
                </value>
                <value>
                    <fullName>Personal Care and Service</fullName>
                </value>
                <value>
                    <fullName>Production and Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Protective Service</fullName>
                </value>
                <value>
                    <fullName>Sales and Related</fullName>
                </value>
                <value>
                    <fullName>Transportation and Material Moving</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pacific_Islander__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pacific Islander</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <label>Social Security Number1</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sight_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sight Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Veteran_Family_of__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Applicant is from a veteran / active military or family of veterans</description>
        <label>Veteran / Active Military</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>White__c</fullName>
        <defaultValue>false</defaultValue>
        <label>White</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_people_in_the_H_H_Adults__c</fullName>
        <label># of people in the H/H - Adults</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Homeless__c</fullName>
        <inlineHelpText>Is this person currently homeless?</inlineHelpText>
        <label>Homeless?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checkbox_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RADApplicationCtrlr.cls
global class RADApplicationCtrlr {
    /*
    public String CSSURL {get; set;}
    public String JSURL {get; set;}    
    
    public Applications__c theApp {get; set;}               
    
    public RADApplicationCtrlr(){
        StaticResource objStc = [Select Id, LastModifiedDate From StaticResource where Name='RAD_Web'];        
        Long iCnt = objStc.LastModifiedDate.getTime();        
        CSSURL = '/resource/'+iCnt+'/RAD_Web/css/';
        JSURL  = '/resource/'+iCnt+'/RAD_Web/js/';
    }
    
    @RemoteAction
    global static Applications__c saveSubmit(Applications__c app, String action){       
        try {                                                           
            system.debug('ACTION: ' + action);
            if(app.Applicant__c == null){
                app.Applicant__c = [select Id from Contact limit 1][0].Id; //to change  
            }           
            
            if(action.equals('save')){                              
                app.Application_Status__c = 'Saved';
            }else if(action.equals('submit')){
                app.Application_Status__c = 'Submitted';
            }
            
            if(app.Id != null){
                update(app);                
            }else {
                insert(app);
                for( Applications__c application : [Select a.Name, a.of_people_in_the_H_H_Adults__c, a.White__c, a.Veteran_Family_of__c, a.Sight_Access__c, a.SSN__c, a.Pacific_Islander__c,a.Family_Annual_Income__c, a.Occupation__c, a.Non_Elderly_Disabled__c, a.Near_Elderly__c, a.Mobility_Access__c, a.Middle_Name__c, a.Live_Work_in_City_of_San_Diego__c, a.Last_Name__c, a.Homeless_with_disability__c, a.Homeless__c, a.Hearing_Access__c, a.First_Name__c, a.Family__c,  a.Ethnicity__c, a.Employment_Zip_Code__c, a.Elderly__c, a.Education__c, a.Displaced__c, a.Disabled_Family__c, a.Disable__c, a.Dependents_Children_under_age_of_18__c, a.DOB__c, a.Citizenship__c, a.Black__c, a.Asian__c, a.Are_you_veteran_or_a_family_of_a_ventera__c, a.Are_you_or_your_spouse_co_head_disabled__c, a.Are_you_in_Active_duty_with_US_Army__c, a.American_Indian__c, a.Age__c From Applications__c a where Id = :app.id Limit 1]){                                                                           
                    app = application;
                }
            }               
            
            return app;
        }catch(Exception e){
            system.debug(e.getMessage());
            return null;
            //return 'FAIL : ' + e.getMessage();            
        }           
    }   
    
    @RemoteAction
    global static Applications__c getApplication(String appid){
        if(appid != null || appid.length() > 0){            
            List<Applications__c> app = new List<Applications__c>();
            for( Applications__c application : [Select a.Name, a.of_people_in_the_H_H_Adults__c, a.White__c, a.Veteran_Family_of__c, a.Sight_Access__c, a.SSN__c, a.Pacific_Islander__c, a.Family_Annual_Income__c,a.Occupation__c, a.Non_Elderly_Disabled__c, a.Near_Elderly__c, a.Mobility_Access__c, a.Middle_Name__c, a.Live_Work_in_City_of_San_Diego__c, a.Last_Name__c, a.Homeless_with_disability__c, a.Homeless__c, a.Hearing_Access__c, a.First_Name__c, a.Family__c,  a.Ethnicity__c, a.Employment_Zip_Code__c, a.Elderly__c, a.Education__c, a.Displaced__c, a.Disabled_Family__c, a.Disable__c, a.Dependents_Children_under_age_of_18__c, a.DOB__c, a.Citizenship__c, a.Black__c, a.Asian__c, a.Are_you_veteran_or_a_family_of_a_ventera__c, a.Are_you_or_your_spouse_co_head_disabled__c, a.Are_you_in_Active_duty_with_US_Army__c, a.American_Indian__c, a.Age__c From Applications__c a where Id = :appid Limit 1]){
                                                                                      
                                                                                          
                app.add(application);
            }
            if(!app.isEmpty()){
                return app.get(0);
            }else return new Applications__c();                                 
        }else return new Applications__c();             
    }   
    
    */ 
    
}