src/objects/Applications__c.object
<CustomObject>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On List</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issued/Offer</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Refused</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Selection_Records__c.object
<CustomObject>
    <fields>
        <fullName>RAD_Wait_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List</label>
        <referenceTo>Enrolled_Wait_List__c</referenceTo>
        <relationshipLabel>Selection Records</relationshipLabel>
        <relationshipName>Selection_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selection_ID__c</fullName>
        <label>Wait List Selection</label>
        <referenceTo>Wait_List_Selection__c</referenceTo>
        <relationshipLabel>Selection Records</relationshipLabel>
        <relationshipName>Selection_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Selection Record</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selection Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Wait_List_Selection__c.object
<CustomObject>
    <fields>
        <fullName>RAD_Current_Scheduler_Count__c</fullName>
        <label>Current Scheduler Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scheduled_Date__c</fullName>
        <label>Scheduled Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait List Selections</relationshipLabel>
        <relationshipName>Wait_List_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Wait List Selection</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait List Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_checkTnumberafterSelection.cls
//Purpose of this class: Once selection Run is completed, boomi will pickup all selectedRecords and pass it to Yardi, Once update in Yardi is sucesssful Tnumber will be generated. Boomi will assign Tnumber back to Salesforce. 
//This class will check for Tnumbers, if present it run RAD_commonSchedulerbeforeCSV , if not delaying RAD_commonSchedulerbeforeCSV for 30 min. 


public class RAD_checkTnumberafterSelection{

public Static void checkTnumber(String wlsidd){

   set<id> Selids = new set<id>();
   //Querying selectionRecords whose selectionID is waitlistSelctionID and status is Selected. 
   
   List<Selection_Records__c> selList = [select id,Selection_ID__c, RAD_Wait_List__r.Applications__r.Applicant__r.Tenant_Number_YARDI__c, Selection_ID__r.RAD_Current_Scheduler_Count__c, Selection_ID__r.Wait_List_Type__c,
                                         Selection_ID__r.Name,Selection_ID__r.Scheduled_Date__c from Selection_Records__c where Selection_ID__c = :wlsidd and Status__c = 'Selected' ];
   //looping through selectionrecords, checking for Tnumber, if Tnumber is present then adding it to Selids.                       
   for(Selection_Records__c sr: selList ){
                 if(sr.RAD_Wait_List__r.Applications__r.Applicant__r.Tenant_Number_YARDI__c!=null && 
                         sr.RAD_Wait_List__r.Applications__r.Applicant__r.Tenant_Number_YARDI__c!=''){
                    Selids.add(sr.id);                           
                           } 
                  /*         else
                           {
                            String cronExpr = '';
                            Datetime dt = Datetime.now();
                            // Decimal tempMin = 59;
                            Decimal tempMin = 0;
                            dt = Datetime.now();
                                tempMin = dt.minute() + 1 ;  //dont use current min, 
                                tempMin = dt.minute() + 30 ;  //dont use current min, 
                                if(dt.second()>=55 ){
                                    tempMin = dt.minute() + 2 ;
                                }
                                if(tempMin >= 59){
                                    tempMin = 0;
                                }  
                                cronExpr = '0 ' + tempMin + ' * * * ? *';
system.debug('$$$$ CronTriggerExpession, else statement' +cronExpr );                                
                                System.debug('my cron trigger will be 1 min from now '+ dt+ '::'+ cronExpr );  
                                
                                
                                
                                String cronExpr = '';
                                Decimal tempHours = 1; 
                                cronExpr = '0 ' + '0 ' + tempHours+' * * ? '; // Setting crontriggerexpression ti run @1am. 
system.debug('$$$$ cronexpression value' +cronExpr);

                                Integer randSeed = Math.round(Math.random()*100000);
                                RAD_commonSchedulerbeforeCSV cs = new RAD_commonSchedulerbeforeCSV (wlsidd);
                                String jobID = System.schedule('Common Scheduler  '+ sr.Selection_ID__r.Wait_List_Type__c + sr.Selection_ID__r.RAD_Current_Scheduler_Count__c +sr.Selection_ID__r.Name+'_'+ sr.Selection_ID__r.Scheduled_Date__c.format()+'_'+String.valueof(randSeed), cronExpr , cs);
                             Break;
                           } */

}
if(!Selids.isEmpty() && !selList.isempty())
if(Selids.size() == selList.size())
{   RAD_SelectionRecordsCSVAttachment SR = new RAD_SelectionRecordsCSVAttachment();
    SR.csvAttachment(wlsidd); // Sending an email to Scheduler.(Email will have an attachment(.CSV format) which will have Seletion Records.)
    system.debug('$$$$ csvattachmentfired');
}
}
}