src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applied_Date_time__c</fullName>
        <description>Applied Date/time on Application to map to Yardi Applied Date</description>
        <inlineHelpText>Applied Date/time</inlineHelpText>
        <label>Applied Date/time</label>
        <type>DateTime</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bed_size__c</fullName>
        <label>Bed size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onlist</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issue/Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lottery__c</fullName>
        <label>Lottery</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prefernce_Point__c</fullName>
        <label>Preference Point</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RAD_Exception_Log__c.object
<CustomObject>
    <fields>
        <fullName>RAD_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RAD_Error_Source__c</fullName>
        <label>Error Source</label>
        <type>TextArea</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <label>Exception Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/objects/Wait_List_Selection__c.object
<CustomObject>
    <fields>
        <fullName>Number_to_Select_from_List__c</fullName>
        <formula>CEILING (Number_of_vacancies_to_fill__c * (100 / VALUE( Wait_List_Type__r.Lease_Up__c ) ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number to Select from List</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Current_Scheduler_Count__c</fullName>
        <label>Current Scheduler Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Scheduler_Count__c</fullName>
        <label>Scheduler Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Number_to_Select__c</fullName>
        <label>Temp Number to Select</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait List Selections</relationshipLabel>
        <relationshipName>Wait_List_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Wait List Selection</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait List Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_MODRBSeln_Batch.cls
//This class generates random number for lottery selection for onlist Mod Rehab WL for the given bedroom count and 
//counts the wl records for processing.

global class RAD_MODRBSeln_Batch implements Database.batchable<sObject>,Database.Stateful{
    
    String query;
    Decimal bedroomsz;
    global Set<String> ranNumSet; 
    global String wlsidd;
    global Decimal totalRecordCount;
    
    
    
    global RAD_MODRBSeln_Batch(String wlsId, Decimal bedroomsize)
    {
       
        system.debug('wlsid  is-----'+ wlsId); 
         
        wlsidd=wlsid;
        ranNumSet = new Set<String>(); 
        bedroomsz = bedroomsize;
        totalRecordCount = 0;

         
        query = 'Select ID, Lottery__c ' +
            ' from Enrolled_Wait_List__c where CreatedDate >= 2018-07-19T19:12:41.000+0000 and Current_Status__c = \'Onlist\' and Wait_List_Type__r.Name =\'Mod Rehab\' and Bed_size__c =: bedroomsz'+
            ' order by Prefernce_Point__c desc,Applications__r.Applied_Date_time__c asc';                               
        /*
        //Query with createddate filter(manuallycreated data) 
        query = 'Select ID, Lottery__c ' +
            ' from Enrolled_Wait_List__c where CreatedDate >= 2018-07-19T19:12:41.000+0000 and Current_Status__c = \'Onlist\' and Wait_List_Type__r.Name =\'Mod Rehab\' and Bed_size__c =: bedroomsz'+
            ' order by Prefernce_Point__c desc,Applications__r.Applied_Date_time__c asc';
            */
            
        system.debug('Query is-----'+ query); 
        
    }
    
    
    
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List< Enrolled_Wait_List__c > scope)
    {
        
        
        List<RAD_Exception_Log__c> excpLogs = new List<RAD_Exception_Log__c>();
        RAD_Exception_Log__c eLog = new RAD_Exception_Log__c();
        
        
        
        String str ='';
        String randomNumber = '';
        for(Enrolled_Wait_List__c wl : scope )    
        {
            
            str = String.valueof(Math.abs(Crypto.getRandomLong()));
            randomNumber = str.substring(0,6);
            

            while(ranNumSet.contains(randomNumber) == true ){

            str = String.valueof(Math.abs(Crypto.getRandomLong()));
            randomNumber = str.substring(0,6);
            
            }
            
            wl.Lottery__c = Decimal.valueOf(randomNumber);
            ranNumSet.add(randomNumber);
            
            
        } 
        
        
        if(!scope.isEmpty()){
            
            totalRecordCount += scope.size(); 
            
            List<Database.SaveResult> wlResultList = Database.update(scope, false);
            for(Integer i=0;i<wlResultList.size();i++){
            
                if(!wlResultList[i].isSuccess()){
                     eLog = new RAD_Exception_Log__c();
                     eLog.RAD_Error_Source__c = 'Error when updating lottery number on WL-Mod Rehab: '+ scope[i].id ;
                     eLog.RAD_Error_Message__c = 'Lottery Number Generation -MRHB: '+wlResultList[i].getErrors();
    
                     excpLogs.add(eLog);
                }
            
            }
        }
        
        
        
        if(!excpLogs.isEmpty()){
            Database.insert(excpLogs, false);
        }    
    


         //system.debug(totalRecordCount); 
        
         //system.debug('set size is--->'+rannumset.size());
         //system.debug(rannumset);
        

    } 
    
    
    
    global void finish(Database.BatchableContext BC)
    {
        // Set Application Trigger on during run.
        SwitchTrigger__c AppTrigger = SwitchTrigger__c.getInstance('Applications__c');
        if(AppTrigger != Null) {
            AppTrigger.Active__c = false;
            update AppTrigger;
        }
       
        Wait_List_Selection__c  wls = [Select RAD_Scheduler_Count__c, Number_to_Select_from_List__c, RAD_Current_Scheduler_Count__c, RAD_Temp_Number_to_Select__c
                                       from Wait_List_Selection__c where id =:wlsidd limit 1];
        
        wls.RAD_Temp_Number_to_Select__c = wls.Number_to_Select_from_List__c==null?0:wls.Number_to_Select_from_List__c;
        wls.RAD_Scheduler_Count__c = totalRecordCount.divide(1000, 0, System.RoundingMode.UP);
        wls.RAD_Current_Scheduler_Count__c = 0;
        
        Database.update(wls,false);
        
    }            
    
    
    
}