src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Update Required</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>On List</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Email_Id_s__mdt.object
<CustomObject>
    <fields>
        <fullName>Email_Id__c</fullName>
        <label>Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Email Id</label>
    <pluralLabel>Email Ids</pluralLabel>
</CustomObject>

src/classes/RAD_DailyAppRecsDeleteBatch.cls
//Purpose of this Batch is to Delete All Application Records whose Status is Closed on a daily basis.

global class RAD_DailyAppRecsDeleteBatch implements Database.Batchable<sObject> {
    public String query;
    
    
    global RAD_DailyAppRecsDeleteBatch (){
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        query = 'select id, name from Applications__c '+
                ' where Application_Status__c in (\'Closed\',\'Removed\') ';
            
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Applications__c> scope){
        delete scope;
    }
    
    global void finish(Database.BatchableContext BC){
        
        Email_Id_s__mdt e = [select id, Name__c, Email_Id__c from Email_Id_s__mdt where DeveloperName = 'Developer2_Email_ID' limit 1];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[]{e.Email_Id__c};
            mail.setToAddresses(toAddresses);
        mail.setSubject('Status Update: Daily Application Records Delete Batch Completed');
        mail.setPlainTextBody(
            'Daily Application Records Delete Batch Process has completed, All Application Records which are in Closed status are deleted sucessfully.' 
        );        
        try {
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        } catch(System.EmailException sme) {
            
        }
        
        
    }
}