src/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications_WL_00000001</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Disabled_Family__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Elderly_Family__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Elderly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Family</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Homeless_with_disability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Homeless with disability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Live_Work_in_City_of_San_Diego__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Applicant lives or works within the City of San Diego</description>
        <label>Live/Work in City of San Diego</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_Elderly_Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Elderly Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Veteran_Family_of__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Applicant is from a veteran / active military or family of veterans</description>
        <label>Veteran / Active Military</label>
        <type>Checkbox</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checkbox_Results</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Enrolled_Wait_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onlist</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issue/Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prefernce_Point__c</fullName>
        <label>Preference Point</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Applied_Date_and_Time__c</fullName>
        <description>This field is updated when WL is created and reapplied</description>
        <inlineHelpText>This field is updated when WL is created and reapplied</inlineHelpText>
        <label>Applied Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Current_Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Over Income</fullName>
                </value>
                <value>
                    <fullName>Criminal</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Refused Offer</fullName>
                </value>
                <value>
                    <fullName>Income Targeting</fullName>
                </value>
                <value>
                    <fullName>System Selection</fullName>
                </value>
                <value>
                    <fullName>NED</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Briefing</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Dropped</fullName>
                </value>
                <value>
                    <fullName>Dropped/No Update 2011</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>Lease Up</fullName>
                </value>
                <value>
                    <fullName>No Show/Response</fullName>
                </value>
                <value>
                    <fullName>Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Offer Rejected</fullName>
                </value>
                <value>
                    <fullName>Voucher Cancelled</fullName>
                </value>
                <value>
                    <fullName>Voucher Expired</fullName>
                </value>
                <value>
                    <fullName>Voucher Issued</fullName>
                </value>
                <value>
                    <fullName>Yearly Updated</fullName>
                </value>
                <value>
                    <fullName>Special Admission</fullName>
                </value>
                <value>
                    <fullName>See Memo</fullName>
                </value>
                <value>
                    <fullName>Accessibility Needs</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Deconcentrate Poverty</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>No, Response</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Request</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted Selection</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Vou Expired</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On List</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issued/Offer</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Refused</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YARDI_HMY__c</fullName>
        <label>YARDI HMY</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SwitchTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to enable and disable triggers in production</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to activate/ deactivate trigger execution</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>SwitchTrigger</label>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <fields>
        <fullName>RADFamily__c</fullName>
        <label>Family</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADLive_Work_in_City_of_San_Diego__c</fullName>
        <label>Live/Work in City of San Diego</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADNon_Elderly_Disabled__c</fullName>
        <label>Elderly</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RADVeteran_Active_Military__c</fullName>
        <label>Veteran / Active Military</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YARDI_HMY__c</fullName>
        <externalId>true</externalId>
        <label>YARDI ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_WLTrigHlprTest.cls
@isTest
public class RAD_WLTrigHlprTest{

     public static testmethod void testWLBasic(){

        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;     
        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name, RADFamily__c, RADLive_Work_in_City_of_San_Diego__c, 
                RADNon_Elderly_Disabled__c, RADVeteran_Active_Military__c from Wait_List_Type__c where name ='Public Housing' limit 1];
        Test.startTest();

            List<Contact> cts = TestSuiteHelper.setupPortalRequiredData();  
            Contact ct = cts[0];
            Applications__c app = [Select id, Elderly_Family__c, Family__c, Homeless_with_disability__c, Live_Work_in_City_of_San_Diego__c,
                        Non_Elderly_Disabled__c, Disabled_Family__c, Veteran_Family_of__c from Applications__c where Applicant__c =:ct.id limit 1];

            
            List<Enrolled_Wait_List__c> wlst = [Select RAD_Applied_Date_and_Time__c,  Applications__r.Family__c, Applications__r.Homeless_with_disability__c,
                Applications__r.Live_Work_in_City_of_San_Diego__c, Applications__r.Non_Elderly_Disabled__c , Applications__r.Veteran_Family_of__c  from Enrolled_Wait_List__c where Applications__c =: app.id ];
            //Database.delete(wlst, false);

             Enrolled_Wait_List__c ew = new Enrolled_Wait_List__c();
             ew.Wait_List_Type__c=wlt.id;
             ew.Prefernce_Point__c=Decimal.valueof('3'); 
             ew.Applications__c=app.id;   
             ew.Current_Status__c='Onlist'; 
             ew.Status__c = 'On List';
             ew.Reason__c ='Active';
             
             //Database.insert( ew, false);
             //Database.delete(ew, false);
             
             
             
             ew = new Enrolled_Wait_List__c();
             ew.Current_Status__c= 'Removed';
             ew.Wait_List_Type__c=wlt.id;
             ew.Prefernce_Point__c=Decimal.valueof('3'); 
             ew.Applications__c=app.id;
             ew.Reason__c ='Active';   

             //Database.insert( ew, false);
             //Database.delete(ew, false);
             
             ew = new Enrolled_Wait_List__c();
             ew.Wait_List_Type__c=wlt.id;
             ew.Prefernce_Point__c=Decimal.valueof('2'); 
             ew.Applications__c=app.id;   
             ew.Current_Status__c= 'Leased';
             ew.Reason__c ='Active';
             
             //Database.insert( ew, false);
            //Database.delete(ew, false);
             
             ew = new Enrolled_Wait_List__c();
             ew.Wait_List_Type__c=wlt.id;
             ew.Prefernce_Point__c=Decimal.valueof('1'); 
             ew.Applications__c=app.id;   
             ew.Current_Status__c= 'Issue/Offer';
             ew.Reason__c ='Active';

             //Database.insert( ew, false);
             //Database.delete(ew, false);

             ew = new Enrolled_Wait_List__c();
             ew.Wait_List_Type__c=wlt.id;
             ew.Prefernce_Point__c=Decimal.valueof('3'); 
             ew.Applications__c=app.id;   
             ew.Current_Status__c= 'Selected';
             ew.Reason__c ='Active';

             //Database.insert( ew, false);
             //Database.delete(ew, false);
             
             
        Test.stopTest();
    }
    
    public static testmethod void testWLBasicUPDT(){
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;    
        TestSuiteHelper.setupCustomSettings();
        Wait_List_Type__c wlt = [Select name, RADFamily__c, RADLive_Work_in_City_of_San_Diego__c, 
                RADNon_Elderly_Disabled__c, RADVeteran_Active_Military__c from Wait_List_Type__c where name ='Public Housing' limit 1];

        List<Contact> cts = TestSuiteHelper.setupPortalRequiredData();  

            Contact ct = cts[0];
            Applications__c app = [Select id, Family__c,Elderly_Family__c, Homeless_with_disability__c, Live_Work_in_City_of_San_Diego__c,
                        Non_Elderly_Disabled__c, Disabled_Family__c, Veteran_Family_of__c from Applications__c where Applicant__c =:ct.id limit 1];

            
            List<Enrolled_Wait_List__c> wlst = [Select RAD_Applied_Date_and_Time__c,  Applications__r.Family__c, Applications__r.Homeless_with_disability__c,
                Applications__r.Live_Work_in_City_of_San_Diego__c, Applications__r.Non_Elderly_Disabled__c , Applications__r.Veteran_Family_of__c  from Enrolled_Wait_List__c where Applications__c =: app.id ];
            //Database.delete(wlst, false);

        Test.startTest();

             //FOR UPDATE

             Enrolled_Wait_List__c ew = new Enrolled_Wait_List__c();
             ew.Wait_List_Type__c=wlt.id;
             
             ew.Prefernce_Point__c=Decimal.valueof('3'); 
             ew.Applications__c=app.id;   
             ew.Current_Status__c= 'Onlist';
             ew.Reason__c ='Active';
             ew.Status__c = 'On List';
             Database.insert( ew, false);
             
             ew = [Select RAD_Applied_Date_and_Time__c,  Applications__r.Family__c, Applications__r.Homeless_with_disability__c,
                Applications__r.Live_Work_in_City_of_San_Diego__c, Applications__r.Non_Elderly_Disabled__c , Applications__r.Disabled_Family__c, Applications__r.Veteran_Family_of__c  from Enrolled_Wait_List__c where Applications__c =: app.id limit 1];
             ew.Current_Status__c='On List'; 
             ew.Wait_List_Type__c=wlt.id;
             
             ew.Applications__r.Family__c = true;
             ew.Applications__r.Homeless_with_disability__c = false;
             ew.Applications__r.Live_Work_in_City_of_San_Diego__c = false;
             ew.Applications__r.Non_Elderly_Disabled__c = false;
             ew.Applications__r.Veteran_Family_of__c  = false;
             Database.update(ew, false);
             
             RAD_WaitListHelper.calculatePrefPoints(ew,wlt);
             RAD_WaitListHelper.calculatePrefPtsFromAppl(app,wlt);

             ew.Current_Status__c='Removed'; 
             Database.update(ew, false);
             
             ew.Current_Status__c='Leased'; 
             Database.update(ew, false);
             
             ew.Current_Status__c='Issue/Offer'; 
             Database.update(ew, false);
             
             ew.Current_Status__c='Selected'; 
             Database.update(ew, false);
             

             
        Test.stopTest();
    }
    public static testmethod void testWL(){
        Test.startTest();
            TestSuiteHelper.setupCustomSettings();
            TestSuiteHelper.setupPortalRequiredData();  

            List<Enrolled_Wait_List__c> wlst = [Select RAD_Applied_Date_and_Time__c from Enrolled_Wait_List__c where current_status__c ='Onlist'];
            
            for(Enrolled_Wait_List__c wl :wlst){
                wl.RAD_Applied_Date_and_Time__c =Datetime.Now();
            
            }
            Database.update(wlst, false);

        Test.stopTest();
    }
    public static testmethod void testWLS(){
        list<SwitchTrigger__c> sw_list = new List<SwitchTrigger__c>();
        SwitchTrigger__c sw = new SwitchTrigger__c(Name='Applications__c',Active__c=True);
        sw_list.add(sw);
        SwitchTrigger__c swWL = new SwitchTrigger__c(Name='Enrolled_Wait_List__c',Active__c=True);
        sw_list.add(swWL);
        insert sw_list;
        Wait_List_Type__c newSec8Type = new Wait_List_Type__c(Name='Section 8',YARDI_HMY__c=5);
        insert newSec8Type;
        
        Wait_List_Type__c wlt = [Select name from Wait_List_Type__c where name ='Section 8' limit 1];    
        Test.startTest();
            try {
                TestSuiteHelper.setupCustomSettings();
                TestSuiteHelper.setupPortalRequiredData();
            } catch(exception e) {
            }  



        Test.stopTest();
    }    
    

 
    
}