src/objects/Applications__c.object
<CustomObject>
    <label>Applications</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Memo__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Memos</relationshipLabel>
        <relationshipName>Memos_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_and_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes / Desc</label>
        <length>1998</length>
        <type>LongTextArea</type>
    </fields>
    <label>Memos</label>
    <nameField>
        <label>Memo Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RAD_AllMemosCntrl.cls
/****
Class Name : RAD_AllMemosCntrl
Purpose : This Class will display All Memos for each Application.
****/


public class RAD_AllMemosCntrl {
    
    public id appid{get;set;}
    public list<Memo__c> memoRecords{get;set;}
    
    
    public RAD_AllMemosCntrl(){
        appid = ApexPages.currentPage().getParameters().get('id');
        system.debug('Application Id' +appid);
        if(appid!=null)
        memoRecords = [select id, name,Applications__r.Name, Date_and_Time__c, Notes__c from Memo__c
                        where 
                        Applications__c = :appid];
        system.debug(memoRecords);
        
    }
    
}