src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checkbox_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Community Global User</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Housing Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Inspector</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>On-Site Manager</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Property Manager</fullName>
                </value>
                <value>
                    <fullName>Rehab HC Specialist</fullName>
                </value>
                <value>
                    <fullName>Resident Manager</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First - Housing Our Heroes</fullName>
                </value>
                <value>
                    <fullName>Landlord/Owner</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Community Member</fullName>
                </value>
                <value>
                    <fullName>Housing Specialist</fullName>
                </value>
                <value>
                    <fullName>Section 3 Resident</fullName>
                </value>
                <value>
                    <fullName>Primary Business Contact</fullName>
                </value>
                <value>
                    <fullName>Business Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Business Admin Contact</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Payroll Contact</fullName>
                </value>
                <value>
                    <fullName>Co-Owner</fullName>
                </value>
                <value>
                    <fullName>Housing First Client_FY18</fullName>
                </value>
                <value>
                    <fullName>Housing First Client - FY17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prospect_Number_YARDI__c</fullName>
        <label>Prospect Number(YARDI)</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SSN_TaxID__c</fullName>
        <label>SSN / TaxID</label>
        <length>15</length>
        <maskChar>asterisk</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Tenant_Number_YARDI__c</fullName>
        <label>Tenant Number (YARDI)</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>Rental Assistance Wait List Portal Record Type</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RAD_ContactTrigHlprTest.cls
@isTest
public class RAD_ContactTrigHlprTest{

    public static testmethod void testContact(){
        Test.startTest();
            TestSuiteHelper.setupCustomSettings();
            List<Contact> cts =TestSuiteHelper.setupPortalRequiredData();  
            Contact ct = cts[0];
            
            Contact ctt = [Select SSN_TaxID__c, Date_of_Birth__c, Gender__c, Prospect_Number_YARDI__c, Tenant_Number_YARDI__c from Contact where id=:ct.id limit 1];
            ctt.SSN_TaxID__c = '998998998';
            update ctt;       
                 
        Test.stopTest();
    }
    
    public static testmethod void testContact1(){

        Id idd = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
    
        Contact c = new contact(Gender__c='Male',LastName = 'sagar', Contact_Type__c = 'Community Global User', recordtypeid=idd, Active__c = 'Yes');
    
        insert c;
        c.SSN_TaxID__c='123456789';
        update c;
        
        
    }
    
}