src/objects/Enrolled_Wait_List__c.object
<CustomObject>
    <fields>
        <fullName>Bed_size__c</fullName>
        <label>Bed size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onlist</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Issue/Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait Lists</relationshipLabel>
        <relationshipName>Wait_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wait List</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Wait List ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Wait_List_Selection__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_at_LI_80__c</fullName>
        <label>Applicant at li-80</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Applicant_at_eli_30_75__c</fullName>
        <label>Applicant at eli-30 (75%)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Applicant_at_vli_50_25__c</fullName>
        <label>Applicant at vli-50 (25%)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bedroom_Size__c</fullName>
        <label>Bedroom Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_vacancies_to_fill__c</fullName>
        <label>Number of vacancies to fill</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_to_Select_from_List__c</fullName>
        <formula>CEILING (Number_of_vacancies_to_fill__c * (100 / VALUE( Wait_List_Type__r.Lease_Up__c ) ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number to Select from List</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Current_Scheduler_Count__c</fullName>
        <label>Current Scheduler Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Scheduler_Count__c</fullName>
        <label>Scheduler Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Eli_Count__c</fullName>
        <label>Temp Eli Count</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Li_Count__c</fullName>
        <label>Temp Li Count</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Number_to_Select__c</fullName>
        <label>Temp Number to Select</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Temp_Vli_Count__c</fullName>
        <label>Temp Vli Count</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait List Selections</relationshipLabel>
        <relationshipName>Wait_List_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Wait List Selection</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait List Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_PubHsgSelnCnt_Batch.cls
// This class will get the count of records for section 8 onlist WL and update the WLS for the given bedroom count

global class RAD_PubHsgSelnCnt_Batch implements Database.batchable<sObject>,Database.Stateful{
    String query;
    Decimal bedroomsz;
    global String wlsidd;
    global Decimal totalRecordCount;
    
     
    
    global RAD_PubHsgSelnCnt_Batch(string wlsid, Decimal bedroomsize){
    
        wlsidd=wlsid;
        totalRecordCount = 0;
        bedroomsz = bedroomsize;
        System.debug('the bedroom size iss '+bedroomsz);
        query = 'Select Name from Enrolled_Wait_List__c '+
                ' where CreatedDate >= 2018-07-19T19:12:41.000+0000 and Current_Status__c = \'Onlist\' and Wait_List_Type__r.Name =\'Public Housing\' and Bed_size__c =: bedroomsz ';
      
      system.debug('$$$$ Public Housing Batch Query' +query);
    }
    
    
    global  Database.QueryLocator start(Database.BatchableContext BC)
        
    {
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Enrolled_Wait_List__c> scope)    
    {
    
        if(!scope.isEmpty()){
           
            totalRecordCount += scope.size(); 
            
        }

    } 
   
    global void finish(Database.BatchableContext BC)     
    {    
    
         Wait_List_Selection__c  wls = [Select Applicant_at_eli_30_75__c, Applicant_at_vli_50_25__c, Applicant_at_LI_80__c, Bedroom_Size__c, RAD_Temp_Number_to_Select__c,
                                     Number_of_vacancies_to_fill__c,RAD_Scheduler_Count__c,RAD_Temp_Eli_Count__c,RAD_Temp_Vli_Count__c,RAD_Current_Scheduler_Count__c, RAD_Temp_Li_Count__c, Number_to_Select_from_List__c, Wait_List_Type__r.Id, Wait_List_Type__r.Name 
                                     from Wait_List_Selection__c where id =:wlsidd limit 1];
                                     
        wls.RAD_Temp_Eli_Count__c = wls.Applicant_at_eli_30_75__c==null?0:wls.Applicant_at_eli_30_75__c;
        wls.RAD_Temp_Vli_Count__c = wls.Applicant_at_vli_50_25__c==null?0:wls.Applicant_at_vli_50_25__c;
        wls.RAD_Temp_Li_Count__c  = wls.Applicant_at_LI_80__c==null?0:wls.Applicant_at_LI_80__c; //TODO OTHERS
        
        wls.RAD_Current_Scheduler_Count__c = 0;
        
        //wls.RAD_Scheduler_Count__c = totalRecordCount.divide(5000, 0, System.RoundingMode.UP); 
        wls.RAD_Scheduler_Count__c = totalRecordCount.divide(1000, 0, System.RoundingMode.UP); // TODO
        System.debug('rhathi the total count is totalRecordCount' + totalRecordCount);
        Database.update(wls, false);
        system.debug('$$$$ updating eli vli li fields '+wls);

    }            
    
}