src/objects/Memo__c.object
<CustomObject>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>Showing</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>Rejection</fullName>
                </value>
                <value>
                    <fullName>Move in</fullName>
                </value>
                <value>
                    <fullName>Wait List</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>A-App Status(Not Lv/wk SD)</fullName>
                </value>
                <value>
                    <fullName>A1- Out our Jurisdiction</fullName>
                </value>
                <value>
                    <fullName>B-App Status(iv/wk SD)</fullName>
                </value>
                <value>
                    <fullName>C-App Trans Received</fullName>
                </value>
                <value>
                    <fullName>D- App Trans to County</fullName>
                </value>
                <value>
                    <fullName>D1-App National City</fullName>
                </value>
                <value>
                    <fullName>D2- App Oceanside</fullName>
                </value>
                <value>
                    <fullName>D3-App Carlsbad</fullName>
                </value>
                <value>
                    <fullName>D4-App Encinitas</fullName>
                </value>
                <value>
                    <fullName>Ltr1- WL Confirmation</fullName>
                </value>
                <value>
                    <fullName>Ltr4-WL NE State</fullName>
                </value>
                <value>
                    <fullName>LtrIT-WL Ineligible to Trans</fullName>
                </value>
                <value>
                    <fullName>LtrUT-WL Unable to Trans</fullName>
                </value>
                <value>
                    <fullName>Ltr7- WL Claim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Memos</label>
    <nameField>
        <label>Memo Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transfer_Letter_Address__mdt.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Memo_Result__c</fullName>
        <label>Memo Result Value</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Transfer Letter Address</label>
    <pluralLabel>Transfer Letter Addresss</pluralLabel>
</CustomObject>

src/classes/RAD_TransferLetters.cls
public class RAD_TransferLetters{
    
    public Transfer_Letter_Address__mdt TransLettAddress{get;set;}
    public List<Memo__c> Memos{get;set;}
    
    public RAD_TransferLetters(ApexPages.StandardController controller){
        map<String,Transfer_Letter_Address__mdt> Traslettersmap = new  map<String,Transfer_Letter_Address__mdt>();
        String memoid= ApexPages.currentPage().getParameters().get('id') ; //getting the memo id.        
        String result;
        
        if(memoid!=null)
            result  = [select id, Result__c, Name  from Memo__c where id = :memoid].Result__c; // getting the value present on Result dropdown of Memo Object
        
        //looping through Transfer Letter Address custom metadata, checking result in Memo_Result__c and getting the addresses. 
        
        for(Transfer_Letter_Address__mdt trlsdd:  [select id, DeveloperName ,Name__c,label, Address__c, City__c, State__c, Zip_Code__c, Phone_Number__c, Memo_Result__c   
                                                   from Transfer_Letter_Address__mdt])
                                                   
            Traslettersmap.put(trlsdd.Memo_Result__c, trlsdd);
        
        if(result!=null)
            if(Traslettersmap.containskey(result))
            TransLettAddress = Traslettersmap.get(result);            
            
        
        
    }
    
}