src/objects/Preferences__c.object
<CustomObject>
    <fields>
        <fullName>Send_To_Boomi__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag is checked by Boomi to determine if a record is to be picked up and processed.</description>
        <inlineHelpText>If the box is checked, Boomi will pull the record on the next poll.  If the box is unchecked, Boomi will not pull the record.</inlineHelpText>
        <label>Send To Boomi</label>
        <type>Checkbox</type>
    </fields>
    <label>Preferences</label>
    <nameField>
        <label>Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PreferencesTriggerHandler.cls
public class PreferencesTriggerHandler extends TriggerHandler {
    public PreferencesTriggerHandler() {
    //this.setMaxLoopCount(1);
    }

    public override void beforeUpdate() {
       
          for(Preferences__c pref:(List< Preferences__c >) Trigger.new){
          if(!(UserInfo.getName() =='Dell Boomi'))
              pref.Send_To_Boomi__c=true;
        } 


    }
      
    public override void afterUpdate() {

    }

    public override void beforeInsert() {
        for(Preferences__c pref:(List< Preferences__c >) Trigger.new){
          if(!(UserInfo.getName() =='Dell Boomi'))
              pref.Send_To_Boomi__c=true;
        }
     

    }
    
    public override void afterInsert() {

    }

    public override void beforeDelete() {

    }

    public override void afterDelete() {

    }

    public override void afterUndelete() {
    
    }
}