src/objects/Wait_List_Selection__c.object
<CustomObject>
    <fields>
        <fullName>RAD_Current_Scheduler_Count__c</fullName>
        <label>Current Scheduler Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RAD_Scheduler_Count__c</fullName>
        <label>Scheduler Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wait_List_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wait List Type</label>
        <referenceTo>Wait_List_Type__c</referenceTo>
        <relationshipLabel>Wait List Selections</relationshipLabel>
        <relationshipName>Wait_List_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Wait List Selection</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Selection Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wait List Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Wait_List_Type__c.object
<CustomObject>
    <label>Wait List Type</label>
    <nameField>
        <label>Wait List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wait List Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAD_InitiateScheduler.cls
global class RAD_InitiateScheduler implements Schedulable{

    global String  wlsidd;   
        
    public RAD_InitiateScheduler(String wlsId){
        
        System.debug('rhathi in RAD_InitiateScheduler wlsid is '+wlsId);
        this.wlsidd =  wlsId;

        
        
    }           

    
    global void execute(SchedulableContext sc){
    
        Wait_List_Selection__c wls = [Select Wait_List_Type__r.name, RAD_Scheduler_Count__c, RAD_Current_Scheduler_Count__c from Wait_List_Selection__c where id =: wlsidd limit 1];           
        wls.RAD_Scheduler_Count__c = 0;
        update wls;
        
        
    }
    
}